package pkpInfo

/*
*	Generated by fireback 1.3.2
*	Written by Ali Torabi.
*	Checkout the repository for licenses and contribution: https://github.com/torabian/fireback
 */
import (
	"github.com/torabian/fireback/modules/fireback"
	"github.com/urfave/cli/v3"
)
import (
	"reflect"
)

// using shared actions here
/// For emi, we also need to print the handlers, and also print security model, which is a part of Fireback
/// and not available in Emi (won't be)
func PkpInfoCustomActions() []fireback.Module3Action {
	routes := []fireback.Module3Action{
		//// Let's add actions for emi acts
		/// End for emi actions
	}
	return routes
}

var PkpInfoCustomActionsCli = []*cli.Command{}

// Only to include some headers
func PkpInfoJsonInclude() {
	str4 := reflect.ValueOf(nil)
	_ = str4
}

// Use the actions bundle for ease and provide it to the ModuleProvider
// and it would gather all actions in the module level
var PkpInfoCliActionsBundle = &fireback.CliActionsBundle{
	Name:  "pkpInfo",
	Usage: ``,
	// Here we will include entities actions, as well as module level actions
	Commands: []*cli.Command{},
}

func GetPkpInfoActionsBundle() *fireback.ModuleActionsBundle {
	return &fireback.ModuleActionsBundle{
		Actions:   PkpInfoCustomActions(),
		CliAction: PkpInfoCliActionsBundle,
	}
}
func GetPkpInfoActionsCli() []*cli.Command {
	return PkpInfoCustomActionsCli
}
