package plugin

/*
*	Generated by fireback 1.2.4
*	Written by Ali Torabi.
*	Checkout the repository for licenses and contribution: https://github.com/torabian/fireback
 */
import (
	"embed"
	"encoding/json"
	"fmt"
	"log"
	reflect "reflect"
	"strings"
	"time"

	"github.com/gin-gonic/gin"
	jsoniter "github.com/json-iterator/go"
	metas "github.com/myorg/mynewmicroservice/modules/plugin/metas"
	mocks "github.com/myorg/mynewmicroservice/modules/plugin/mocks/Plugin"
	seeders "github.com/myorg/mynewmicroservice/modules/plugin/seeders/Plugin"
	"github.com/schollz/progressbar/v3"
	"github.com/torabian/fireback/modules/fireback"
	"github.com/urfave/cli"
	"gopkg.in/yaml.v2"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

var pluginSeedersFs = &seeders.ViewsFs

func ResetPluginSeeders(fs *embed.FS) {
	pluginSeedersFs = fs
}

type PluginEntityQs struct {
	Name    fireback.QueriableField `cli:"name" table:"plugin" typeof:"string" column:"name" qs:"name"`
	Enabled fireback.QueriableField `cli:"enabled" table:"plugin" typeof:"bool?" column:"enabled" qs:"enabled"`
	Content fireback.QueriableField `cli:"content" table:"plugin" typeof:"xfile?" column:"content" qs:"content"`
}

func (x *PluginEntityQs) GetQuery() string {
	return fireback.GenerateQueryStringStyle(reflect.ValueOf(x), "")
}

var PluginQsFlags = []cli.Flag{
	&cli.StringFlag{
		Name:  "name",
		Usage: "The name of the plugin",
	},
	&cli.StringFlag{
		Name:  "enabled",
		Usage: "",
	},
	&cli.StringFlag{
		Name:  "content",
		Usage: "The content of the plugin",
	},
}

type PluginEntity struct {
	// Defines the visibility of the record in the table.
	// Visibility is a detailed topic, you can check all of the visibility values in fireback/visibility.go
	// by default, visibility of record are 0, means they are protected by the workspace
	// which are being created, and visible to every member of the workspace
	Visibility fireback.String `json:"visibility,omitempty" yaml:"visibility,omitempty" xml:"visibility,omitempty"`
	// The unique-id of the workspace which content belongs to. Upon creation this will be designated
	// to the selected workspace by user, if they have write access. You can change this value
	// or prevent changes to it manually (on root features for example modifying other workspace)
	WorkspaceId fireback.String `json:"workspaceId,omitempty" xml:"workspaceId,omitempty" yaml:"workspaceId,omitempty"`
	// The unique-id of the parent table, which this record is being linked to.
	// used internally for making relations in fireback, generally does not need manual changes
	// or modification by the developer or user. For example, if you have a object inside an object
	// the unique-id of the parent will be written in the child.
	LinkerId fireback.String `json:"linkerId,omitempty" xml:"linkerId,omitempty" yaml:"linkerId,omitempty"`
	// Used for recursive or parent-child operations. Some tables, are having nested relations,
	// and this field makes the table self refrenceing. ParentId needs to exist in the table before
	// creating of modifying a record.
	ParentId fireback.String `json:"parentId,omitempty" xml:"parentId,omitempty" yaml:"parentId,omitempty"`
	// Makes a field deletable. Some records should not be deletable at all.
	// default it's true.
	IsDeletable *bool `json:"isDeletable,omitempty" xml:"isDeletable,omitempty" yaml:"isDeletable,omitempty" gorm:"default:true"`
	// Makes a field updatable. Some records should not be updatable at all.
	// default it's true.
	IsUpdatable *bool `json:"isUpdatable,omitempty" xml:"isUpdatable,omitempty" yaml:"isUpdatable,omitempty" gorm:"default:true"`
	// The unique-id of the user which is creating the record, or the record belongs to.
	// Administration might want to change this to any user, by default Fireback fills
	// it to the current authenticated user.
	UserId fireback.String `json:"userId,omitempty" xml:"userId,omitempty" yaml:"userId,omitempty"`
	// General mechanism to rank the elements. From code perspective, it's just a number,
	// but you can sort it based on any logic for records to make a ranking, sorting.
	// they should not be unique across a table.
	Rank fireback.Int64 `json:"rank,omitempty" yaml:"rank,omitempty" xml:"rank,omitempty" gorm:"type:int;name:rank"`
	// Primary numeric key in the database. This value is not meant to be exported to public
	// or be used to access data at all. Rather a mechanism of indexing columns internally
	// or cursor pagination in future releases of fireback, or better search performance.
	ID uint `gorm:"primaryKey;autoIncrement" json:"-" yaml:"-" xml:"-"`
	// Unique id of the record across the table. This value will be accessed from public APIs,
	// and many other places intead of numeric ID property.
	// Upon generation, a UUID automatically is being assigned, and if user has specified the
	// Unique id in the post body, it will be used. This mechanism allows to manage unsaved
	// content on front-end much easier than requiring parent to exists first.
	UniqueId string `json:"uniqueId,omitempty" xml:"uniqueId,omitempty" gorm:"unique;not null;size:100;" yaml:"uniqueId,omitempty"`
	// The time that the record has been updated in datetime.
	// the field will be automatically populated by gorm orm.
	UpdatedAt *time.Time `json:"updatedAt,omitempty" xml:"updatedAt,omitempty" yaml:"updatedAt,omitempty"`
	// The time that the record has been created in datetime.
	// the field will be automatically populated by gorm orm.
	CreatedAt *time.Time `json:"createdAt,omitempty" xml:"createdAt,omitempty" yaml:"createdAt,omitempty"`
	// The time that the record has been deleted softly (means the data still exists in database, but no longer visible to any feature) in nano datatime
	// you need to make sure check this field if writing custom sql queries.
	// the field will be automatically populated by gorm orm.
	DeletedAt *time.Time `json:"deletedAt,omitempty" xml:"deletedAt,omitempty" yaml:"deletedAt,omitempty"`
	// Record creation date time formatting based on locale of the headers, or other
	// possible factors.
	CreatedFormatted string `json:"createdFormatted,omitempty" xml:"createdFormatted,omitempty" yaml:"createdFormatted,omitempty" sql:"-" gorm:"-"`
	// Record update date time formatting based on locale of the headers, or other
	// possible factors.
	UpdatedFormatted string `json:"updatedFormatted,omitempty" xml:"updatedFormatted,omitempty" yaml:"updatedFormatted,omitempty" sql:"-" gorm:"-"`
	// The name of the plugin
	Name    string        `json:"name" xml:"name" yaml:"name"        `
	Enabled fireback.Bool `json:"enabled" xml:"enabled" yaml:"enabled"        `
	// The content of the plugin
	Content  fireback.XFile  `json:"content" xml:"content" yaml:"content"    gorm:"embedded;embeddedPrefix:content_"      `
	Children []*PluginEntity `csv:"-" gorm:"-" sql:"-" json:"children,omitempty" xml:"children,omitempty"  yaml:"children,omitempty"`
	LinkedTo *PluginEntity   `csv:"-" yaml:"-" gorm:"-" json:"-" sql:"-" xml:"-"`
}

func PluginEntityStream(q fireback.QueryDSL) (chan []*PluginEntity, *fireback.QueryResultMeta, *fireback.IError) {
	cn := make(chan []*PluginEntity)
	q.ItemsPerPage = 50
	q.StartIndex = 0
	_, qrm, err := PluginActions.Query(q)
	if err != nil {
		return nil, nil, err
	}
	go func() {
		defer close(cn)
		for i := 0; i <= int(qrm.TotalAvailableItems)-1; i++ {
			items, _, _ := PluginActions.Query(q)
			i += q.ItemsPerPage
			q.StartIndex = i
			cn <- items
		}
	}()
	return cn, qrm, nil
}

type PluginEntityList struct {
	Items []*PluginEntity
}

func NewPluginEntityList(items []*PluginEntity) *PluginEntityList {
	return &PluginEntityList{
		Items: items,
	}
}
func (x *PluginEntityList) Json() string {
	if x != nil {
		str, _ := json.MarshalIndent(x, "", "  ")
		return (string(str))
	}
	return ""
}
func (x *PluginEntityList) ToTree() *fireback.TreeOperation[PluginEntity] {
	return fireback.NewTreeOperation(
		x.Items,
		func(t *PluginEntity) string {
			if !t.ParentId.Valid {
				return ""
			}
			return t.ParentId.String
		},
		func(t *PluginEntity) string {
			return t.UniqueId
		},
	)
}

var PluginPreloadRelations []string = []string{}

type pluginActionsSig struct {
	Update         func(query fireback.QueryDSL, dto *PluginEntity) (*PluginEntity, *fireback.IError)
	Create         func(dto *PluginEntity, query fireback.QueryDSL) (*PluginEntity, *fireback.IError)
	Upsert         func(dto *PluginEntity, query fireback.QueryDSL) (*PluginEntity, *fireback.IError)
	SeederInit     func() *PluginEntity
	Remove         func(query fireback.QueryDSL) (int64, *fireback.IError)
	MultiInsert    func(dtos []*PluginEntity, query fireback.QueryDSL) ([]*PluginEntity, *fireback.IError)
	GetOne         func(query fireback.QueryDSL) (*PluginEntity, *fireback.IError)
	GetByWorkspace func(query fireback.QueryDSL) (*PluginEntity, *fireback.IError)
	Query          func(query fireback.QueryDSL) ([]*PluginEntity, *fireback.QueryResultMeta, *fireback.IError)
}

var PluginActions pluginActionsSig = pluginActionsSig{
	Update:         PluginActionUpdateFn,
	Create:         PluginActionCreateFn,
	Upsert:         PluginActionUpsertFn,
	Remove:         PluginActionRemoveFn,
	SeederInit:     PluginActionSeederInitFn,
	MultiInsert:    PluginMultiInsertFn,
	GetOne:         PluginActionGetOneFn,
	GetByWorkspace: PluginActionGetByWorkspaceFn,
	Query:          PluginActionQueryFn,
}

func PluginActionUpsertFn(dto *PluginEntity, query fireback.QueryDSL) (*PluginEntity, *fireback.IError) {
	return nil, nil
}

var PLUGIN_EVENT_CREATED = "plugin.created"
var PLUGIN_EVENT_UPDATED = "plugin.updated"
var PLUGIN_EVENT_DELETED = "plugin.deleted"
var PLUGIN_EVENTS = []string{
	PLUGIN_EVENT_CREATED,
	PLUGIN_EVENT_UPDATED,
	PLUGIN_EVENT_DELETED,
}

type PluginFieldMap struct {
	Name    fireback.TranslatedString `yaml:"name"`
	Enabled fireback.TranslatedString `yaml:"enabled"`
	Content fireback.TranslatedString `yaml:"content"`
}

var PluginEntityMetaConfig map[string]int64 = map[string]int64{}
var PluginEntityJsonSchema = fireback.ExtractEntityFields(reflect.ValueOf(&PluginEntity{}))

func entityPluginFormatter(dto *PluginEntity, query fireback.QueryDSL) {
	if dto == nil {
		return
	}
}
func PluginActionSeederMultiple(query fireback.QueryDSL, count int) {
	successInsert := 0
	failureInsert := 0
	batchSize := 100
	bar := progressbar.Default(int64(count))
	// Collect entities in batches
	var entitiesBatch []*PluginEntity
	for i := 1; i <= count; i++ {
		entity := PluginActions.SeederInit()
		entitiesBatch = append(entitiesBatch, entity)
		// When batch size is reached, perform the batch insert
		if len(entitiesBatch) == batchSize || i == count {
			// Insert batch
			_, err := PluginActions.MultiInsert(entitiesBatch, query)
			if err == nil {
				successInsert += len(entitiesBatch)
			} else {
				fmt.Println(err)
				failureInsert += len(entitiesBatch)
			}
			// Clear the batch after insert
			entitiesBatch = nil
		}
		bar.Add(1)
	}
	fmt.Println("Success", successInsert, "Failure", failureInsert)
}
func PluginActionSeeder(query fireback.QueryDSL, count int) {
	successInsert := 0
	failureInsert := 0
	bar := progressbar.Default(int64(count))
	for i := 1; i <= count; i++ {
		entity := PluginActions.SeederInit()
		_, err := PluginActions.Create(entity, query)
		if err == nil {
			successInsert++
		} else {
			fmt.Println(err)
			failureInsert++
		}
		bar.Add(1)
	}
	fmt.Println("Success", successInsert, "Failure", failureInsert)
}
func (x *PluginEntity) Seeder() string {
	obj := PluginActions.SeederInit()
	v, _ := json.MarshalIndent(obj, "", "  ")
	return string(v)
}
func PluginActionSeederInitFn() *PluginEntity {
	entity := &PluginEntity{}
	return entity
}
func PluginAssociationCreate(dto *PluginEntity, query fireback.QueryDSL) error {
	return nil
}

/**
* These kind of content are coming from another entity, which is indepndent module
* If we want to create them, we need to do it before. This is not association.
**/
func PluginRelationContentCreate(dto *PluginEntity, query fireback.QueryDSL) error {
	return nil
}
func PluginRelationContentUpdate(dto *PluginEntity, query fireback.QueryDSL) error {
	return nil
}
func PluginPolyglotUpdateHandler(dto *PluginEntity, query fireback.QueryDSL) {
	if dto == nil {
		return
	}
}

/**
 * This will be validating your entity fully. Important note is that, you add validate:* tag
 * in your entity, it will automatically work here. For slices inside entity, make sure you add
 * extra line of AppendSliceErrors, otherwise they won't be detected
 */
func PluginValidator(dto *PluginEntity, isPatch bool) *fireback.IError {
	err := fireback.CommonStructValidatorPointer(dto, isPatch)
	return err
}

// Creates a set of natural language queries, which can be used with
// AI tools to create content or help with some tasks
var PluginAskCmd cli.Command = cli.Command{
	Name:  "nlp",
	Usage: "Set of natural language queries which helps creating content or data",
	Subcommands: []cli.Command{
		{
			Name:  "sample",
			Usage: "Asks for generating sample by giving an example data",
			Flags: []cli.Flag{
				&cli.StringFlag{
					Name:  "format",
					Usage: "Format of the export or import file. Can be 'yaml', 'yml', 'json'",
					Value: "yaml",
				},
				&cli.IntFlag{
					Name:  "count",
					Usage: "How many samples to ask",
					Value: 30,
				},
			},
			Action: func(c *cli.Context) error {
				v := &PluginEntity{}
				format := c.String("format")
				request := "\033[1m" + `
I need you to create me an array of exact signature as the example given below,
with at least ` + fmt.Sprint(c.String("count")) + ` items, mock the content with few words, and guess the possible values
based on the common sense. I need the output to be a valid ` + format + ` file.
Make sure you wrap the entire array in 'items' field. Also before that, I provide some explanation of each field:
Name: (type: string) Description: The name of the plugin
Enabled: (type: bool?) Description: 
Content: (type: xfile?) Description: The content of the plugin
And here is the actual object signature:
` + v.Seeder() + `
`
				fmt.Println(request)
				return nil
			},
		},
	},
}

func PluginEntityPreSanitize(dto *PluginEntity, query fireback.QueryDSL) {
}
func PluginEntityBeforeCreateAppend(dto *PluginEntity, query fireback.QueryDSL) {
	if dto.UniqueId == "" {
		dto.UniqueId = fireback.UUID()
	}
	dto.WorkspaceId = fireback.NewString(query.WorkspaceId)
	dto.UserId = fireback.NewString(query.UserId)
	PluginRecursiveAddUniqueId(dto, query)
}
func PluginRecursiveAddUniqueId(dto *PluginEntity, query fireback.QueryDSL) {
}

/*
*

		Batch inserts, do not have all features that create
		operation does. Use it with unnormalized content,
		or read the source code carefully.
	  This is not marked as an action, because it should not be available publicly
	  at this moment.

*
*/
func PluginMultiInsertFn(dtos []*PluginEntity, query fireback.QueryDSL) ([]*PluginEntity, *fireback.IError) {
	if len(dtos) > 0 {
		for index := range dtos {
			PluginEntityPreSanitize(dtos[index], query)
			PluginEntityBeforeCreateAppend(dtos[index], query)
		}
		var dbref *gorm.DB = nil
		if query.Tx == nil {
			dbref = fireback.GetDbRef()
		} else {
			dbref = query.Tx
		}
		query.Tx = dbref
		err := dbref.Create(&dtos).Error
		if err != nil {
			return nil, fireback.GormErrorToIError(err)
		}
	}
	return dtos, nil
}
func PluginActionBatchCreateFn(dtos []*PluginEntity, query fireback.QueryDSL) ([]*PluginEntity, *fireback.IError) {
	if dtos != nil && len(dtos) > 0 {
		items := []*PluginEntity{}
		for _, item := range dtos {
			s, err := PluginActions.Create(item, query)
			if err != nil {
				return nil, err
			}
			items = append(items, s)
		}
		return items, nil
	}
	return dtos, nil
}
func PluginDeleteEntireChildren(query fireback.QueryDSL, dto *PluginEntity) *fireback.IError {
	// intentionally removed this. It's hard to implement it, and probably wrong without
	// proper on delete cascade
	return nil
}
func PluginActionCreateFn(dto *PluginEntity, query fireback.QueryDSL) (*PluginEntity, *fireback.IError) {
	// 1. Validate always
	if iError := PluginValidator(dto, false); iError != nil {
		return nil, iError
	}
	// 1.5 Sanitize the content coming of the front-end
	PluginEntityPreSanitize(dto, query)
	// 2. Append the necessary information about user, workspace
	PluginEntityBeforeCreateAppend(dto, query)
	// 3. Create other entities if we want select from them
	PluginRelationContentCreate(dto, query)
	// 4. Create the entity
	var dbref *gorm.DB = nil
	if query.Tx == nil {
		dbref = fireback.GetDbRef()
	} else {
		dbref = query.Tx
	}
	query.Tx = dbref
	err := dbref.Create(&dto).Error
	if err != nil {
		err := fireback.GormErrorToIError(err)
		return nil, err
	}
	// 5. Create sub entities, objects or arrays, association to other entities
	PluginAssociationCreate(dto, query)
	// 6. Fire the event into system
	actionEvent, eventErr := NewPluginCreatedEvent(dto, &query)
	if actionEvent != nil && eventErr == nil {
		fireback.GetEventBusInstance().FireEvent(query, *actionEvent)
	} else {
		log.Default().Panicln("Creating event has failed for %v", dto)
	}
	/*
		event.MustFire(PLUGIN_EVENT_CREATED, event.M{
			"entity":   dto,
			"entityKey": fireback.GetTypeString(&PluginEntity{}),
			"target":   "workspace",
			"unqiueId": query.WorkspaceId,
		})
	*/
	return dto, nil
}
func PluginActionGetOneFn(query fireback.QueryDSL) (*PluginEntity, *fireback.IError) {
	refl := reflect.ValueOf(&PluginEntity{})
	item, err := fireback.GetOneEntity[PluginEntity](query, refl)
	entityPluginFormatter(item, query)
	return item, err
}
func PluginActionGetByWorkspaceFn(query fireback.QueryDSL) (*PluginEntity, *fireback.IError) {
	refl := reflect.ValueOf(&PluginEntity{})
	item, err := fireback.GetOneByWorkspaceEntity[PluginEntity](query, refl)
	entityPluginFormatter(item, query)
	return item, err
}
func PluginActionQueryFn(query fireback.QueryDSL) ([]*PluginEntity, *fireback.QueryResultMeta, *fireback.IError) {
	refl := reflect.ValueOf(&PluginEntity{})
	items, meta, err := fireback.QueryEntitiesPointer[PluginEntity](query, refl)
	for _, item := range items {
		entityPluginFormatter(item, query)
	}
	return items, meta, err
}

var pluginMemoryItems []*PluginEntity = []*PluginEntity{}

func PluginEntityIntoMemory() {
	q := fireback.QueryDSL{
		ItemsPerPage: 500,
		StartIndex:   0,
	}
	_, qrm, _ := PluginActions.Query(q)
	for i := 0; i <= int(qrm.TotalAvailableItems)-1; i++ {
		items, _, _ := PluginActions.Query(q)
		pluginMemoryItems = append(pluginMemoryItems, items...)
		i += q.ItemsPerPage
		q.StartIndex = i
	}
}
func PluginMemGet(id uint) *PluginEntity {
	for _, item := range pluginMemoryItems {
		if item.ID == id {
			return item
		}
	}
	return nil
}
func PluginMemJoin(items []uint) []*PluginEntity {
	res := []*PluginEntity{}
	for _, item := range items {
		v := PluginMemGet(item)
		if v != nil {
			res = append(res, v)
		}
	}
	return res
}
func PluginUpdateExec(dbref *gorm.DB, query fireback.QueryDSL, fields *PluginEntity) (*PluginEntity, *fireback.IError) {
	uniqueId := fields.UniqueId
	query.TriggerEventName = PLUGIN_EVENT_UPDATED
	PluginEntityPreSanitize(fields, query)
	var item PluginEntity
	var itemRefetched PluginEntity
	// If the entity is distinct by workspace, then the Query.WorkspaceId
	// which is selected is being used as the condition for create or update
	// if not, the unique Id is being used
	cond2 := &PluginEntity{UniqueId: uniqueId}
	q := dbref.
		Where(cond2).
		FirstOrCreate(&item)
	err := q.UpdateColumns(fields).Error
	if err != nil {
		return nil, fireback.GormErrorToIError(err)
	}
	query.Tx = dbref
	PluginRelationContentUpdate(fields, query)
	PluginPolyglotUpdateHandler(fields, query)
	if ero := PluginDeleteEntireChildren(query, fields); ero != nil {
		return nil, ero
	}
	// @meta(update has many)
	err = dbref.
		Preload(clause.Associations).
		Where(&PluginEntity{UniqueId: uniqueId}).
		First(&itemRefetched).Error
	if err != nil {
		return nil, fireback.GormErrorToIError(err)
	}
	actionEvent, eventErr := NewPluginUpdatedEvent(fields, &query)
	if actionEvent != nil && eventErr == nil {
		fireback.GetEventBusInstance().FireEvent(query, *actionEvent)
	} else {
		log.Default().Panicln("Updating event has failed for %v", fields)
	}
	/*
	   event.MustFire(query.TriggerEventName, event.M{
	     "entity":   &item,
	     "target":   "workspace",
	     "unqiueId": query.WorkspaceId,
	   })*/
	return &itemRefetched, nil
}
func PluginActionUpdateFn(query fireback.QueryDSL, fields *PluginEntity) (*PluginEntity, *fireback.IError) {
	if fields == nil {
		return nil, fireback.Create401Error(&fireback.FirebackMessages.BodyIsMissing, []string{})
	}
	// 1. Validate always
	if iError := PluginValidator(fields, true); iError != nil {
		return nil, iError
	}
	// Let's not add this. I am not sure of the consequences
	// PluginRecursiveAddUniqueId(fields, query)
	var dbref *gorm.DB = nil
	if query.Tx == nil {
		dbref = fireback.GetDbRef()
		var item *PluginEntity
		vf := dbref.Transaction(func(tx *gorm.DB) error {
			dbref = tx
			var err *fireback.IError
			item, err = PluginUpdateExec(dbref, query, fields)
			if err == nil {
				return nil
			} else {
				return err
			}
		})
		return item, fireback.CastToIError(vf)
	} else {
		dbref = query.Tx
		return PluginUpdateExec(dbref, query, fields)
	}
}

var PluginWipeCmd cli.Command = cli.Command{
	Name:  "wipe",
	Usage: "Wipes entire plugins ",
	Action: func(c *cli.Context) error {
		query := fireback.CommonCliQueryDSLBuilderAuthorize(c, &fireback.SecurityModel{
			ActionRequires: []fireback.PermissionInfo{PERM_ROOT_PLUGIN_DELETE},
		})
		count, _ := PluginActionWipeClean(query)
		fmt.Println("Removed", count, "of entities")
		return nil
	},
}

func PluginActionRemoveFn(query fireback.QueryDSL) (int64, *fireback.IError) {
	refl := reflect.ValueOf(&PluginEntity{})
	query.ActionRequires = []fireback.PermissionInfo{PERM_ROOT_PLUGIN_DELETE}
	return fireback.RemoveEntity[PluginEntity](query, refl)
}
func PluginActionWipeClean(query fireback.QueryDSL) (int64, error) {
	var err error
	var count int64 = 0
	{
		subCount, subErr := fireback.WipeCleanEntity[PluginEntity]()
		if subErr != nil {
			fmt.Println("Error while wiping 'PluginEntity'", subErr)
			return count, subErr
		} else {
			count += subCount
		}
	}
	return count, err
}
func PluginActionBulkUpdate(
	query fireback.QueryDSL, dto *fireback.BulkRecordRequest[PluginEntity]) (
	*fireback.BulkRecordRequest[PluginEntity], *fireback.IError,
) {
	result := []*PluginEntity{}
	err := fireback.GetDbRef().Transaction(func(tx *gorm.DB) error {
		query.Tx = tx
		for _, record := range dto.Records {
			item, err := PluginActions.Update(query, record)
			if err != nil {
				return err
			} else {
				result = append(result, item)
			}
		}
		return nil
	})
	if err == nil {
		return dto, nil
	}
	return nil, err.(*fireback.IError)
}
func (x *PluginEntity) Json() string {
	if x != nil {
		str, _ := json.MarshalIndent(x, "", "  ")
		return (string(str))
	}
	return ""
}

var PluginEntityMeta = fireback.TableMetaData{
	EntityName:    "Plugin",
	ExportKey:     "plugins",
	TableNameInDb: "plugin_entities",
	EntityObject:  &PluginEntity{},
	ExportStream:  PluginActionExportT,
	ImportQuery:   PluginActionImport,
}

func PluginActionExport(
	query fireback.QueryDSL,
) (chan []byte, *fireback.IError) {
	return fireback.YamlExporterChannel[PluginEntity](query, PluginActions.Query, PluginPreloadRelations)
}
func PluginActionExportT(
	query fireback.QueryDSL,
) (chan []interface{}, *fireback.IError) {
	return fireback.YamlExporterChannelT[PluginEntity](query, PluginActions.Query, PluginPreloadRelations)
}
func PluginActionImport(
	dto interface{}, query fireback.QueryDSL,
) *fireback.IError {
	var json = jsoniter.ConfigCompatibleWithStandardLibrary
	var content PluginEntity
	cx, err2 := json.Marshal(dto)
	if err2 != nil {
		return fireback.Create401Error(&fireback.FirebackMessages.InvalidContent, []string{})
	}
	json.Unmarshal(cx, &content)
	_, err := PluginActions.Create(&content, query)
	return err
}

var PluginCommonCliFlags = []cli.Flag{
	&cli.StringFlag{
		Name:  "x-accept",
		Usage: "Return type of the the content, such as json or yaml",
	},
	&cli.StringFlag{
		Name:     "wid",
		Required: false,
		Usage:    "Provide workspace id, if you want to change the data workspace",
	},
	&cli.StringFlag{
		Name:     "uid",
		Required: false,
		Usage:    "Unique Id - external unique hash to query entity",
	},
	&cli.StringFlag{
		Name:     "pid",
		Required: false,
		Usage:    " Parent record id of the same type",
	},
	&cli.StringFlag{
		Name:     "name",
		Required: false,
		Usage:    `The name of the plugin (string)`,
	},
	&cli.StringFlag{
		Name:     "enabled",
		Required: false,
		Usage:    `enabled (bool?)`,
	},
	&cli.StringFlag{
		Name:     "content",
		Required: false,
		Usage:    `The content of the plugin (xfile?)`,
	},
}
var PluginCommonInteractiveCliFlags = []fireback.CliInteractiveFlag{
	{
		Name:        "name",
		StructField: "Name",
		Required:    false,
		Recommended: false,
		Usage:       `The name of the plugin`,
		Type:        "string",
	},
}
var PluginCommonCliFlagsOptional = []cli.Flag{
	&cli.StringFlag{
		Name:     "x-src",
		Required: false,
		Usage:    `Import the body of the request from a file (e.g. json/yaml) on the disk`,
	},
	&cli.StringFlag{
		Name:  "x-accept",
		Usage: "Return type of the the content, such as json or yaml",
	},
	&cli.StringFlag{
		Name:     "wid",
		Required: false,
		Usage:    "Provide workspace id, if you want to change the data workspace",
	},
	&cli.StringFlag{
		Name:     "uid",
		Required: false,
		Usage:    "Unique Id - external unique hash to query entity",
	},
	&cli.StringFlag{
		Name:     "pid",
		Required: false,
		Usage:    " Parent record id of the same type",
	},
	&cli.StringFlag{
		Name:     "name",
		Required: false,
		Usage:    `The name of the plugin (string)`,
	},
	&cli.StringFlag{
		Name:     "enabled",
		Required: false,
		Usage:    `enabled (bool?)`,
	},
	&cli.StringFlag{
		Name:     "content",
		Required: false,
		Usage:    `The content of the plugin (xfile?)`,
	},
}
var PluginCreateCmd cli.Command = PLUGIN_ACTION_POST_ONE.ToCli()
var PluginCreateInteractiveCmd cli.Command = cli.Command{
	Name:  "ic",
	Usage: "Creates a new entity, using requied fields in an interactive name",
	Flags: []cli.Flag{
		&cli.BoolFlag{
			Name:  "all",
			Usage: "Interactively asks for all inputs, not only required ones",
		},
	},
	Action: func(c *cli.Context) {
		query := fireback.CommonCliQueryDSLBuilderAuthorize(c, &fireback.SecurityModel{
			ActionRequires: []fireback.PermissionInfo{PERM_ROOT_PLUGIN_CREATE},
		})
		entity := &PluginEntity{}
		fireback.PopulateInteractively(entity, c, PluginCommonInteractiveCliFlags)
		if entity, err := PluginActions.Create(entity, query); err != nil {
			fmt.Println(err.Error())
		} else {
			f, _ := yaml.Marshal(entity)
			fmt.Println(fireback.FormatYamlKeys(string(f)))
		}
	},
}
var PluginUpdateCmd cli.Command = cli.Command{
	Name:    "update",
	Aliases: []string{"u"},
	Flags:   PluginCommonCliFlagsOptional,
	Usage:   "Updates entity by passing the parameters",
	Action: func(c *cli.Context) error {
		query := fireback.CommonCliQueryDSLBuilderAuthorize(c, &fireback.SecurityModel{
			ActionRequires: []fireback.PermissionInfo{PERM_ROOT_PLUGIN_UPDATE},
		})
		entity := CastPluginFromCli(c)
		if entity, err := PluginActions.Update(query, entity); err != nil {
			fmt.Println(err.Error())
		} else {
			f, _ := json.MarshalIndent(entity, "", "  ")
			fmt.Println(string(f))
		}
		return nil
	},
}

func (x *PluginEntity) FromCli(c *cli.Context) *PluginEntity {
	return CastPluginFromCli(c)
}
func CastPluginFromCli(c *cli.Context) *PluginEntity {
	template := &PluginEntity{}
	fireback.HandleXsrc(c, template)
	if c.IsSet("uid") {
		template.UniqueId = c.String("uid")
	}
	if c.IsSet("pid") {
		template.ParentId = fireback.NewStringAutoNull(c.String("pid"))
	}
	if c.IsSet("name") {
		template.Name = c.String("name")
	}
	if c.IsSet("content") {
		template.Content = fireback.NewXFileAutoNull(c.String("content"))
	}
	if c.IsSet("enabled") {
		template.Enabled = fireback.NewBoolAutoNull(c.String("enabled"))
	}
	return template
}
func PluginSyncSeederFromFs(fsRef *embed.FS, fileNames []string, q fireback.QueryDSL) {
	fireback.SeederFromFSImport(
		q,
		PluginActions.Create,
		reflect.ValueOf(&PluginEntity{}).Elem(),
		fsRef,
		fileNames,
		true,
	)
}
func PluginSyncSeeders() {
	fireback.SeederFromFSImport(
		fireback.QueryDSL{WorkspaceId: fireback.USER_SYSTEM},
		PluginActions.Create,
		reflect.ValueOf(&PluginEntity{}).Elem(),
		pluginSeedersFs,
		[]string{},
		true,
	)
}
func PluginImportMocks() {
	fireback.SeederFromFSImport(
		fireback.QueryDSL{},
		PluginActions.Create,
		reflect.ValueOf(&PluginEntity{}).Elem(),
		&mocks.ViewsFs,
		[]string{},
		false,
	)
}
func PluginWriteQueryMock(ctx fireback.MockQueryContext) {
	for _, lang := range ctx.Languages {
		itemsPerPage := 9999
		if ctx.ItemsPerPage > 0 {
			itemsPerPage = ctx.ItemsPerPage
		}
		f := fireback.QueryDSL{ItemsPerPage: itemsPerPage, Language: lang, WithPreloads: ctx.WithPreloads, Deep: true}
		items, count, _ := PluginActions.Query(f)
		result := fireback.QueryEntitySuccessResult(f, items, count)
		fireback.WriteMockDataToFile(lang, "", "Plugin", result)
	}
}
func PluginsActionQueryString(keyword string, page int) ([]string, *fireback.QueryResultMeta, *fireback.IError) {
	searchFields := []string{
		`unique_id %"{keyword}"%`,
		`name %"{keyword}"%`,
	}
	m := func(item *PluginEntity) string {
		label := item.UniqueId
		// if item.Name != nil {
		// 	label += " >>> " + *item.Name
		// }
		return label
	}
	query := fireback.QueryStringCastCli(searchFields, keyword, page)
	items, meta, err := PluginActions.Query(query)
	stringItems := []string{}
	for _, item := range items {
		label := m(item)
		stringItems = append(stringItems, label)
	}
	return stringItems, meta, err
}

var PluginDevCommands = []cli.Command{
	PluginWipeCmd,
	{
		Name:  "mock",
		Usage: "Generates mock records based on the entity definition",
		Flags: []cli.Flag{
			&cli.IntFlag{
				Name:  "count",
				Usage: "how many activation key do you need to be generated and stored in database",
				Value: 10,
			},
			&cli.BoolFlag{
				Name:  "batch",
				Usage: "Multiple insert into database mode. Might miss children and relations at the moment",
			},
		},
		Action: func(c *cli.Context) error {
			query := fireback.CommonCliQueryDSLBuilderAuthorize(c, &fireback.SecurityModel{
				ActionRequires: []fireback.PermissionInfo{PERM_ROOT_PLUGIN_CREATE},
			})
			if c.Bool("batch") {
				PluginActionSeederMultiple(query, c.Int("count"))
			} else {
				PluginActionSeeder(query, c.Int("count"))
			}
			return nil
		},
	},
	{
		Name:    "init",
		Aliases: []string{"i"},
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:  "format",
				Usage: "Format of the export or import file. Can be 'yaml', 'yml', 'json'",
				Value: "yaml",
			},
		},
		Usage: "Creates a basic seeder file for you, based on the definition module we have. You can populate this file as an example",
		Action: func(c *cli.Context) error {
			seed := PluginActions.SeederInit()
			fireback.CommonInitSeeder(strings.TrimSpace(c.String("format")), seed)
			return nil
		},
	},
	cli.Command{
		Name:  "mlist",
		Usage: "Prints the list of embedded mocks into the app",
		Action: func(c *cli.Context) error {
			if entity, err := fireback.GetSeederFilenames(&mocks.ViewsFs, ""); err != nil {
				fmt.Println(err.Error())
			} else {
				f, _ := json.MarshalIndent(entity, "", "  ")
				fmt.Println(string(f))
			}
			return nil
		},
	},
	cli.Command{
		Name:  "msync",
		Usage: "Tries to sync mocks into the system",
		Action: func(c *cli.Context) error {
			fireback.CommonCliImportEmbedCmd(c,
				PluginActions.Create,
				reflect.ValueOf(&PluginEntity{}).Elem(),
				&mocks.ViewsFs,
			)
			return nil
		},
	},
}
var PluginImportExportCommands = []cli.Command{
	{
		Name:    "validate",
		Aliases: []string{"v"},
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:  "file",
				Usage: "Validates an import file, such as yaml, json, csv, and gives some insights how the after import it would look like",
				Value: "plugin-seeder-plugin.yml",
				// Uncomment before publish, they need to specify
				// Required: true,
			},
			&cli.StringFlag{
				Name:  "format",
				Usage: "Format of the export or import file. Can be 'yaml', 'yml', 'json'",
				Value: "yaml",
			},
		},
		Usage: "Reads a yaml file containing an array of plugins, you can run this to validate if your import file is correct, and how it would look like after import",
		Action: func(c *cli.Context) error {
			data := &[]PluginEntity{}
			fireback.ReadYamlFile(c.String("file"), data)
			fmt.Println(data)
			return nil
		},
	},
	cli.Command{
		Name:  "slist",
		Usage: "Prints the list of files attached to this module for syncing or bootstrapping project",
		Action: func(c *cli.Context) error {
			if entity, err := fireback.GetSeederFilenames(pluginSeedersFs, ""); err != nil {
				fmt.Println(err.Error())
			} else {
				f, _ := json.MarshalIndent(entity, "", "  ")
				fmt.Println(string(f))
			}
			return nil
		},
	},
	cli.Command{
		Name:  "ssync",
		Usage: "Tries to sync the embedded content into the database, the list could be seen by 'slist' command",
		Action: func(c *cli.Context) error {
			fireback.CommonCliImportEmbedCmd(c,
				PluginActions.Create,
				reflect.ValueOf(&PluginEntity{}).Elem(),
				pluginSeedersFs,
			)
			return nil
		},
	},
	cli.Command{
		Name:    "export",
		Aliases: []string{"e"},
		Flags: append(fireback.CommonQueryFlags,
			&cli.StringFlag{
				Name:     "file",
				Usage:    "The address of file you want the csv/yaml/json be exported to",
				Required: true,
			}),
		Usage: "Exports a query results into the csv/yaml/json format",
		Action: func(c *cli.Context) error {
			return fireback.CommonCliExportCmd2(c,
				PluginEntityStream,
				reflect.ValueOf(&PluginEntity{}).Elem(),
				c.String("file"),
				&metas.MetaFs,
				"PluginFieldMap.yml",
				PluginPreloadRelations,
			)
		},
	},
	cli.Command{
		Name: "import",
		Flags: append(
			append(
				fireback.CommonQueryFlags,
				&cli.StringFlag{
					Name:     "file",
					Usage:    "The address of file you want the csv be imported from",
					Required: true,
				}),
			PluginCommonCliFlagsOptional...,
		),
		Usage: "imports csv/yaml/json file and place it and its children into database",
		Action: func(c *cli.Context) error {
			fireback.CommonCliImportCmdAuthorized(c,
				PluginActions.Create,
				reflect.ValueOf(&PluginEntity{}).Elem(),
				c.String("file"),
				&fireback.SecurityModel{
					ActionRequires: []fireback.PermissionInfo{PERM_ROOT_PLUGIN_CREATE},
				},
				func() PluginEntity {
					v := CastPluginFromCli(c)
					return *v
				},
			)
			return nil
		},
	},
}
var PluginCliCommands []cli.Command = []cli.Command{
	PLUGIN_ACTION_QUERY.ToCli(),
	PLUGIN_ACTION_TABLE.ToCli(),
	PLUGIN_ACTION_PATCH.ToCli(),
	PluginCreateCmd,
	PluginAskCmd,
	PluginCreateInteractiveCmd,
	fireback.GetCommonRemoveQuery(
		reflect.ValueOf(&PluginEntity{}).Elem(),
		PluginActions.Remove,
	),
}

func PluginCliFn() cli.Command {
	commands := append(PluginImportExportCommands, PluginCliCommands...)
	if !fireback.GetConfig().Production {
		commands = append(commands, PluginDevCommands...)
	}
	return cli.Command{
		Name:        "plugin",
		Description: "Plugins module actions",
		Usage:       `A list of active plugins in the project.`,
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:  "language",
				Value: "en",
			},
		},
		Subcommands: commands,
	}
}

var PLUGIN_ACTION_TABLE = fireback.Module3Action{
	Name:          "table",
	ActionAliases: []string{"t"},
	Flags:         fireback.CommonQueryFlags,
	Description:   "Table formatted queries all of the entities in database based on the standard query format",
	Action:        PluginActions.Query,
	CliAction: func(c *cli.Context, security *fireback.SecurityModel) error {
		fireback.CommonCliTableCmd2(c,
			PluginActions.Query,
			security,
			reflect.ValueOf(&PluginEntity{}).Elem(),
		)
		return nil
	},
}
var PLUGIN_ACTION_QUERY = fireback.Module3Action{
	Method: "GET",
	Url:    "/plugins",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_PLUGIN_QUERY},
	},
	Handlers: []gin.HandlerFunc{
		func(c *gin.Context) {
			qs := &PluginEntityQs{}
			fireback.HttpQueryEntity(c, PluginActions.Query, qs)
		},
	},
	Format:         "QUERY",
	Action:         PluginActions.Query,
	ResponseEntity: &[]PluginEntity{},
	Out: &fireback.Module3ActionBody{
		Entity: "PluginEntity",
	},
	CliAction: func(c *cli.Context, security *fireback.SecurityModel) error {
		qs := &PluginEntityQs{}
		fireback.CommonCliQueryCmd3(
			c,
			PluginActions.Query,
			security,
			qs,
		)
		return nil
	},
	CliName:       "query",
	Name:          "query",
	ActionAliases: []string{"q"},
	Flags:         append(fireback.CommonQueryFlags, PluginQsFlags...),
	Description:   "Queries all of the entities in database based on the standard query format (s+)",
}
var PLUGIN_ACTION_EXPORT = fireback.Module3Action{
	Method: "GET",
	Url:    "/plugins/export",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_PLUGIN_QUERY},
	},
	Handlers: []gin.HandlerFunc{
		func(c *gin.Context) {
			fireback.HttpStreamFileChannel(c, PluginActionExport)
		},
	},
	Format:         "QUERY",
	Action:         PluginActionExport,
	ResponseEntity: &[]PluginEntity{},
	Out: &fireback.Module3ActionBody{
		Entity: "PluginEntity",
	},
}
var PLUGIN_ACTION_GET_ONE = fireback.Module3Action{
	Method: "GET",
	Url:    "/plugin/:uniqueId",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_PLUGIN_QUERY},
	},
	Handlers: []gin.HandlerFunc{
		func(c *gin.Context) {
			fireback.HttpGetEntity(c, PluginActions.GetOne)
		},
	},
	Format:         "GET_ONE",
	Action:         PluginActions.GetOne,
	ResponseEntity: &PluginEntity{},
	Out: &fireback.Module3ActionBody{
		Entity: "PluginEntity",
	},
}
var PLUGIN_ACTION_POST_ONE = fireback.Module3Action{
	Name:          "create",
	ActionAliases: []string{"c"},
	Description:   "Create new plugin",
	Flags:         PluginCommonCliFlags,
	Method:        "POST",
	Url:           "/plugin",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_PLUGIN_CREATE},
	},
	Handlers: []gin.HandlerFunc{
		func(c *gin.Context) {
			fireback.HttpPostEntity(c, PluginActions.Create)
		},
	},
	CliAction: func(c *cli.Context, security *fireback.SecurityModel) error {
		result, err := fireback.CliPostEntity(c, PluginActions.Create, security)
		fireback.HandleActionInCli(c, result, err, map[string]map[string]string{})
		if err != nil {
			return err
		}
		return nil
	},
	Action:         PluginActions.Create,
	Format:         "POST_ONE",
	RequestEntity:  &PluginEntity{},
	ResponseEntity: &PluginEntity{},
	Out: &fireback.Module3ActionBody{
		Entity: "PluginEntity",
	},
	In: &fireback.Module3ActionBody{
		Entity: "PluginEntity",
	},
}
var PLUGIN_ACTION_PATCH = fireback.Module3Action{
	Name:          "update",
	ActionAliases: []string{"u"},
	Flags:         PluginCommonCliFlagsOptional,
	Method:        "PATCH",
	Url:           "/plugin",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_PLUGIN_UPDATE},
	},
	Handlers: []gin.HandlerFunc{
		func(c *gin.Context) {
			fireback.HttpUpdateEntity(c, PluginActions.Update)
		},
	},
	Action:         PluginActions.Update,
	RequestEntity:  &PluginEntity{},
	ResponseEntity: &PluginEntity{},
	Format:         "PATCH_ONE",
	Out: &fireback.Module3ActionBody{
		Entity: "PluginEntity",
	},
	In: &fireback.Module3ActionBody{
		Entity: "PluginEntity",
	},
	Description: "Update the Plugin entity by unique id",
	CliName:     "update",
	CliAction: func(c *cli.Context, security *fireback.SecurityModel) error {
		result, err := fireback.CliPatchEntity(c, PluginActions.Update, security)
		fireback.HandleActionInCli(c, result, err, map[string]map[string]string{})
		if err != nil {
			return err
		}
		return nil
	},
}
var PLUGIN_ACTION_PATCH_BULK = fireback.Module3Action{
	Method: "PATCH",
	Url:    "/plugins",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_PLUGIN_UPDATE},
	},
	Handlers: []gin.HandlerFunc{
		func(c *gin.Context) {
			fireback.HttpUpdateEntities(c, PluginActionBulkUpdate)
		},
	},
	Action:         PluginActionBulkUpdate,
	Format:         "PATCH_BULK",
	RequestEntity:  &fireback.BulkRecordRequest[PluginEntity]{},
	ResponseEntity: &fireback.BulkRecordRequest[PluginEntity]{},
	Out: &fireback.Module3ActionBody{
		Entity: "PluginEntity",
	},
	In: &fireback.Module3ActionBody{
		Entity: "PluginEntity",
	},
}
var PLUGIN_ACTION_DELETE = fireback.Module3Action{
	Method: "DELETE",
	Url:    "/plugin",
	Format: "DELETE_DSL",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_PLUGIN_DELETE},
	},
	Handlers: []gin.HandlerFunc{
		func(c *gin.Context) {
			fireback.HttpRemoveEntity(c, PluginActions.Remove)
		},
	},
	Action:         PluginActions.Remove,
	RequestEntity:  &fireback.DeleteRequest{},
	ResponseEntity: &fireback.DeleteResponse{},
	TargetEntity:   &PluginEntity{},
}

/**
 *	Override this function on PluginEntityHttp.go,
 *	In order to add your own http
 **/
var AppendPluginRouter = func(r *[]fireback.Module3Action) {}

func GetPluginModule3Actions() []fireback.Module3Action {
	routes := []fireback.Module3Action{
		PLUGIN_ACTION_QUERY,
		PLUGIN_ACTION_EXPORT,
		PLUGIN_ACTION_GET_ONE,
		PLUGIN_ACTION_POST_ONE,
		PLUGIN_ACTION_PATCH,
		PLUGIN_ACTION_PATCH_BULK,
		PLUGIN_ACTION_DELETE,
	}
	// Append user defined functions
	AppendPluginRouter(&routes)
	return routes
}

var PERM_ROOT_PLUGIN = fireback.PermissionInfo{
	CompleteKey: "root.modules.plugin.plugin.*",
	Name:        "Entire plugin actions (*)",
	Description: "",
}
var PERM_ROOT_PLUGIN_DELETE = fireback.PermissionInfo{
	CompleteKey: "root.modules.plugin.plugin.delete",
	Name:        "Delete plugin",
	Description: "",
}
var PERM_ROOT_PLUGIN_CREATE = fireback.PermissionInfo{
	CompleteKey: "root.modules.plugin.plugin.create",
	Name:        "Create plugin",
	Description: "",
}
var PERM_ROOT_PLUGIN_UPDATE = fireback.PermissionInfo{
	CompleteKey: "root.modules.plugin.plugin.update",
	Name:        "Update plugin",
	Description: "",
}
var PERM_ROOT_PLUGIN_QUERY = fireback.PermissionInfo{
	CompleteKey: "root.modules.plugin.plugin.query",
	Name:        "Query plugin",
	Description: "",
}
var ALL_PLUGIN_PERMISSIONS = []fireback.PermissionInfo{
	PERM_ROOT_PLUGIN_DELETE,
	PERM_ROOT_PLUGIN_CREATE,
	PERM_ROOT_PLUGIN_UPDATE,
	PERM_ROOT_PLUGIN_QUERY,
	PERM_ROOT_PLUGIN,
}

func NewPluginCreatedEvent(
	payload *PluginEntity,
	query *fireback.QueryDSL,
) (*fireback.Event, error) {
	event := &fireback.Event{
		Name:    "PluginCreated",
		Payload: payload,
		Security: &fireback.SecurityModel{
			ActionRequires: []fireback.PermissionInfo{
				PERM_ROOT_PLUGIN_QUERY,
			},
		},
		CacheKey: "*plugin.PluginEntity",
	}
	// Apply the source of the event based on querydsl
	fireback.ApplyQueryDslContextToEvent(event, *query)
	return event, nil
}
func NewPluginUpdatedEvent(
	payload *PluginEntity,
	query *fireback.QueryDSL,
) (*fireback.Event, error) {
	event := &fireback.Event{
		Name:    "PluginUpdated",
		Payload: payload,
		Security: &fireback.SecurityModel{
			ActionRequires: []fireback.PermissionInfo{
				PERM_ROOT_PLUGIN_QUERY,
			},
		},
		CacheKey: "*plugin.PluginEntity",
	}
	// Apply the source of the event based on querydsl
	fireback.ApplyQueryDslContextToEvent(event, *query)
	return event, nil
}

var PluginEntityBundle = fireback.EntityBundle{
	Permissions: ALL_PLUGIN_PERMISSIONS,
	// Cli command has been exluded, since we use module to wrap all the entities
	// to be more easier to wrap up.
	// Create your own bundle if you need with Cli
	//CliCommands: []cli.Command{
	//	PluginCliFn(),
	//},
	Actions:      GetPluginModule3Actions(),
	MockProvider: PluginImportMocks,
	AutoMigrationEntities: []interface{}{
		&PluginEntity{},
	},
	MigrationScripts: []fireback.MigrationScript{},
}
