package plugin

/*
*	Generated by fireback 1.2.4
*	Written by Ali Torabi.
*	Checkout the repository for licenses and contribution: https://github.com/torabian/fireback
 */
import (
	"github.com/torabian/fireback/modules/fireback"
	"github.com/urfave/cli"
)
import (
	"reflect"
)

// using shared actions here
func PluginCustomActions() []fireback.Module3Action {
	routes := []fireback.Module3Action{}
	return routes
}

var PluginCustomActionsCli = []cli.Command{}

// Only to include some headers
func PluginJsonInclude() {
	str4 := reflect.ValueOf(nil)
	_ = str4
}

// Use the actions bundle for ease and provide it to the ModuleProvider
// and it would gather all actions in the module level
var PluginCliActionsBundle = &fireback.CliActionsBundle{
	Name:  "plugin",
	Usage: ``,
	// Here we will include entities actions, as well as module level actions
	Subcommands: cli.Commands{
		PluginCliFn(),
	},
}

func GetPluginActionsBundle() *fireback.ModuleActionsBundle {
	return &fireback.ModuleActionsBundle{
		Actions:   PluginCustomActions(),
		CliAction: PluginCliActionsBundle,
	}
}
func GetPluginActionsCli() []cli.Command {
	return PluginCustomActionsCli
}
