package product

/*
*	Generated by fireback 1.2.4
*	Written by Ali Torabi.
*	Checkout the repository for licenses and contribution: https://github.com/torabian/fireback
 */
import (
	"encoding/json"
	"fmt"
	"github.com/gin-gonic/gin"
	jsoniter "github.com/json-iterator/go"
	queries "github.com/myorg/mynewmicroservice/modules/product/queries"
	"github.com/schollz/progressbar/v3"
	"github.com/torabian/fireback/modules/fireback"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"log"
	"strings"
	//queries github.com/myorg/mynewmicroservice - modules/product"
	"embed"
	metas "github.com/myorg/mynewmicroservice/modules/product/metas"
	mocks "github.com/myorg/mynewmicroservice/modules/product/mocks/Category"
	seeders "github.com/myorg/mynewmicroservice/modules/product/seeders/Category"
	"github.com/urfave/cli"
	"gopkg.in/yaml.v2"
	reflect "reflect"
	"time"
)

var categorySeedersFs = &seeders.ViewsFs

func ResetCategorySeeders(fs *embed.FS) {
	categorySeedersFs = fs
}

type CategoryParameters struct {
	// Defines the visibility of the record in the table.
	// Visibility is a detailed topic, you can check all of the visibility values in fireback/visibility.go
	// by default, visibility of record are 0, means they are protected by the workspace
	// which are being created, and visible to every member of the workspace
	Visibility fireback.String `json:"visibility,omitempty" yaml:"visibility,omitempty" xml:"visibility,omitempty"`
	// The unique-id of the workspace which content belongs to. Upon creation this will be designated
	// to the selected workspace by user, if they have write access. You can change this value
	// or prevent changes to it manually (on root features for example modifying other workspace)
	WorkspaceId fireback.String `json:"workspaceId,omitempty" xml:"workspaceId,omitempty" yaml:"workspaceId,omitempty"`
	// The unique-id of the parent table, which this record is being linked to.
	// used internally for making relations in fireback, generally does not need manual changes
	// or modification by the developer or user. For example, if you have a object inside an object
	// the unique-id of the parent will be written in the child.
	LinkerId fireback.String `json:"linkerId,omitempty" xml:"linkerId,omitempty" yaml:"linkerId,omitempty"`
	// Used for recursive or parent-child operations. Some tables, are having nested relations,
	// and this field makes the table self refrenceing. ParentId needs to exist in the table before
	// creating of modifying a record.
	ParentId fireback.String `json:"parentId,omitempty" xml:"parentId,omitempty" yaml:"parentId,omitempty"`
	// Makes a field deletable. Some records should not be deletable at all.
	// default it's true.
	IsDeletable *bool `json:"isDeletable,omitempty" xml:"isDeletable,omitempty" yaml:"isDeletable,omitempty" gorm:"default:true"`
	// Makes a field updatable. Some records should not be updatable at all.
	// default it's true.
	IsUpdatable *bool `json:"isUpdatable,omitempty" xml:"isUpdatable,omitempty" yaml:"isUpdatable,omitempty" gorm:"default:true"`
	// The unique-id of the user which is creating the record, or the record belongs to.
	// Administration might want to change this to any user, by default Fireback fills
	// it to the current authenticated user.
	UserId fireback.String `json:"userId,omitempty" xml:"userId,omitempty" yaml:"userId,omitempty"`
	// General mechanism to rank the elements. From code perspective, it's just a number,
	// but you can sort it based on any logic for records to make a ranking, sorting.
	// they should not be unique across a table.
	Rank fireback.Int64 `json:"rank,omitempty" yaml:"rank,omitempty" xml:"rank,omitempty" gorm:"type:int;name:rank"`
	// Primary numeric key in the database. This value is not meant to be exported to public
	// or be used to access data at all. Rather a mechanism of indexing columns internally
	// or cursor pagination in future releases of fireback, or better search performance.
	ID uint `gorm:"primaryKey;autoIncrement" json:"-" yaml:"-" xml:"-"`
	// Unique id of the record across the table. This value will be accessed from public APIs,
	// and many other places intead of numeric ID property.
	// Upon generation, a UUID automatically is being assigned, and if user has specified the
	// Unique id in the post body, it will be used. This mechanism allows to manage unsaved
	// content on front-end much easier than requiring parent to exists first.
	UniqueId string `json:"uniqueId,omitempty" xml:"uniqueId,omitempty" gorm:"unique;not null;size:100;" yaml:"uniqueId,omitempty"`
	// The time that the record has been updated in datetime.
	// the field will be automatically populated by gorm orm.
	UpdatedAt *time.Time `json:"updatedAt,omitempty" xml:"updatedAt,omitempty" yaml:"updatedAt,omitempty"`
	// The time that the record has been created in datetime.
	// the field will be automatically populated by gorm orm.
	CreatedAt *time.Time `json:"createdAt,omitempty" xml:"createdAt,omitempty" yaml:"createdAt,omitempty"`
	// The time that the record has been deleted softly (means the data still exists in database, but no longer visible to any feature) in nano datatime
	// you need to make sure check this field if writing custom sql queries.
	// the field will be automatically populated by gorm orm.
	DeletedAt *time.Time `json:"deletedAt,omitempty" xml:"deletedAt,omitempty" yaml:"deletedAt,omitempty"`
	// Record creation date time formatting based on locale of the headers, or other
	// possible factors.
	CreatedFormatted string `json:"createdFormatted,omitempty" xml:"createdFormatted,omitempty" yaml:"createdFormatted,omitempty" sql:"-" gorm:"-"`
	// Record update date time formatting based on locale of the headers, or other
	// possible factors.
	UpdatedFormatted string `json:"updatedFormatted,omitempty" xml:"updatedFormatted,omitempty" yaml:"updatedFormatted,omitempty" sql:"-" gorm:"-"`
	// The original parameter which will be required
	Parameter   *ParameterEntity `json:"parameter" xml:"parameter" yaml:"parameter"    gorm:"foreignKey:ParameterId;references:UniqueId"      `
	ParameterId fireback.String  `json:"parameterId" yaml:"parameterId" xml:"parameterId"   validate:"required" `
	// If the parameter is required to create a product
	IsRequired fireback.Bool   `json:"isRequired" xml:"isRequired" yaml:"isRequired"        `
	LinkedTo   *CategoryEntity `yaml:"-" gorm:"-" json:"-" sql:"-" xml:"-"`
}

func (x *CategoryParameters) RootObjectName() string {
	return "CategoryEntity"
}

type CategoryEntityQs struct {
	Name       fireback.QueriableField `cli:"name" table:"category" typeof:"string" column:"name" qs:"name"`
	Parameters fireback.QueriableField `cli:"parameters" table:"category" typeof:"array" column:"parameters" qs:"parameters"`
	Attributes fireback.QueriableField `cli:"attributes" table:"category" typeof:"" column:"attributes" qs:"attributes"`
}

func (x *CategoryEntityQs) GetQuery() string {
	return fireback.GenerateQueryStringStyle(reflect.ValueOf(x), "")
}

var CategoryQsFlags = []cli.Flag{
	&cli.StringFlag{
		Name:  "name",
		Usage: "Name of the category",
	},
	&cli.StringFlag{
		Name:  "parameters",
		Usage: "The parameters this category has (itself), and this value will be used when creating a new product for the category.",
	},
	&cli.StringFlag{
		Name:  "attributes",
		Usage: "Custom attributes for the product which will be created in the category.",
	},
}

type CategoryEntity struct {
	// Defines the visibility of the record in the table.
	// Visibility is a detailed topic, you can check all of the visibility values in fireback/visibility.go
	// by default, visibility of record are 0, means they are protected by the workspace
	// which are being created, and visible to every member of the workspace
	Visibility fireback.String `json:"visibility,omitempty" yaml:"visibility,omitempty" xml:"visibility,omitempty"`
	// The unique-id of the workspace which content belongs to. Upon creation this will be designated
	// to the selected workspace by user, if they have write access. You can change this value
	// or prevent changes to it manually (on root features for example modifying other workspace)
	WorkspaceId fireback.String `json:"workspaceId,omitempty" xml:"workspaceId,omitempty" yaml:"workspaceId,omitempty"`
	// The unique-id of the parent table, which this record is being linked to.
	// used internally for making relations in fireback, generally does not need manual changes
	// or modification by the developer or user. For example, if you have a object inside an object
	// the unique-id of the parent will be written in the child.
	LinkerId fireback.String `json:"linkerId,omitempty" xml:"linkerId,omitempty" yaml:"linkerId,omitempty"`
	// Used for recursive or parent-child operations. Some tables, are having nested relations,
	// and this field makes the table self refrenceing. ParentId needs to exist in the table before
	// creating of modifying a record.
	ParentId fireback.String `json:"parentId,omitempty" xml:"parentId,omitempty" yaml:"parentId,omitempty"`
	// Makes a field deletable. Some records should not be deletable at all.
	// default it's true.
	IsDeletable *bool `json:"isDeletable,omitempty" xml:"isDeletable,omitempty" yaml:"isDeletable,omitempty" gorm:"default:true"`
	// Makes a field updatable. Some records should not be updatable at all.
	// default it's true.
	IsUpdatable *bool `json:"isUpdatable,omitempty" xml:"isUpdatable,omitempty" yaml:"isUpdatable,omitempty" gorm:"default:true"`
	// The unique-id of the user which is creating the record, or the record belongs to.
	// Administration might want to change this to any user, by default Fireback fills
	// it to the current authenticated user.
	UserId fireback.String `json:"userId,omitempty" xml:"userId,omitempty" yaml:"userId,omitempty"`
	// General mechanism to rank the elements. From code perspective, it's just a number,
	// but you can sort it based on any logic for records to make a ranking, sorting.
	// they should not be unique across a table.
	Rank fireback.Int64 `json:"rank,omitempty" yaml:"rank,omitempty" xml:"rank,omitempty" gorm:"type:int;name:rank"`
	// Primary numeric key in the database. This value is not meant to be exported to public
	// or be used to access data at all. Rather a mechanism of indexing columns internally
	// or cursor pagination in future releases of fireback, or better search performance.
	ID uint `gorm:"primaryKey;autoIncrement" json:"-" yaml:"-" xml:"-"`
	// Unique id of the record across the table. This value will be accessed from public APIs,
	// and many other places intead of numeric ID property.
	// Upon generation, a UUID automatically is being assigned, and if user has specified the
	// Unique id in the post body, it will be used. This mechanism allows to manage unsaved
	// content on front-end much easier than requiring parent to exists first.
	UniqueId string `json:"uniqueId,omitempty" xml:"uniqueId,omitempty" gorm:"unique;not null;size:100;" yaml:"uniqueId,omitempty"`
	// The time that the record has been updated in datetime.
	// the field will be automatically populated by gorm orm.
	UpdatedAt *time.Time `json:"updatedAt,omitempty" xml:"updatedAt,omitempty" yaml:"updatedAt,omitempty"`
	// The time that the record has been created in datetime.
	// the field will be automatically populated by gorm orm.
	CreatedAt *time.Time `json:"createdAt,omitempty" xml:"createdAt,omitempty" yaml:"createdAt,omitempty"`
	// The time that the record has been deleted softly (means the data still exists in database, but no longer visible to any feature) in nano datatime
	// you need to make sure check this field if writing custom sql queries.
	// the field will be automatically populated by gorm orm.
	DeletedAt *time.Time `json:"deletedAt,omitempty" xml:"deletedAt,omitempty" yaml:"deletedAt,omitempty"`
	// Record creation date time formatting based on locale of the headers, or other
	// possible factors.
	CreatedFormatted string `json:"createdFormatted,omitempty" xml:"createdFormatted,omitempty" yaml:"createdFormatted,omitempty" sql:"-" gorm:"-"`
	// Record update date time formatting based on locale of the headers, or other
	// possible factors.
	UpdatedFormatted string `json:"updatedFormatted,omitempty" xml:"updatedFormatted,omitempty" yaml:"updatedFormatted,omitempty" sql:"-" gorm:"-"`
	// Name of the category
	Name string `json:"name" xml:"name" yaml:"name"  validate:"required"        translate:"true"  `
	// The parameters this category has (itself), and this value will be used when creating a new product for the category.
	Parameters []*CategoryParameters `json:"parameters" xml:"parameters" yaml:"parameters"    gorm:"foreignKey:LinkerId;references:UniqueId;constraint:OnDelete:CASCADE"      `
	// Custom attributes for the product which will be created in the category.
	Attributes   *string                   `json:"attributes" xml:"attributes" yaml:"attributes"        `
	Translations []*CategoryEntityPolyglot `json:"translations,omitempty" xml:"translations,omitempty" yaml:"translations,omitempty" gorm:"foreignKey:LinkerId;references:UniqueId;constraint:OnDelete:CASCADE"`
	Children     []*CategoryEntity         `csv:"-" gorm:"-" sql:"-" json:"children,omitempty" xml:"children,omitempty"  yaml:"children,omitempty"`
	LinkedTo     *CategoryEntity           `csv:"-" yaml:"-" gorm:"-" json:"-" sql:"-" xml:"-"`
}

func CategoryEntityStream(q fireback.QueryDSL) (chan []*CategoryEntity, *fireback.QueryResultMeta, *fireback.IError) {
	cn := make(chan []*CategoryEntity)
	q.ItemsPerPage = 50
	q.StartIndex = 0
	_, qrm, err := CategoryActions.Query(q)
	if err != nil {
		return nil, nil, err
	}
	go func() {
		defer close(cn)
		for i := 0; i <= int(qrm.TotalAvailableItems)-1; i++ {
			items, _, _ := CategoryActions.Query(q)
			i += q.ItemsPerPage
			q.StartIndex = i
			cn <- items
		}
	}()
	return cn, qrm, nil
}

type CategoryEntityList struct {
	Items []*CategoryEntity
}

func NewCategoryEntityList(items []*CategoryEntity) *CategoryEntityList {
	return &CategoryEntityList{
		Items: items,
	}
}
func (x *CategoryEntityList) Json() string {
	if x != nil {
		str, _ := json.MarshalIndent(x, "", "  ")
		return (string(str))
	}
	return ""
}
func (x *CategoryEntityList) ToTree() *fireback.TreeOperation[CategoryEntity] {
	return fireback.NewTreeOperation(
		x.Items,
		func(t *CategoryEntity) string {
			if !t.ParentId.Valid {
				return ""
			}
			return t.ParentId.String
		},
		func(t *CategoryEntity) string {
			return t.UniqueId
		},
	)
}

var CategoryPreloadRelations []string = []string{}

type categoryActionsSig struct {
	Update         func(query fireback.QueryDSL, dto *CategoryEntity) (*CategoryEntity, *fireback.IError)
	Create         func(dto *CategoryEntity, query fireback.QueryDSL) (*CategoryEntity, *fireback.IError)
	Upsert         func(dto *CategoryEntity, query fireback.QueryDSL) (*CategoryEntity, *fireback.IError)
	SeederInit     func() *CategoryEntity
	Remove         func(query fireback.QueryDSL) (int64, *fireback.IError)
	MultiInsert    func(dtos []*CategoryEntity, query fireback.QueryDSL) ([]*CategoryEntity, *fireback.IError)
	GetOne         func(query fireback.QueryDSL) (*CategoryEntity, *fireback.IError)
	GetByWorkspace func(query fireback.QueryDSL) (*CategoryEntity, *fireback.IError)
	Query          func(query fireback.QueryDSL) ([]*CategoryEntity, *fireback.QueryResultMeta, *fireback.IError)
	CteQuery       func(query fireback.QueryDSL) ([]*CategoryEntity, *fireback.QueryResultMeta, *fireback.IError)
}

var CategoryActions categoryActionsSig = categoryActionsSig{
	Update:         CategoryActionUpdateFn,
	Create:         CategoryActionCreateFn,
	Upsert:         CategoryActionUpsertFn,
	Remove:         CategoryActionRemoveFn,
	SeederInit:     CategoryActionSeederInitFn,
	MultiInsert:    CategoryMultiInsertFn,
	GetOne:         CategoryActionGetOneFn,
	GetByWorkspace: CategoryActionGetByWorkspaceFn,
	Query:          CategoryActionQueryFn,
	CteQuery:       CategoryActionCteQueryFn,
}

func CategoryActionUpsertFn(dto *CategoryEntity, query fireback.QueryDSL) (*CategoryEntity, *fireback.IError) {
	return nil, nil
}

var CATEGORY_EVENT_CREATED = "category.created"
var CATEGORY_EVENT_UPDATED = "category.updated"
var CATEGORY_EVENT_DELETED = "category.deleted"
var CATEGORY_EVENTS = []string{
	CATEGORY_EVENT_CREATED,
	CATEGORY_EVENT_UPDATED,
	CATEGORY_EVENT_DELETED,
}

type CategoryFieldMap struct {
	Name       fireback.TranslatedString `yaml:"name"`
	Parameters fireback.TranslatedString `yaml:"parameters"`
	Attributes fireback.TranslatedString `yaml:"attributes"`
}

var CategoryEntityMetaConfig map[string]int64 = map[string]int64{}
var CategoryEntityJsonSchema = fireback.ExtractEntityFields(reflect.ValueOf(&CategoryEntity{}))

type CategoryEntityPolyglot struct {
	LinkerId   string `gorm:"uniqueId;not null;size:100;" json:"linkerId,omitempty" yaml:"linkerId,omitempty" xml:"linkerId,omitempty"`
	LanguageId string `gorm:"uniqueId;not null;size:100;" json:"languageId,omitempty" xml:"languageId,omitempty" yaml:"languageId,omitempty"`
	Name       string `yaml:"name,omitempty" xml:"name,omitempty" json:"name,omitempty"`
}

func CategoryParametersActionCreate(
	dto *CategoryParameters,
	query fireback.QueryDSL,
) (*CategoryParameters, *fireback.IError) {
	dto.LinkerId = fireback.NewString(query.LinkerId)
	var dbref *gorm.DB = nil
	if query.Tx == nil {
		dbref = fireback.GetDbRef()
	} else {
		dbref = query.Tx
	}
	query.Tx = dbref
	if dto.UniqueId == "" {
		dto.UniqueId = fireback.UUID()
	}
	err := dbref.Create(&dto).Error
	if err != nil {
		err := fireback.GormErrorToIError(err)
		return nil, err
	}
	return dto, nil
}
func CategoryParametersActionUpdate(
	query fireback.QueryDSL,
	dto *CategoryParameters,
) (*CategoryParameters, *fireback.IError) {
	dto.LinkerId = fireback.NewString(query.LinkerId)
	var dbref *gorm.DB = nil
	if query.Tx == nil {
		dbref = fireback.GetDbRef()
	} else {
		dbref = query.Tx
	}
	query.Tx = dbref
	cond2 := &CategoryParameters{LinkerId: fireback.NewString(query.LinkerId), UniqueId: query.UniqueId}
	q := query.Tx.Where(cond2)
	err := q.UpdateColumns(&dto).Error
	if err != nil {
		err := fireback.GormErrorToIError(err)
		return nil, err
	}
	return dto, nil
}
func CategoryParametersActionGetOne(
	query fireback.QueryDSL,
) (*CategoryParameters, *fireback.IError) {
	refl := reflect.ValueOf(&CategoryParameters{})
	item, err := fireback.GetOneEntity[CategoryParameters](query, refl)
	return item, err
}
func entityCategoryFormatter(dto *CategoryEntity, query fireback.QueryDSL) {
	if dto == nil {
		return
	}
}
func CategoryActionSeederMultiple(query fireback.QueryDSL, count int) {
	successInsert := 0
	failureInsert := 0
	batchSize := 100
	bar := progressbar.Default(int64(count))
	// Collect entities in batches
	var entitiesBatch []*CategoryEntity
	for i := 1; i <= count; i++ {
		entity := CategoryActions.SeederInit()
		entitiesBatch = append(entitiesBatch, entity)
		// When batch size is reached, perform the batch insert
		if len(entitiesBatch) == batchSize || i == count {
			// Insert batch
			_, err := CategoryActions.MultiInsert(entitiesBatch, query)
			if err == nil {
				successInsert += len(entitiesBatch)
			} else {
				fmt.Println(err)
				failureInsert += len(entitiesBatch)
			}
			// Clear the batch after insert
			entitiesBatch = nil
		}
		bar.Add(1)
	}
	fmt.Println("Success", successInsert, "Failure", failureInsert)
}
func CategoryActionSeeder(query fireback.QueryDSL, count int) {
	successInsert := 0
	failureInsert := 0
	bar := progressbar.Default(int64(count))
	for i := 1; i <= count; i++ {
		entity := CategoryActions.SeederInit()
		_, err := CategoryActions.Create(entity, query)
		if err == nil {
			successInsert++
		} else {
			fmt.Println(err)
			failureInsert++
		}
		bar.Add(1)
	}
	fmt.Println("Success", successInsert, "Failure", failureInsert)
}
func (x *CategoryEntity) GetNameTranslated(language string) string {
	if x.Translations != nil && len(x.Translations) > 0 {
		for _, item := range x.Translations {
			if item.LanguageId == language {
				return item.Name
			}
		}
	}
	return ""
}
func (x *CategoryEntity) Seeder() string {
	obj := CategoryActions.SeederInit()
	v, _ := json.MarshalIndent(obj, "", "  ")
	return string(v)
}
func CategoryActionSeederInitFn() *CategoryEntity {
	entity := &CategoryEntity{
		Parameters: []*CategoryParameters{{}},
	}
	return entity
}
func CategoryAssociationCreate(dto *CategoryEntity, query fireback.QueryDSL) error {
	return nil
}

/**
* These kind of content are coming from another entity, which is indepndent module
* If we want to create them, we need to do it before. This is not association.
**/
func CategoryRelationContentCreate(dto *CategoryEntity, query fireback.QueryDSL) error {
	return nil
}
func CategoryRelationContentUpdate(dto *CategoryEntity, query fireback.QueryDSL) error {
	return nil
}
func CategoryPolyglotUpdateHandler(dto *CategoryEntity, query fireback.QueryDSL) {
	if dto == nil {
		return
	}
	fireback.PolyglotUpdateHandler(dto, &CategoryEntityPolyglot{}, query)
}

/**
 * This will be validating your entity fully. Important note is that, you add validate:* tag
 * in your entity, it will automatically work here. For slices inside entity, make sure you add
 * extra line of AppendSliceErrors, otherwise they won't be detected
 */
func CategoryValidator(dto *CategoryEntity, isPatch bool) *fireback.IError {
	err := fireback.CommonStructValidatorPointer(dto, isPatch)
	if dto != nil && dto.Parameters != nil {
		fireback.AppendSliceErrors(dto.Parameters, isPatch, "parameters", err)
	}
	return err
}

// Creates a set of natural language queries, which can be used with
// AI tools to create content or help with some tasks
var CategoryAskCmd cli.Command = cli.Command{
	Name:  "nlp",
	Usage: "Set of natural language queries which helps creating content or data",
	Subcommands: []cli.Command{
		{
			Name:  "sample",
			Usage: "Asks for generating sample by giving an example data",
			Flags: []cli.Flag{
				&cli.StringFlag{
					Name:  "format",
					Usage: "Format of the export or import file. Can be 'yaml', 'yml', 'json'",
					Value: "yaml",
				},
				&cli.IntFlag{
					Name:  "count",
					Usage: "How many samples to ask",
					Value: 30,
				},
			},
			Action: func(c *cli.Context) error {
				v := &CategoryEntity{}
				format := c.String("format")
				request := "\033[1m" + `
I need you to create me an array of exact signature as the example given below,
with at least ` + fmt.Sprint(c.String("count")) + ` items, mock the content with few words, and guess the possible values
based on the common sense. I need the output to be a valid ` + format + ` file.
Make sure you wrap the entire array in 'items' field. Also before that, I provide some explanation of each field:
Name: (type: string) Description: Name of the category
Parameters: (type: array) Description: The parameters this category has (itself), and this value will be used when creating a new product for the category.
Attributes: (type: ) Description: Custom attributes for the product which will be created in the category.
And here is the actual object signature:
` + v.Seeder() + `
`
				fmt.Println(request)
				return nil
			},
		},
	},
}

func CategoryEntityPreSanitize(dto *CategoryEntity, query fireback.QueryDSL) {
}
func CategoryEntityBeforeCreateAppend(dto *CategoryEntity, query fireback.QueryDSL) {
	if dto.UniqueId == "" {
		dto.UniqueId = fireback.UUID()
	}
	dto.WorkspaceId = fireback.NewString(query.WorkspaceId)
	dto.UserId = fireback.NewString(query.UserId)
	CategoryRecursiveAddUniqueId(dto, query)
}
func CategoryRecursiveAddUniqueId(dto *CategoryEntity, query fireback.QueryDSL) {
	if dto.Parameters != nil && len(dto.Parameters) > 0 {
		for index0 := range dto.Parameters {
			if dto.Parameters[index0].UniqueId == "" {
				dto.Parameters[index0].UniqueId = fireback.UUID()
			}
		}
	}
}

/*
*
	Batch inserts, do not have all features that create
	operation does. Use it with unnormalized content,
	or read the source code carefully.
  This is not marked as an action, because it should not be available publicly
  at this moment.
*
*/
func CategoryMultiInsertFn(dtos []*CategoryEntity, query fireback.QueryDSL) ([]*CategoryEntity, *fireback.IError) {
	if len(dtos) > 0 {
		for index := range dtos {
			CategoryEntityPreSanitize(dtos[index], query)
			CategoryEntityBeforeCreateAppend(dtos[index], query)
		}
		var dbref *gorm.DB = nil
		if query.Tx == nil {
			dbref = fireback.GetDbRef()
		} else {
			dbref = query.Tx
		}
		query.Tx = dbref
		err := dbref.Create(&dtos).Error
		if err != nil {
			return nil, fireback.GormErrorToIError(err)
		}
	}
	return dtos, nil
}
func CategoryActionBatchCreateFn(dtos []*CategoryEntity, query fireback.QueryDSL) ([]*CategoryEntity, *fireback.IError) {
	if dtos != nil && len(dtos) > 0 {
		items := []*CategoryEntity{}
		for _, item := range dtos {
			s, err := CategoryActions.Create(item, query)
			if err != nil {
				return nil, err
			}
			items = append(items, s)
		}
		return items, nil
	}
	return dtos, nil
}
func CategoryDeleteEntireChildren(query fireback.QueryDSL, dto *CategoryEntity) *fireback.IError {
	// intentionally removed this. It's hard to implement it, and probably wrong without
	// proper on delete cascade
	return nil
}
func CategoryActionCreateFn(dto *CategoryEntity, query fireback.QueryDSL) (*CategoryEntity, *fireback.IError) {
	// 1. Validate always
	if iError := CategoryValidator(dto, false); iError != nil {
		return nil, iError
	}
	// 1.5 Sanitize the content coming of the front-end
	CategoryEntityPreSanitize(dto, query)
	// 2. Append the necessary information about user, workspace
	CategoryEntityBeforeCreateAppend(dto, query)
	// 3. Create other entities if we want select from them
	CategoryRelationContentCreate(dto, query)
	// 4. Create the entity
	var dbref *gorm.DB = nil
	if query.Tx == nil {
		dbref = fireback.GetDbRef()
	} else {
		dbref = query.Tx
	}
	query.Tx = dbref
	err := dbref.Create(&dto).Error
	if err != nil {
		err := fireback.GormErrorToIError(err)
		return nil, err
	}
	// 5. Create sub entities, objects or arrays, association to other entities
	CategoryAssociationCreate(dto, query)
	// 6. Fire the event into system
	actionEvent, eventErr := NewCategoryCreatedEvent(dto, &query)
	if actionEvent != nil && eventErr == nil {
		fireback.GetEventBusInstance().FireEvent(query, *actionEvent)
	} else {
		log.Default().Panicln("Creating event has failed for %v", dto)
	}
	/*
		event.MustFire(CATEGORY_EVENT_CREATED, event.M{
			"entity":   dto,
			"entityKey": fireback.GetTypeString(&CategoryEntity{}),
			"target":   "workspace",
			"unqiueId": query.WorkspaceId,
		})
	*/
	return dto, nil
}
func CategoryActionGetOneFn(query fireback.QueryDSL) (*CategoryEntity, *fireback.IError) {
	refl := reflect.ValueOf(&CategoryEntity{})
	item, err := fireback.GetOneEntity[CategoryEntity](query, refl)
	entityCategoryFormatter(item, query)
	return item, err
}
func CategoryActionGetByWorkspaceFn(query fireback.QueryDSL) (*CategoryEntity, *fireback.IError) {
	refl := reflect.ValueOf(&CategoryEntity{})
	item, err := fireback.GetOneByWorkspaceEntity[CategoryEntity](query, refl)
	entityCategoryFormatter(item, query)
	return item, err
}
func CategoryActionQueryFn(query fireback.QueryDSL) ([]*CategoryEntity, *fireback.QueryResultMeta, *fireback.IError) {
	refl := reflect.ValueOf(&CategoryEntity{})
	items, meta, err := fireback.QueryEntitiesPointer[CategoryEntity](query, refl)
	for _, item := range items {
		entityCategoryFormatter(item, query)
	}
	return items, meta, err
}

var categoryMemoryItems []*CategoryEntity = []*CategoryEntity{}

func CategoryEntityIntoMemory() {
	q := fireback.QueryDSL{
		ItemsPerPage: 500,
		StartIndex:   0,
	}
	_, qrm, _ := CategoryActions.Query(q)
	for i := 0; i <= int(qrm.TotalAvailableItems)-1; i++ {
		items, _, _ := CategoryActions.Query(q)
		categoryMemoryItems = append(categoryMemoryItems, items...)
		i += q.ItemsPerPage
		q.StartIndex = i
	}
}
func CategoryMemGet(id uint) *CategoryEntity {
	for _, item := range categoryMemoryItems {
		if item.ID == id {
			return item
		}
	}
	return nil
}
func CategoryMemJoin(items []uint) []*CategoryEntity {
	res := []*CategoryEntity{}
	for _, item := range items {
		v := CategoryMemGet(item)
		if v != nil {
			res = append(res, v)
		}
	}
	return res
}
func (dto *CategoryEntity) Size() int {
	var size int = len(dto.Children)
	for _, c := range dto.Children {
		size += c.Size()
	}
	return size
}
func (dto *CategoryEntity) Add(nodes ...*CategoryEntity) bool {
	var size = dto.Size()
	for _, n := range nodes {
		if n.ParentId.Valid && n.ParentId.String == dto.UniqueId {
			dto.Children = append(dto.Children, n)
		} else {
			for _, c := range dto.Children {
				if c.Add(n) {
					break
				}
			}
		}
	}
	return dto.Size() == size+len(nodes)
}
func CategoryActionCommonPivotQuery(query fireback.QueryDSL) ([]*fireback.PivotResult, *fireback.QueryResultMeta, *fireback.IError) {
	items, meta, err := fireback.UnsafeQuerySqlFromFs[fireback.PivotResult](
		&queries.QueriesFs, "CategoryCommonPivot.sqlite.dyno", query,
	)
	return items, meta, err
}
func CategoryActionCteQueryFn(query fireback.QueryDSL) ([]*CategoryEntity, *fireback.QueryResultMeta, *fireback.IError) {
	refl := reflect.ValueOf(&CategoryEntity{})
	items, meta, err := fireback.ContextAwareVSqlOperation[CategoryEntity](
		refl, &queries.QueriesFs, "CategoryCte.vsql", query,
	)
	for _, item := range items {
		entityCategoryFormatter(item, query)
	}
	var tree []*CategoryEntity
	for _, item := range items {
		if !item.ParentId.Valid {
			root := item
			root.Add(items...)
			tree = append(tree, root)
		}
	}
	return tree, meta, err
}
func CategoryUpdateExec(dbref *gorm.DB, query fireback.QueryDSL, fields *CategoryEntity) (*CategoryEntity, *fireback.IError) {
	uniqueId := fields.UniqueId
	query.TriggerEventName = CATEGORY_EVENT_UPDATED
	CategoryEntityPreSanitize(fields, query)
	var item CategoryEntity
	var itemRefetched CategoryEntity
	// If the entity is distinct by workspace, then the Query.WorkspaceId
	// which is selected is being used as the condition for create or update
	// if not, the unique Id is being used
	cond2 := &CategoryEntity{UniqueId: uniqueId}
	q := dbref.
		Where(cond2).
		FirstOrCreate(&item)
	err := q.UpdateColumns(fields).Error
	if err != nil {
		return nil, fireback.GormErrorToIError(err)
	}
	query.Tx = dbref
	CategoryRelationContentUpdate(fields, query)
	CategoryPolyglotUpdateHandler(fields, query)
	if ero := CategoryDeleteEntireChildren(query, fields); ero != nil {
		return nil, ero
	}
	// @meta(update has many)
	if fields.Parameters != nil {
		linkerId := uniqueId
		dbref.
			Where(&CategoryParameters{LinkerId: fireback.NewString(linkerId)}).
			Delete(&CategoryParameters{})
		for _, newItem := range fields.Parameters {
			newItem.UniqueId = fireback.UUID()
			newItem.LinkerId = fireback.NewString(linkerId)
			dbref.Create(&newItem)
		}
	}
	err = dbref.
		Preload(clause.Associations).
		Where(&CategoryEntity{UniqueId: uniqueId}).
		First(&itemRefetched).Error
	if err != nil {
		return nil, fireback.GormErrorToIError(err)
	}
	actionEvent, eventErr := NewCategoryUpdatedEvent(fields, &query)
	if actionEvent != nil && eventErr == nil {
		fireback.GetEventBusInstance().FireEvent(query, *actionEvent)
	} else {
		log.Default().Panicln("Updating event has failed for %v", fields)
	}
	/*
	   event.MustFire(query.TriggerEventName, event.M{
	     "entity":   &item,
	     "target":   "workspace",
	     "unqiueId": query.WorkspaceId,
	   })*/
	return &itemRefetched, nil
}
func CategoryActionUpdateFn(query fireback.QueryDSL, fields *CategoryEntity) (*CategoryEntity, *fireback.IError) {
	if fields == nil {
		return nil, fireback.Create401Error(&fireback.FirebackMessages.BodyIsMissing, []string{})
	}
	// 1. Validate always
	if iError := CategoryValidator(fields, true); iError != nil {
		return nil, iError
	}
	// Let's not add this. I am not sure of the consequences
	// CategoryRecursiveAddUniqueId(fields, query)
	var dbref *gorm.DB = nil
	if query.Tx == nil {
		dbref = fireback.GetDbRef()
		var item *CategoryEntity
		vf := dbref.Transaction(func(tx *gorm.DB) error {
			dbref = tx
			var err *fireback.IError
			item, err = CategoryUpdateExec(dbref, query, fields)
			if err == nil {
				return nil
			} else {
				return err
			}
		})
		return item, fireback.CastToIError(vf)
	} else {
		dbref = query.Tx
		return CategoryUpdateExec(dbref, query, fields)
	}
}

var CategoryWipeCmd cli.Command = cli.Command{
	Name:  "wipe",
	Usage: "Wipes entire categories ",
	Action: func(c *cli.Context) error {
		query := fireback.CommonCliQueryDSLBuilderAuthorize(c, &fireback.SecurityModel{
			ActionRequires: []fireback.PermissionInfo{PERM_ROOT_CATEGORY_DELETE},
		})
		count, _ := CategoryActionWipeClean(query)
		fmt.Println("Removed", count, "of entities")
		return nil
	},
}

func CategoryActionRemoveFn(query fireback.QueryDSL) (int64, *fireback.IError) {
	refl := reflect.ValueOf(&CategoryEntity{})
	query.ActionRequires = []fireback.PermissionInfo{PERM_ROOT_CATEGORY_DELETE}
	return fireback.RemoveEntity[CategoryEntity](query, refl)
}
func CategoryActionWipeClean(query fireback.QueryDSL) (int64, error) {
	var err error
	var count int64 = 0
	{
		subCount, subErr := fireback.WipeCleanEntity[CategoryParameters]()
		if subErr != nil {
			fmt.Println("Error while wiping 'CategoryParameters'", subErr)
			return count, subErr
		} else {
			count += subCount
		}
	}
	{
		subCount, subErr := fireback.WipeCleanEntity[CategoryEntity]()
		if subErr != nil {
			fmt.Println("Error while wiping 'CategoryEntity'", subErr)
			return count, subErr
		} else {
			count += subCount
		}
	}
	return count, err
}
func CategoryActionBulkUpdate(
	query fireback.QueryDSL, dto *fireback.BulkRecordRequest[CategoryEntity]) (
	*fireback.BulkRecordRequest[CategoryEntity], *fireback.IError,
) {
	result := []*CategoryEntity{}
	err := fireback.GetDbRef().Transaction(func(tx *gorm.DB) error {
		query.Tx = tx
		for _, record := range dto.Records {
			item, err := CategoryActions.Update(query, record)
			if err != nil {
				return err
			} else {
				result = append(result, item)
			}
		}
		return nil
	})
	if err == nil {
		return dto, nil
	}
	return nil, err.(*fireback.IError)
}
func (x *CategoryEntity) Json() string {
	if x != nil {
		str, _ := json.MarshalIndent(x, "", "  ")
		return (string(str))
	}
	return ""
}

var CategoryEntityMeta = fireback.TableMetaData{
	EntityName:    "Category",
	ExportKey:     "categories",
	TableNameInDb: "category_entities",
	EntityObject:  &CategoryEntity{},
	ExportStream:  CategoryActionExportT,
	ImportQuery:   CategoryActionImport,
}

func CategoryActionExport(
	query fireback.QueryDSL,
) (chan []byte, *fireback.IError) {
	return fireback.YamlExporterChannel[CategoryEntity](query, CategoryActions.Query, CategoryPreloadRelations)
}
func CategoryActionExportT(
	query fireback.QueryDSL,
) (chan []interface{}, *fireback.IError) {
	return fireback.YamlExporterChannelT[CategoryEntity](query, CategoryActions.Query, CategoryPreloadRelations)
}
func CategoryActionImport(
	dto interface{}, query fireback.QueryDSL,
) *fireback.IError {
	var json = jsoniter.ConfigCompatibleWithStandardLibrary
	var content CategoryEntity
	cx, err2 := json.Marshal(dto)
	if err2 != nil {
		return fireback.Create401Error(&fireback.FirebackMessages.InvalidContent, []string{})
	}
	json.Unmarshal(cx, &content)
	_, err := CategoryActions.Create(&content, query)
	return err
}

var CategoryCommonCliFlags = []cli.Flag{
	&cli.StringFlag{
		Name:  "x-accept",
		Usage: "Return type of the the content, such as json or yaml",
	},
	&cli.StringFlag{
		Name:     "wid",
		Required: false,
		Usage:    "Provide workspace id, if you want to change the data workspace",
	},
	&cli.StringFlag{
		Name:     "uid",
		Required: false,
		Usage:    "Unique Id - external unique hash to query entity",
	},
	&cli.StringFlag{
		Name:     "pid",
		Required: false,
		Usage:    " Parent record id of the same type",
	},
	&cli.StringFlag{
		Name:     "name",
		Required: true,
		Usage:    `Name of the category (string)`,
	},
	&cli.StringSliceFlag{
		Name:     "parameters",
		Required: false,
		Usage:    `The parameters this category has (itself), and this value will be used when creating a new product for the category. (array)`,
	},
	&cli.StringFlag{
		Name:     "attributes",
		Required: false,
		Usage:    `Custom attributes for the product which will be created in the category. ()`,
	},
}
var CategoryCommonInteractiveCliFlags = []fireback.CliInteractiveFlag{
	{
		Name:        "name",
		StructField: "Name",
		Required:    true,
		Recommended: false,
		Usage:       `Name of the category`,
		Type:        "string",
	},
}
var CategoryCommonCliFlagsOptional = []cli.Flag{
	&cli.StringFlag{
		Name:     "x-src",
		Required: false,
		Usage:    `Import the body of the request from a file (e.g. json/yaml) on the disk`,
	},
	&cli.StringFlag{
		Name:  "x-accept",
		Usage: "Return type of the the content, such as json or yaml",
	},
	&cli.StringFlag{
		Name:     "wid",
		Required: false,
		Usage:    "Provide workspace id, if you want to change the data workspace",
	},
	&cli.StringFlag{
		Name:     "uid",
		Required: false,
		Usage:    "Unique Id - external unique hash to query entity",
	},
	&cli.StringFlag{
		Name:     "pid",
		Required: false,
		Usage:    " Parent record id of the same type",
	},
	&cli.StringFlag{
		Name:     "name",
		Required: true,
		Usage:    `Name of the category (string)`,
	},
	&cli.StringSliceFlag{
		Name:     "parameters",
		Required: false,
		Usage:    `The parameters this category has (itself), and this value will be used when creating a new product for the category. (array)`,
	},
	&cli.StringFlag{
		Name:     "attributes",
		Required: false,
		Usage:    `Custom attributes for the product which will be created in the category. ()`,
	},
}
var CategoryCreateCmd cli.Command = CATEGORY_ACTION_POST_ONE.ToCli()
var CategoryCreateInteractiveCmd cli.Command = cli.Command{
	Name:  "ic",
	Usage: "Creates a new entity, using requied fields in an interactive name",
	Flags: []cli.Flag{
		&cli.BoolFlag{
			Name:  "all",
			Usage: "Interactively asks for all inputs, not only required ones",
		},
	},
	Action: func(c *cli.Context) {
		query := fireback.CommonCliQueryDSLBuilderAuthorize(c, &fireback.SecurityModel{
			ActionRequires: []fireback.PermissionInfo{PERM_ROOT_CATEGORY_CREATE},
		})
		entity := &CategoryEntity{}
		fireback.PopulateInteractively(entity, c, CategoryCommonInteractiveCliFlags)
		if entity, err := CategoryActions.Create(entity, query); err != nil {
			fmt.Println(err.Error())
		} else {
			f, _ := yaml.Marshal(entity)
			fmt.Println(fireback.FormatYamlKeys(string(f)))
		}
	},
}
var CategoryUpdateCmd cli.Command = cli.Command{
	Name:    "update",
	Aliases: []string{"u"},
	Flags:   CategoryCommonCliFlagsOptional,
	Usage:   "Updates entity by passing the parameters",
	Action: func(c *cli.Context) error {
		query := fireback.CommonCliQueryDSLBuilderAuthorize(c, &fireback.SecurityModel{
			ActionRequires: []fireback.PermissionInfo{PERM_ROOT_CATEGORY_UPDATE},
		})
		entity := CastCategoryFromCli(c)
		if entity, err := CategoryActions.Update(query, entity); err != nil {
			fmt.Println(err.Error())
		} else {
			f, _ := json.MarshalIndent(entity, "", "  ")
			fmt.Println(string(f))
		}
		return nil
	},
}

func (x *CategoryEntity) FromCli(c *cli.Context) *CategoryEntity {
	return CastCategoryFromCli(c)
}
func CastCategoryFromCli(c *cli.Context) *CategoryEntity {
	template := &CategoryEntity{}
	fireback.HandleXsrc(c, template)
	if c.IsSet("uid") {
		template.UniqueId = c.String("uid")
	}
	if c.IsSet("pid") {
		template.ParentId = fireback.NewStringAutoNull(c.String("pid"))
	}
	if c.IsSet("name") {
		template.Name = c.String("name")
	}
	return template
}
func CategorySyncSeederFromFs(fsRef *embed.FS, fileNames []string, q fireback.QueryDSL) {
	fireback.SeederFromFSImport(
		q,
		CategoryActions.Create,
		reflect.ValueOf(&CategoryEntity{}).Elem(),
		fsRef,
		fileNames,
		true,
	)
}
func CategorySyncSeeders() {
	fireback.SeederFromFSImport(
		fireback.QueryDSL{WorkspaceId: fireback.USER_SYSTEM},
		CategoryActions.Create,
		reflect.ValueOf(&CategoryEntity{}).Elem(),
		categorySeedersFs,
		[]string{},
		true,
	)
}
func CategoryImportMocks() {
	fireback.SeederFromFSImport(
		fireback.QueryDSL{},
		CategoryActions.Create,
		reflect.ValueOf(&CategoryEntity{}).Elem(),
		&mocks.ViewsFs,
		[]string{},
		false,
	)
}
func CategoryWriteQueryMock(ctx fireback.MockQueryContext) {
	for _, lang := range ctx.Languages {
		itemsPerPage := 9999
		if ctx.ItemsPerPage > 0 {
			itemsPerPage = ctx.ItemsPerPage
		}
		f := fireback.QueryDSL{ItemsPerPage: itemsPerPage, Language: lang, WithPreloads: ctx.WithPreloads, Deep: true}
		items, count, _ := CategoryActions.Query(f)
		result := fireback.QueryEntitySuccessResult(f, items, count)
		fireback.WriteMockDataToFile(lang, "", "Category", result)
	}
}
func CategoriesActionQueryString(keyword string, page int) ([]string, *fireback.QueryResultMeta, *fireback.IError) {
	searchFields := []string{
		`unique_id %"{keyword}"%`,
		`name %"{keyword}"%`,
	}
	m := func(item *CategoryEntity) string {
		label := item.UniqueId
		// if item.Name != nil {
		// 	label += " >>> " + *item.Name
		// }
		return label
	}
	query := fireback.QueryStringCastCli(searchFields, keyword, page)
	items, meta, err := CategoryActions.Query(query)
	stringItems := []string{}
	for _, item := range items {
		label := m(item)
		stringItems = append(stringItems, label)
	}
	return stringItems, meta, err
}

var CategoryDevCommands = []cli.Command{
	CategoryWipeCmd,
	{
		Name:  "mock",
		Usage: "Generates mock records based on the entity definition",
		Flags: []cli.Flag{
			&cli.IntFlag{
				Name:  "count",
				Usage: "how many activation key do you need to be generated and stored in database",
				Value: 10,
			},
			&cli.BoolFlag{
				Name:  "batch",
				Usage: "Multiple insert into database mode. Might miss children and relations at the moment",
			},
		},
		Action: func(c *cli.Context) error {
			query := fireback.CommonCliQueryDSLBuilderAuthorize(c, &fireback.SecurityModel{
				ActionRequires: []fireback.PermissionInfo{PERM_ROOT_CATEGORY_CREATE},
			})
			if c.Bool("batch") {
				CategoryActionSeederMultiple(query, c.Int("count"))
			} else {
				CategoryActionSeeder(query, c.Int("count"))
			}
			return nil
		},
	},
	{
		Name:    "init",
		Aliases: []string{"i"},
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:  "format",
				Usage: "Format of the export or import file. Can be 'yaml', 'yml', 'json'",
				Value: "yaml",
			},
		},
		Usage: "Creates a basic seeder file for you, based on the definition module we have. You can populate this file as an example",
		Action: func(c *cli.Context) error {
			seed := CategoryActions.SeederInit()
			fireback.CommonInitSeeder(strings.TrimSpace(c.String("format")), seed)
			return nil
		},
	},
	cli.Command{
		Name:  "mlist",
		Usage: "Prints the list of embedded mocks into the app",
		Action: func(c *cli.Context) error {
			if entity, err := fireback.GetSeederFilenames(&mocks.ViewsFs, ""); err != nil {
				fmt.Println(err.Error())
			} else {
				f, _ := json.MarshalIndent(entity, "", "  ")
				fmt.Println(string(f))
			}
			return nil
		},
	},
	cli.Command{
		Name:  "msync",
		Usage: "Tries to sync mocks into the system",
		Action: func(c *cli.Context) error {
			fireback.CommonCliImportEmbedCmd(c,
				CategoryActions.Create,
				reflect.ValueOf(&CategoryEntity{}).Elem(),
				&mocks.ViewsFs,
			)
			return nil
		},
	},
}
var CategoryImportExportCommands = []cli.Command{
	{
		Name:    "validate",
		Aliases: []string{"v"},
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:  "file",
				Usage: "Validates an import file, such as yaml, json, csv, and gives some insights how the after import it would look like",
				Value: "category-seeder-category.yml",
				// Uncomment before publish, they need to specify
				// Required: true,
			},
			&cli.StringFlag{
				Name:  "format",
				Usage: "Format of the export or import file. Can be 'yaml', 'yml', 'json'",
				Value: "yaml",
			},
		},
		Usage: "Reads a yaml file containing an array of categories, you can run this to validate if your import file is correct, and how it would look like after import",
		Action: func(c *cli.Context) error {
			data := &[]CategoryEntity{}
			fireback.ReadYamlFile(c.String("file"), data)
			fmt.Println(data)
			return nil
		},
	},
	cli.Command{
		Name:  "slist",
		Usage: "Prints the list of files attached to this module for syncing or bootstrapping project",
		Action: func(c *cli.Context) error {
			if entity, err := fireback.GetSeederFilenames(categorySeedersFs, ""); err != nil {
				fmt.Println(err.Error())
			} else {
				f, _ := json.MarshalIndent(entity, "", "  ")
				fmt.Println(string(f))
			}
			return nil
		},
	},
	cli.Command{
		Name:  "ssync",
		Usage: "Tries to sync the embedded content into the database, the list could be seen by 'slist' command",
		Action: func(c *cli.Context) error {
			fireback.CommonCliImportEmbedCmd(c,
				CategoryActions.Create,
				reflect.ValueOf(&CategoryEntity{}).Elem(),
				categorySeedersFs,
			)
			return nil
		},
	},
	cli.Command{
		Name:    "export",
		Aliases: []string{"e"},
		Flags: append(fireback.CommonQueryFlags,
			&cli.StringFlag{
				Name:     "file",
				Usage:    "The address of file you want the csv/yaml/json be exported to",
				Required: true,
			}),
		Usage: "Exports a query results into the csv/yaml/json format",
		Action: func(c *cli.Context) error {
			return fireback.CommonCliExportCmd2(c,
				CategoryEntityStream,
				reflect.ValueOf(&CategoryEntity{}).Elem(),
				c.String("file"),
				&metas.MetaFs,
				"CategoryFieldMap.yml",
				CategoryPreloadRelations,
			)
		},
	},
	cli.Command{
		Name: "import",
		Flags: append(
			append(
				fireback.CommonQueryFlags,
				&cli.StringFlag{
					Name:     "file",
					Usage:    "The address of file you want the csv be imported from",
					Required: true,
				}),
			CategoryCommonCliFlagsOptional...,
		),
		Usage: "imports csv/yaml/json file and place it and its children into database",
		Action: func(c *cli.Context) error {
			fireback.CommonCliImportCmdAuthorized(c,
				CategoryActions.Create,
				reflect.ValueOf(&CategoryEntity{}).Elem(),
				c.String("file"),
				&fireback.SecurityModel{
					ActionRequires: []fireback.PermissionInfo{PERM_ROOT_CATEGORY_CREATE},
				},
				func() CategoryEntity {
					v := CastCategoryFromCli(c)
					return *v
				},
			)
			return nil
		},
	},
}
var CategoryCliCommands []cli.Command = []cli.Command{
	CATEGORY_ACTION_QUERY.ToCli(),
	CATEGORY_ACTION_TABLE.ToCli(),
	CATEGORY_ACTION_PATCH.ToCli(),
	CategoryCreateCmd,
	CategoryAskCmd,
	CategoryCreateInteractiveCmd,
	fireback.GetCommonRemoveQuery(
		reflect.ValueOf(&CategoryEntity{}).Elem(),
		CategoryActions.Remove,
	),
	fireback.GetCommonCteQuery(CategoryActions.CteQuery),
	fireback.GetCommonPivotQuery(CategoryActionCommonPivotQuery),
}

func CategoryCliFn() cli.Command {
	commands := append(CategoryImportExportCommands, CategoryCliCommands...)
	if !fireback.GetConfig().Production {
		commands = append(commands, CategoryDevCommands...)
	}
	return cli.Command{
		Name:        "category",
		Description: "Categorys module actions",
		Usage:       `Represting categories across the products, which can have product or child categories, or both at the same time.`,
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:  "language",
				Value: "en",
			},
		},
		Subcommands: commands,
	}
}

var CATEGORY_ACTION_TABLE = fireback.Module3Action{
	Name:          "table",
	ActionAliases: []string{"t"},
	Flags:         fireback.CommonQueryFlags,
	Description:   "Table formatted queries all of the entities in database based on the standard query format",
	Action:        CategoryActions.Query,
	CliAction: func(c *cli.Context, security *fireback.SecurityModel) error {
		fireback.CommonCliTableCmd2(c,
			CategoryActions.Query,
			security,
			reflect.ValueOf(&CategoryEntity{}).Elem(),
		)
		return nil
	},
}
var CATEGORY_ACTION_QUERY = fireback.Module3Action{
	Method: "GET",
	Url:    "/categories",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_CATEGORY_QUERY},
	},
	Handlers: []gin.HandlerFunc{
		func(c *gin.Context) {
			qs := &CategoryEntityQs{}
			fireback.HttpQueryEntity(c, CategoryActions.Query, qs)
		},
	},
	Format:         "QUERY",
	Action:         CategoryActions.Query,
	ResponseEntity: &[]CategoryEntity{},
	Out: &fireback.Module3ActionBody{
		Entity: "CategoryEntity",
	},
	CliAction: func(c *cli.Context, security *fireback.SecurityModel) error {
		qs := &CategoryEntityQs{}
		fireback.CommonCliQueryCmd3(
			c,
			CategoryActions.Query,
			security,
			qs,
		)
		return nil
	},
	CliName:       "query",
	Name:          "query",
	ActionAliases: []string{"q"},
	Flags:         append(fireback.CommonQueryFlags, CategoryQsFlags...),
	Description:   "Queries all of the entities in database based on the standard query format (s+)",
}
var CATEGORY_ACTION_QUERY_CTE = fireback.Module3Action{
	Method: "GET",
	Url:    "/cte-categories",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_CATEGORY_QUERY},
	},
	Handlers: []gin.HandlerFunc{
		func(c *gin.Context) {
			qs := &CategoryEntityQs{}
			fireback.HttpQueryEntity(c, CategoryActions.CteQuery, qs)
		},
	},
	Format:         "QUERY",
	Action:         CategoryActions.CteQuery,
	ResponseEntity: &[]CategoryEntity{},
	Out: &fireback.Module3ActionBody{
		Entity: "CategoryEntity",
	},
}
var CATEGORY_ACTION_EXPORT = fireback.Module3Action{
	Method: "GET",
	Url:    "/categories/export",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_CATEGORY_QUERY},
	},
	Handlers: []gin.HandlerFunc{
		func(c *gin.Context) {
			fireback.HttpStreamFileChannel(c, CategoryActionExport)
		},
	},
	Format:         "QUERY",
	Action:         CategoryActionExport,
	ResponseEntity: &[]CategoryEntity{},
	Out: &fireback.Module3ActionBody{
		Entity: "CategoryEntity",
	},
}
var CATEGORY_ACTION_GET_ONE = fireback.Module3Action{
	Method: "GET",
	Url:    "/category/:uniqueId",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_CATEGORY_QUERY},
	},
	Handlers: []gin.HandlerFunc{
		func(c *gin.Context) {
			fireback.HttpGetEntity(c, CategoryActions.GetOne)
		},
	},
	Format:         "GET_ONE",
	Action:         CategoryActions.GetOne,
	ResponseEntity: &CategoryEntity{},
	Out: &fireback.Module3ActionBody{
		Entity: "CategoryEntity",
	},
}
var CATEGORY_ACTION_POST_ONE = fireback.Module3Action{
	Name:          "create",
	ActionAliases: []string{"c"},
	Description:   "Create new category",
	Flags:         CategoryCommonCliFlags,
	Method:        "POST",
	Url:           "/category",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_CATEGORY_CREATE},
	},
	Handlers: []gin.HandlerFunc{
		func(c *gin.Context) {
			fireback.HttpPostEntity(c, CategoryActions.Create)
		},
	},
	CliAction: func(c *cli.Context, security *fireback.SecurityModel) error {
		result, err := fireback.CliPostEntity(c, CategoryActions.Create, security)
		fireback.HandleActionInCli(c, result, err, map[string]map[string]string{})
		if err != nil {
			return err
		}
		return nil
	},
	Action:         CategoryActions.Create,
	Format:         "POST_ONE",
	RequestEntity:  &CategoryEntity{},
	ResponseEntity: &CategoryEntity{},
	Out: &fireback.Module3ActionBody{
		Entity: "CategoryEntity",
	},
	In: &fireback.Module3ActionBody{
		Entity: "CategoryEntity",
	},
}
var CATEGORY_ACTION_PATCH = fireback.Module3Action{
	Name:          "update",
	ActionAliases: []string{"u"},
	Flags:         CategoryCommonCliFlagsOptional,
	Method:        "PATCH",
	Url:           "/category",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_CATEGORY_UPDATE},
	},
	Handlers: []gin.HandlerFunc{
		func(c *gin.Context) {
			fireback.HttpUpdateEntity(c, CategoryActions.Update)
		},
	},
	Action:         CategoryActions.Update,
	RequestEntity:  &CategoryEntity{},
	ResponseEntity: &CategoryEntity{},
	Format:         "PATCH_ONE",
	Out: &fireback.Module3ActionBody{
		Entity: "CategoryEntity",
	},
	In: &fireback.Module3ActionBody{
		Entity: "CategoryEntity",
	},
	Description: "Update the Category entity by unique id",
	CliName:     "update",
	CliAction: func(c *cli.Context, security *fireback.SecurityModel) error {
		result, err := fireback.CliPatchEntity(c, CategoryActions.Update, security)
		fireback.HandleActionInCli(c, result, err, map[string]map[string]string{})
		if err != nil {
			return err
		}
		return nil
	},
}
var CATEGORY_ACTION_PATCH_BULK = fireback.Module3Action{
	Method: "PATCH",
	Url:    "/categories",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_CATEGORY_UPDATE},
	},
	Handlers: []gin.HandlerFunc{
		func(c *gin.Context) {
			fireback.HttpUpdateEntities(c, CategoryActionBulkUpdate)
		},
	},
	Action:         CategoryActionBulkUpdate,
	Format:         "PATCH_BULK",
	RequestEntity:  &fireback.BulkRecordRequest[CategoryEntity]{},
	ResponseEntity: &fireback.BulkRecordRequest[CategoryEntity]{},
	Out: &fireback.Module3ActionBody{
		Entity: "CategoryEntity",
	},
	In: &fireback.Module3ActionBody{
		Entity: "CategoryEntity",
	},
}
var CATEGORY_ACTION_DELETE = fireback.Module3Action{
	Method: "DELETE",
	Url:    "/category",
	Format: "DELETE_DSL",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_CATEGORY_DELETE},
	},
	Handlers: []gin.HandlerFunc{
		func(c *gin.Context) {
			fireback.HttpRemoveEntity(c, CategoryActions.Remove)
		},
	},
	Action:         CategoryActions.Remove,
	RequestEntity:  &fireback.DeleteRequest{},
	ResponseEntity: &fireback.DeleteResponse{},
	TargetEntity:   &CategoryEntity{},
}
var CATEGORY_PARAMETERS_ACTION_PATCH = fireback.Module3Action{
	Method: "PATCH",
	Url:    "/category/:linkerId/parameters/:uniqueId",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_CATEGORY_UPDATE},
	},
	Handlers: []gin.HandlerFunc{
		func(
			c *gin.Context,
		) {
			fireback.HttpUpdateEntity(c, CategoryParametersActionUpdate)
		},
	},
	Action:         CategoryParametersActionUpdate,
	Format:         "PATCH_ONE",
	RequestEntity:  &CategoryParameters{},
	ResponseEntity: &CategoryParameters{},
	Out: &fireback.Module3ActionBody{
		Entity: "CategoryParameters",
	},
	In: &fireback.Module3ActionBody{
		Entity: "CategoryParameters",
	},
}
var CATEGORY_PARAMETERS_ACTION_GET = fireback.Module3Action{
	Method: "GET",
	Url:    "/category/parameters/:linkerId/:uniqueId",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_CATEGORY_QUERY},
	},
	Handlers: []gin.HandlerFunc{
		func(
			c *gin.Context,
		) {
			fireback.HttpGetEntity(c, CategoryParametersActionGetOne)
		},
	},
	Action:         CategoryParametersActionGetOne,
	Format:         "GET_ONE",
	ResponseEntity: &CategoryParameters{},
	Out: &fireback.Module3ActionBody{
		Entity: "CategoryParameters",
	},
}
var CATEGORY_PARAMETERS_ACTION_POST = fireback.Module3Action{
	Method: "POST",
	Url:    "/category/:linkerId/parameters",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_CATEGORY_CREATE},
	},
	Handlers: []gin.HandlerFunc{
		func(
			c *gin.Context,
		) {
			fireback.HttpPostEntity(c, CategoryParametersActionCreate)
		},
	},
	Action:         CategoryParametersActionCreate,
	Format:         "POST_ONE",
	RequestEntity:  &CategoryParameters{},
	ResponseEntity: &CategoryParameters{},
	Out: &fireback.Module3ActionBody{
		Entity: "CategoryParameters",
	},
	In: &fireback.Module3ActionBody{
		Entity: "CategoryParameters",
	},
}

/**
 *	Override this function on CategoryEntityHttp.go,
 *	In order to add your own http
 **/
var AppendCategoryRouter = func(r *[]fireback.Module3Action) {}

func GetCategoryModule3Actions() []fireback.Module3Action {
	routes := []fireback.Module3Action{
		CATEGORY_ACTION_QUERY_CTE,
		CATEGORY_ACTION_QUERY,
		CATEGORY_ACTION_EXPORT,
		CATEGORY_ACTION_GET_ONE,
		CATEGORY_ACTION_POST_ONE,
		CATEGORY_ACTION_PATCH,
		CATEGORY_ACTION_PATCH_BULK,
		CATEGORY_ACTION_DELETE,
		CATEGORY_PARAMETERS_ACTION_PATCH,
		CATEGORY_PARAMETERS_ACTION_GET,
		CATEGORY_PARAMETERS_ACTION_POST,
	}
	// Append user defined functions
	AppendCategoryRouter(&routes)
	return routes
}

var PERM_ROOT_CATEGORY = fireback.PermissionInfo{
	CompleteKey: "root.modules.product.category.*",
	Name:        "Entire category actions (*)",
	Description: "",
}
var PERM_ROOT_CATEGORY_DELETE = fireback.PermissionInfo{
	CompleteKey: "root.modules.product.category.delete",
	Name:        "Delete category",
	Description: "",
}
var PERM_ROOT_CATEGORY_CREATE = fireback.PermissionInfo{
	CompleteKey: "root.modules.product.category.create",
	Name:        "Create category",
	Description: "",
}
var PERM_ROOT_CATEGORY_UPDATE = fireback.PermissionInfo{
	CompleteKey: "root.modules.product.category.update",
	Name:        "Update category",
	Description: "",
}
var PERM_ROOT_CATEGORY_QUERY = fireback.PermissionInfo{
	CompleteKey: "root.modules.product.category.query",
	Name:        "Query category",
	Description: "",
}
var ALL_CATEGORY_PERMISSIONS = []fireback.PermissionInfo{
	PERM_ROOT_CATEGORY_DELETE,
	PERM_ROOT_CATEGORY_CREATE,
	PERM_ROOT_CATEGORY_UPDATE,
	PERM_ROOT_CATEGORY_QUERY,
	PERM_ROOT_CATEGORY,
}

func NewCategoryCreatedEvent(
	payload *CategoryEntity,
	query *fireback.QueryDSL,
) (*fireback.Event, error) {
	event := &fireback.Event{
		Name:    "CategoryCreated",
		Payload: payload,
		Security: &fireback.SecurityModel{
			ActionRequires: []fireback.PermissionInfo{
				PERM_ROOT_CATEGORY_QUERY,
			},
		},
		CacheKey: "*product.CategoryEntity",
	}
	// Apply the source of the event based on querydsl
	fireback.ApplyQueryDslContextToEvent(event, *query)
	return event, nil
}
func NewCategoryUpdatedEvent(
	payload *CategoryEntity,
	query *fireback.QueryDSL,
) (*fireback.Event, error) {
	event := &fireback.Event{
		Name:    "CategoryUpdated",
		Payload: payload,
		Security: &fireback.SecurityModel{
			ActionRequires: []fireback.PermissionInfo{
				PERM_ROOT_CATEGORY_QUERY,
			},
		},
		CacheKey: "*product.CategoryEntity",
	}
	// Apply the source of the event based on querydsl
	fireback.ApplyQueryDslContextToEvent(event, *query)
	return event, nil
}

var CategoryEntityBundle = fireback.EntityBundle{
	Permissions: ALL_CATEGORY_PERMISSIONS,
	// Cli command has been exluded, since we use module to wrap all the entities
	// to be more easier to wrap up.
	// Create your own bundle if you need with Cli
	//CliCommands: []cli.Command{
	//	CategoryCliFn(),
	//},
	Actions:      GetCategoryModule3Actions(),
	MockProvider: CategoryImportMocks,
	AutoMigrationEntities: []interface{}{
		&CategoryEntity{},
		&CategoryParameters{},
		&CategoryEntityPolyglot{},
	},
	MigrationScripts: []fireback.MigrationScript{},
}
