package product

/*
*	Generated by fireback 1.2.4
*	Written by Ali Torabi.
*	Checkout the repository for licenses and contribution: https://github.com/torabian/fireback
 */
import (
	"embed"
	"encoding/json"
	"fmt"
	"github.com/gin-gonic/gin"
	jsoniter "github.com/json-iterator/go"
	metas "github.com/myorg/mynewmicroservice/modules/product/metas"
	mocks "github.com/myorg/mynewmicroservice/modules/product/mocks/ParameterType"
	seeders "github.com/myorg/mynewmicroservice/modules/product/seeders/ParameterType"
	"github.com/schollz/progressbar/v3"
	"github.com/torabian/fireback/modules/fireback"
	"github.com/urfave/cli"
	"gopkg.in/yaml.v2"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"log"
	reflect "reflect"
	"strings"
	"time"
)

var parameterTypeSeedersFs = &seeders.ViewsFs

func ResetParameterTypeSeeders(fs *embed.FS) {
	parameterTypeSeedersFs = fs
}

type ParameterTypeEntityQs struct {
	Name        fireback.QueriableField `cli:"name" table:"parameter_type" typeof:"string" column:"name" qs:"name"`
	Description fireback.QueriableField `cli:"description" table:"parameter_type" typeof:"string" column:"description" qs:"description"`
	BindingKey  fireback.QueriableField `cli:"binding-key" table:"parameter_type" typeof:"string" column:"binding_key" qs:"bindingKey"`
}

func (x *ParameterTypeEntityQs) GetQuery() string {
	return fireback.GenerateQueryStringStyle(reflect.ValueOf(x), "")
}

var ParameterTypeQsFlags = []cli.Flag{
	&cli.StringFlag{
		Name:  "name",
		Usage: "Type of the parameter which can be selected for a parameter",
	},
	&cli.StringFlag{
		Name:  "description",
		Usage: "Describe the parameter type so selection is easier for content management.",
	},
	&cli.StringFlag{
		Name:  "binding-key",
		Usage: "A unique key that would bind this type to programming langauge base on limits in the code base.",
	},
}

type ParameterTypeEntity struct {
	// Defines the visibility of the record in the table.
	// Visibility is a detailed topic, you can check all of the visibility values in fireback/visibility.go
	// by default, visibility of record are 0, means they are protected by the workspace
	// which are being created, and visible to every member of the workspace
	Visibility fireback.String `json:"visibility,omitempty" yaml:"visibility,omitempty" xml:"visibility,omitempty"`
	// The unique-id of the workspace which content belongs to. Upon creation this will be designated
	// to the selected workspace by user, if they have write access. You can change this value
	// or prevent changes to it manually (on root features for example modifying other workspace)
	WorkspaceId fireback.String `json:"workspaceId,omitempty" xml:"workspaceId,omitempty" yaml:"workspaceId,omitempty"`
	// The unique-id of the parent table, which this record is being linked to.
	// used internally for making relations in fireback, generally does not need manual changes
	// or modification by the developer or user. For example, if you have a object inside an object
	// the unique-id of the parent will be written in the child.
	LinkerId fireback.String `json:"linkerId,omitempty" xml:"linkerId,omitempty" yaml:"linkerId,omitempty"`
	// Used for recursive or parent-child operations. Some tables, are having nested relations,
	// and this field makes the table self refrenceing. ParentId needs to exist in the table before
	// creating of modifying a record.
	ParentId fireback.String `json:"parentId,omitempty" xml:"parentId,omitempty" yaml:"parentId,omitempty"`
	// Makes a field deletable. Some records should not be deletable at all.
	// default it's true.
	IsDeletable *bool `json:"isDeletable,omitempty" xml:"isDeletable,omitempty" yaml:"isDeletable,omitempty" gorm:"default:true"`
	// Makes a field updatable. Some records should not be updatable at all.
	// default it's true.
	IsUpdatable *bool `json:"isUpdatable,omitempty" xml:"isUpdatable,omitempty" yaml:"isUpdatable,omitempty" gorm:"default:true"`
	// The unique-id of the user which is creating the record, or the record belongs to.
	// Administration might want to change this to any user, by default Fireback fills
	// it to the current authenticated user.
	UserId fireback.String `json:"userId,omitempty" xml:"userId,omitempty" yaml:"userId,omitempty"`
	// General mechanism to rank the elements. From code perspective, it's just a number,
	// but you can sort it based on any logic for records to make a ranking, sorting.
	// they should not be unique across a table.
	Rank fireback.Int64 `json:"rank,omitempty" yaml:"rank,omitempty" xml:"rank,omitempty" gorm:"type:int;name:rank"`
	// Primary numeric key in the database. This value is not meant to be exported to public
	// or be used to access data at all. Rather a mechanism of indexing columns internally
	// or cursor pagination in future releases of fireback, or better search performance.
	ID uint `gorm:"primaryKey;autoIncrement" json:"-" yaml:"-" xml:"-"`
	// Unique id of the record across the table. This value will be accessed from public APIs,
	// and many other places intead of numeric ID property.
	// Upon generation, a UUID automatically is being assigned, and if user has specified the
	// Unique id in the post body, it will be used. This mechanism allows to manage unsaved
	// content on front-end much easier than requiring parent to exists first.
	UniqueId string `json:"uniqueId,omitempty" xml:"uniqueId,omitempty" gorm:"unique;not null;size:100;" yaml:"uniqueId,omitempty"`
	// The time that the record has been updated in datetime.
	// the field will be automatically populated by gorm orm.
	UpdatedAt *time.Time `json:"updatedAt,omitempty" xml:"updatedAt,omitempty" yaml:"updatedAt,omitempty"`
	// The time that the record has been created in datetime.
	// the field will be automatically populated by gorm orm.
	CreatedAt *time.Time `json:"createdAt,omitempty" xml:"createdAt,omitempty" yaml:"createdAt,omitempty"`
	// The time that the record has been deleted softly (means the data still exists in database, but no longer visible to any feature) in nano datatime
	// you need to make sure check this field if writing custom sql queries.
	// the field will be automatically populated by gorm orm.
	DeletedAt *time.Time `json:"deletedAt,omitempty" xml:"deletedAt,omitempty" yaml:"deletedAt,omitempty"`
	// Record creation date time formatting based on locale of the headers, or other
	// possible factors.
	CreatedFormatted string `json:"createdFormatted,omitempty" xml:"createdFormatted,omitempty" yaml:"createdFormatted,omitempty" sql:"-" gorm:"-"`
	// Record update date time formatting based on locale of the headers, or other
	// possible factors.
	UpdatedFormatted string `json:"updatedFormatted,omitempty" xml:"updatedFormatted,omitempty" yaml:"updatedFormatted,omitempty" sql:"-" gorm:"-"`
	// Type of the parameter which can be selected for a parameter
	Name string `json:"name" xml:"name" yaml:"name"  validate:"required"        translate:"true"  `
	// Describe the parameter type so selection is easier for content management.
	Description string `json:"description" xml:"description" yaml:"description"        translate:"true"  `
	// A unique key that would bind this type to programming langauge base on limits in the code base.
	BindingKey   string                         `json:"bindingKey" xml:"bindingKey" yaml:"bindingKey"  validate:"required"        `
	Translations []*ParameterTypeEntityPolyglot `json:"translations,omitempty" xml:"translations,omitempty" yaml:"translations,omitempty" gorm:"foreignKey:LinkerId;references:UniqueId;constraint:OnDelete:CASCADE"`
	Children     []*ParameterTypeEntity         `csv:"-" gorm:"-" sql:"-" json:"children,omitempty" xml:"children,omitempty"  yaml:"children,omitempty"`
	LinkedTo     *ParameterTypeEntity           `csv:"-" yaml:"-" gorm:"-" json:"-" sql:"-" xml:"-"`
}

func ParameterTypeEntityStream(q fireback.QueryDSL) (chan []*ParameterTypeEntity, *fireback.QueryResultMeta, *fireback.IError) {
	cn := make(chan []*ParameterTypeEntity)
	q.ItemsPerPage = 50
	q.StartIndex = 0
	_, qrm, err := ParameterTypeActions.Query(q)
	if err != nil {
		return nil, nil, err
	}
	go func() {
		defer close(cn)
		for i := 0; i <= int(qrm.TotalAvailableItems)-1; i++ {
			items, _, _ := ParameterTypeActions.Query(q)
			i += q.ItemsPerPage
			q.StartIndex = i
			cn <- items
		}
	}()
	return cn, qrm, nil
}

type ParameterTypeEntityList struct {
	Items []*ParameterTypeEntity
}

func NewParameterTypeEntityList(items []*ParameterTypeEntity) *ParameterTypeEntityList {
	return &ParameterTypeEntityList{
		Items: items,
	}
}
func (x *ParameterTypeEntityList) Json() string {
	if x != nil {
		str, _ := json.MarshalIndent(x, "", "  ")
		return (string(str))
	}
	return ""
}
func (x *ParameterTypeEntityList) ToTree() *fireback.TreeOperation[ParameterTypeEntity] {
	return fireback.NewTreeOperation(
		x.Items,
		func(t *ParameterTypeEntity) string {
			if !t.ParentId.Valid {
				return ""
			}
			return t.ParentId.String
		},
		func(t *ParameterTypeEntity) string {
			return t.UniqueId
		},
	)
}

var ParameterTypePreloadRelations []string = []string{}

type parameterTypeActionsSig struct {
	Update         func(query fireback.QueryDSL, dto *ParameterTypeEntity) (*ParameterTypeEntity, *fireback.IError)
	Create         func(dto *ParameterTypeEntity, query fireback.QueryDSL) (*ParameterTypeEntity, *fireback.IError)
	Upsert         func(dto *ParameterTypeEntity, query fireback.QueryDSL) (*ParameterTypeEntity, *fireback.IError)
	SeederInit     func() *ParameterTypeEntity
	Remove         func(query fireback.QueryDSL) (int64, *fireback.IError)
	MultiInsert    func(dtos []*ParameterTypeEntity, query fireback.QueryDSL) ([]*ParameterTypeEntity, *fireback.IError)
	GetOne         func(query fireback.QueryDSL) (*ParameterTypeEntity, *fireback.IError)
	GetByWorkspace func(query fireback.QueryDSL) (*ParameterTypeEntity, *fireback.IError)
	Query          func(query fireback.QueryDSL) ([]*ParameterTypeEntity, *fireback.QueryResultMeta, *fireback.IError)
}

var ParameterTypeActions parameterTypeActionsSig = parameterTypeActionsSig{
	Update:         ParameterTypeActionUpdateFn,
	Create:         ParameterTypeActionCreateFn,
	Upsert:         ParameterTypeActionUpsertFn,
	Remove:         ParameterTypeActionRemoveFn,
	SeederInit:     ParameterTypeActionSeederInitFn,
	MultiInsert:    ParameterTypeMultiInsertFn,
	GetOne:         ParameterTypeActionGetOneFn,
	GetByWorkspace: ParameterTypeActionGetByWorkspaceFn,
	Query:          ParameterTypeActionQueryFn,
}

func ParameterTypeActionUpsertFn(dto *ParameterTypeEntity, query fireback.QueryDSL) (*ParameterTypeEntity, *fireback.IError) {
	return nil, nil
}

var PARAMETER_TYPE_EVENT_CREATED = "parameterType.created"
var PARAMETER_TYPE_EVENT_UPDATED = "parameterType.updated"
var PARAMETER_TYPE_EVENT_DELETED = "parameterType.deleted"
var PARAMETER_TYPE_EVENTS = []string{
	PARAMETER_TYPE_EVENT_CREATED,
	PARAMETER_TYPE_EVENT_UPDATED,
	PARAMETER_TYPE_EVENT_DELETED,
}

type ParameterTypeFieldMap struct {
	Name        fireback.TranslatedString `yaml:"name"`
	Description fireback.TranslatedString `yaml:"description"`
	BindingKey  fireback.TranslatedString `yaml:"bindingKey"`
}

var ParameterTypeEntityMetaConfig map[string]int64 = map[string]int64{}
var ParameterTypeEntityJsonSchema = fireback.ExtractEntityFields(reflect.ValueOf(&ParameterTypeEntity{}))

type ParameterTypeEntityPolyglot struct {
	LinkerId    string `gorm:"uniqueId;not null;size:100;" json:"linkerId,omitempty" yaml:"linkerId,omitempty" xml:"linkerId,omitempty"`
	LanguageId  string `gorm:"uniqueId;not null;size:100;" json:"languageId,omitempty" xml:"languageId,omitempty" yaml:"languageId,omitempty"`
	Name        string `yaml:"name,omitempty" xml:"name,omitempty" json:"name,omitempty"`
	Description string `yaml:"description,omitempty" xml:"description,omitempty" json:"description,omitempty"`
}

func entityParameterTypeFormatter(dto *ParameterTypeEntity, query fireback.QueryDSL) {
	if dto == nil {
		return
	}
}
func ParameterTypeActionSeederMultiple(query fireback.QueryDSL, count int) {
	successInsert := 0
	failureInsert := 0
	batchSize := 100
	bar := progressbar.Default(int64(count))
	// Collect entities in batches
	var entitiesBatch []*ParameterTypeEntity
	for i := 1; i <= count; i++ {
		entity := ParameterTypeActions.SeederInit()
		entitiesBatch = append(entitiesBatch, entity)
		// When batch size is reached, perform the batch insert
		if len(entitiesBatch) == batchSize || i == count {
			// Insert batch
			_, err := ParameterTypeActions.MultiInsert(entitiesBatch, query)
			if err == nil {
				successInsert += len(entitiesBatch)
			} else {
				fmt.Println(err)
				failureInsert += len(entitiesBatch)
			}
			// Clear the batch after insert
			entitiesBatch = nil
		}
		bar.Add(1)
	}
	fmt.Println("Success", successInsert, "Failure", failureInsert)
}
func ParameterTypeActionSeeder(query fireback.QueryDSL, count int) {
	successInsert := 0
	failureInsert := 0
	bar := progressbar.Default(int64(count))
	for i := 1; i <= count; i++ {
		entity := ParameterTypeActions.SeederInit()
		_, err := ParameterTypeActions.Create(entity, query)
		if err == nil {
			successInsert++
		} else {
			fmt.Println(err)
			failureInsert++
		}
		bar.Add(1)
	}
	fmt.Println("Success", successInsert, "Failure", failureInsert)
}
func (x *ParameterTypeEntity) GetNameTranslated(language string) string {
	if x.Translations != nil && len(x.Translations) > 0 {
		for _, item := range x.Translations {
			if item.LanguageId == language {
				return item.Name
			}
		}
	}
	return ""
}
func (x *ParameterTypeEntity) GetDescriptionTranslated(language string) string {
	if x.Translations != nil && len(x.Translations) > 0 {
		for _, item := range x.Translations {
			if item.LanguageId == language {
				return item.Description
			}
		}
	}
	return ""
}
func (x *ParameterTypeEntity) Seeder() string {
	obj := ParameterTypeActions.SeederInit()
	v, _ := json.MarshalIndent(obj, "", "  ")
	return string(v)
}
func ParameterTypeActionSeederInitFn() *ParameterTypeEntity {
	entity := &ParameterTypeEntity{}
	return entity
}
func ParameterTypeAssociationCreate(dto *ParameterTypeEntity, query fireback.QueryDSL) error {
	return nil
}

/**
* These kind of content are coming from another entity, which is indepndent module
* If we want to create them, we need to do it before. This is not association.
**/
func ParameterTypeRelationContentCreate(dto *ParameterTypeEntity, query fireback.QueryDSL) error {
	return nil
}
func ParameterTypeRelationContentUpdate(dto *ParameterTypeEntity, query fireback.QueryDSL) error {
	return nil
}
func ParameterTypePolyglotUpdateHandler(dto *ParameterTypeEntity, query fireback.QueryDSL) {
	if dto == nil {
		return
	}
	fireback.PolyglotUpdateHandler(dto, &ParameterTypeEntityPolyglot{}, query)
}

/**
 * This will be validating your entity fully. Important note is that, you add validate:* tag
 * in your entity, it will automatically work here. For slices inside entity, make sure you add
 * extra line of AppendSliceErrors, otherwise they won't be detected
 */
func ParameterTypeValidator(dto *ParameterTypeEntity, isPatch bool) *fireback.IError {
	err := fireback.CommonStructValidatorPointer(dto, isPatch)
	return err
}

// Creates a set of natural language queries, which can be used with
// AI tools to create content or help with some tasks
var ParameterTypeAskCmd cli.Command = cli.Command{
	Name:  "nlp",
	Usage: "Set of natural language queries which helps creating content or data",
	Subcommands: []cli.Command{
		{
			Name:  "sample",
			Usage: "Asks for generating sample by giving an example data",
			Flags: []cli.Flag{
				&cli.StringFlag{
					Name:  "format",
					Usage: "Format of the export or import file. Can be 'yaml', 'yml', 'json'",
					Value: "yaml",
				},
				&cli.IntFlag{
					Name:  "count",
					Usage: "How many samples to ask",
					Value: 30,
				},
			},
			Action: func(c *cli.Context) error {
				v := &ParameterTypeEntity{}
				format := c.String("format")
				request := "\033[1m" + `
I need you to create me an array of exact signature as the example given below,
with at least ` + fmt.Sprint(c.String("count")) + ` items, mock the content with few words, and guess the possible values
based on the common sense. I need the output to be a valid ` + format + ` file.
Make sure you wrap the entire array in 'items' field. Also before that, I provide some explanation of each field:
Name: (type: string) Description: Type of the parameter which can be selected for a parameter
Description: (type: string) Description: Describe the parameter type so selection is easier for content management.
BindingKey: (type: string) Description: A unique key that would bind this type to programming langauge base on limits in the code base.
And here is the actual object signature:
` + v.Seeder() + `
`
				fmt.Println(request)
				return nil
			},
		},
	},
}

func ParameterTypeEntityPreSanitize(dto *ParameterTypeEntity, query fireback.QueryDSL) {
}
func ParameterTypeEntityBeforeCreateAppend(dto *ParameterTypeEntity, query fireback.QueryDSL) {
	if dto.UniqueId == "" {
		dto.UniqueId = fireback.UUID()
	}
	dto.WorkspaceId = fireback.NewString(query.WorkspaceId)
	dto.UserId = fireback.NewString(query.UserId)
	ParameterTypeRecursiveAddUniqueId(dto, query)
}
func ParameterTypeRecursiveAddUniqueId(dto *ParameterTypeEntity, query fireback.QueryDSL) {
}

/*
*
	Batch inserts, do not have all features that create
	operation does. Use it with unnormalized content,
	or read the source code carefully.
  This is not marked as an action, because it should not be available publicly
  at this moment.
*
*/
func ParameterTypeMultiInsertFn(dtos []*ParameterTypeEntity, query fireback.QueryDSL) ([]*ParameterTypeEntity, *fireback.IError) {
	if len(dtos) > 0 {
		for index := range dtos {
			ParameterTypeEntityPreSanitize(dtos[index], query)
			ParameterTypeEntityBeforeCreateAppend(dtos[index], query)
		}
		var dbref *gorm.DB = nil
		if query.Tx == nil {
			dbref = fireback.GetDbRef()
		} else {
			dbref = query.Tx
		}
		query.Tx = dbref
		err := dbref.Create(&dtos).Error
		if err != nil {
			return nil, fireback.GormErrorToIError(err)
		}
	}
	return dtos, nil
}
func ParameterTypeActionBatchCreateFn(dtos []*ParameterTypeEntity, query fireback.QueryDSL) ([]*ParameterTypeEntity, *fireback.IError) {
	if dtos != nil && len(dtos) > 0 {
		items := []*ParameterTypeEntity{}
		for _, item := range dtos {
			s, err := ParameterTypeActions.Create(item, query)
			if err != nil {
				return nil, err
			}
			items = append(items, s)
		}
		return items, nil
	}
	return dtos, nil
}
func ParameterTypeDeleteEntireChildren(query fireback.QueryDSL, dto *ParameterTypeEntity) *fireback.IError {
	// intentionally removed this. It's hard to implement it, and probably wrong without
	// proper on delete cascade
	return nil
}
func ParameterTypeActionCreateFn(dto *ParameterTypeEntity, query fireback.QueryDSL) (*ParameterTypeEntity, *fireback.IError) {
	// 1. Validate always
	if iError := ParameterTypeValidator(dto, false); iError != nil {
		return nil, iError
	}
	// 1.5 Sanitize the content coming of the front-end
	ParameterTypeEntityPreSanitize(dto, query)
	// 2. Append the necessary information about user, workspace
	ParameterTypeEntityBeforeCreateAppend(dto, query)
	// 3. Create other entities if we want select from them
	ParameterTypeRelationContentCreate(dto, query)
	// 4. Create the entity
	var dbref *gorm.DB = nil
	if query.Tx == nil {
		dbref = fireback.GetDbRef()
	} else {
		dbref = query.Tx
	}
	query.Tx = dbref
	err := dbref.Create(&dto).Error
	if err != nil {
		err := fireback.GormErrorToIError(err)
		return nil, err
	}
	// 5. Create sub entities, objects or arrays, association to other entities
	ParameterTypeAssociationCreate(dto, query)
	// 6. Fire the event into system
	actionEvent, eventErr := NewParameterTypeCreatedEvent(dto, &query)
	if actionEvent != nil && eventErr == nil {
		fireback.GetEventBusInstance().FireEvent(query, *actionEvent)
	} else {
		log.Default().Panicln("Creating event has failed for %v", dto)
	}
	/*
		event.MustFire(PARAMETER_TYPE_EVENT_CREATED, event.M{
			"entity":   dto,
			"entityKey": fireback.GetTypeString(&ParameterTypeEntity{}),
			"target":   "workspace",
			"unqiueId": query.WorkspaceId,
		})
	*/
	return dto, nil
}
func ParameterTypeActionGetOneFn(query fireback.QueryDSL) (*ParameterTypeEntity, *fireback.IError) {
	refl := reflect.ValueOf(&ParameterTypeEntity{})
	item, err := fireback.GetOneEntity[ParameterTypeEntity](query, refl)
	entityParameterTypeFormatter(item, query)
	return item, err
}
func ParameterTypeActionGetByWorkspaceFn(query fireback.QueryDSL) (*ParameterTypeEntity, *fireback.IError) {
	refl := reflect.ValueOf(&ParameterTypeEntity{})
	item, err := fireback.GetOneByWorkspaceEntity[ParameterTypeEntity](query, refl)
	entityParameterTypeFormatter(item, query)
	return item, err
}
func ParameterTypeActionQueryFn(query fireback.QueryDSL) ([]*ParameterTypeEntity, *fireback.QueryResultMeta, *fireback.IError) {
	refl := reflect.ValueOf(&ParameterTypeEntity{})
	items, meta, err := fireback.QueryEntitiesPointer[ParameterTypeEntity](query, refl)
	for _, item := range items {
		entityParameterTypeFormatter(item, query)
	}
	return items, meta, err
}

var parameterTypeMemoryItems []*ParameterTypeEntity = []*ParameterTypeEntity{}

func ParameterTypeEntityIntoMemory() {
	q := fireback.QueryDSL{
		ItemsPerPage: 500,
		StartIndex:   0,
	}
	_, qrm, _ := ParameterTypeActions.Query(q)
	for i := 0; i <= int(qrm.TotalAvailableItems)-1; i++ {
		items, _, _ := ParameterTypeActions.Query(q)
		parameterTypeMemoryItems = append(parameterTypeMemoryItems, items...)
		i += q.ItemsPerPage
		q.StartIndex = i
	}
}
func ParameterTypeMemGet(id uint) *ParameterTypeEntity {
	for _, item := range parameterTypeMemoryItems {
		if item.ID == id {
			return item
		}
	}
	return nil
}
func ParameterTypeMemJoin(items []uint) []*ParameterTypeEntity {
	res := []*ParameterTypeEntity{}
	for _, item := range items {
		v := ParameterTypeMemGet(item)
		if v != nil {
			res = append(res, v)
		}
	}
	return res
}
func ParameterTypeUpdateExec(dbref *gorm.DB, query fireback.QueryDSL, fields *ParameterTypeEntity) (*ParameterTypeEntity, *fireback.IError) {
	uniqueId := fields.UniqueId
	query.TriggerEventName = PARAMETER_TYPE_EVENT_UPDATED
	ParameterTypeEntityPreSanitize(fields, query)
	var item ParameterTypeEntity
	var itemRefetched ParameterTypeEntity
	// If the entity is distinct by workspace, then the Query.WorkspaceId
	// which is selected is being used as the condition for create or update
	// if not, the unique Id is being used
	cond2 := &ParameterTypeEntity{UniqueId: uniqueId}
	q := dbref.
		Where(cond2).
		FirstOrCreate(&item)
	err := q.UpdateColumns(fields).Error
	if err != nil {
		return nil, fireback.GormErrorToIError(err)
	}
	query.Tx = dbref
	ParameterTypeRelationContentUpdate(fields, query)
	ParameterTypePolyglotUpdateHandler(fields, query)
	if ero := ParameterTypeDeleteEntireChildren(query, fields); ero != nil {
		return nil, ero
	}
	// @meta(update has many)
	err = dbref.
		Preload(clause.Associations).
		Where(&ParameterTypeEntity{UniqueId: uniqueId}).
		First(&itemRefetched).Error
	if err != nil {
		return nil, fireback.GormErrorToIError(err)
	}
	actionEvent, eventErr := NewParameterTypeUpdatedEvent(fields, &query)
	if actionEvent != nil && eventErr == nil {
		fireback.GetEventBusInstance().FireEvent(query, *actionEvent)
	} else {
		log.Default().Panicln("Updating event has failed for %v", fields)
	}
	/*
	   event.MustFire(query.TriggerEventName, event.M{
	     "entity":   &item,
	     "target":   "workspace",
	     "unqiueId": query.WorkspaceId,
	   })*/
	return &itemRefetched, nil
}
func ParameterTypeActionUpdateFn(query fireback.QueryDSL, fields *ParameterTypeEntity) (*ParameterTypeEntity, *fireback.IError) {
	if fields == nil {
		return nil, fireback.Create401Error(&fireback.FirebackMessages.BodyIsMissing, []string{})
	}
	// 1. Validate always
	if iError := ParameterTypeValidator(fields, true); iError != nil {
		return nil, iError
	}
	// Let's not add this. I am not sure of the consequences
	// ParameterTypeRecursiveAddUniqueId(fields, query)
	var dbref *gorm.DB = nil
	if query.Tx == nil {
		dbref = fireback.GetDbRef()
		var item *ParameterTypeEntity
		vf := dbref.Transaction(func(tx *gorm.DB) error {
			dbref = tx
			var err *fireback.IError
			item, err = ParameterTypeUpdateExec(dbref, query, fields)
			if err == nil {
				return nil
			} else {
				return err
			}
		})
		return item, fireback.CastToIError(vf)
	} else {
		dbref = query.Tx
		return ParameterTypeUpdateExec(dbref, query, fields)
	}
}

var ParameterTypeWipeCmd cli.Command = cli.Command{
	Name:  "wipe",
	Usage: "Wipes entire parametertypes ",
	Action: func(c *cli.Context) error {
		query := fireback.CommonCliQueryDSLBuilderAuthorize(c, &fireback.SecurityModel{
			ActionRequires: []fireback.PermissionInfo{PERM_ROOT_PARAMETER_TYPE_DELETE},
		})
		count, _ := ParameterTypeActionWipeClean(query)
		fmt.Println("Removed", count, "of entities")
		return nil
	},
}

func ParameterTypeActionRemoveFn(query fireback.QueryDSL) (int64, *fireback.IError) {
	refl := reflect.ValueOf(&ParameterTypeEntity{})
	query.ActionRequires = []fireback.PermissionInfo{PERM_ROOT_PARAMETER_TYPE_DELETE}
	return fireback.RemoveEntity[ParameterTypeEntity](query, refl)
}
func ParameterTypeActionWipeClean(query fireback.QueryDSL) (int64, error) {
	var err error
	var count int64 = 0
	{
		subCount, subErr := fireback.WipeCleanEntity[ParameterTypeEntity]()
		if subErr != nil {
			fmt.Println("Error while wiping 'ParameterTypeEntity'", subErr)
			return count, subErr
		} else {
			count += subCount
		}
	}
	return count, err
}
func ParameterTypeActionBulkUpdate(
	query fireback.QueryDSL, dto *fireback.BulkRecordRequest[ParameterTypeEntity]) (
	*fireback.BulkRecordRequest[ParameterTypeEntity], *fireback.IError,
) {
	result := []*ParameterTypeEntity{}
	err := fireback.GetDbRef().Transaction(func(tx *gorm.DB) error {
		query.Tx = tx
		for _, record := range dto.Records {
			item, err := ParameterTypeActions.Update(query, record)
			if err != nil {
				return err
			} else {
				result = append(result, item)
			}
		}
		return nil
	})
	if err == nil {
		return dto, nil
	}
	return nil, err.(*fireback.IError)
}
func (x *ParameterTypeEntity) Json() string {
	if x != nil {
		str, _ := json.MarshalIndent(x, "", "  ")
		return (string(str))
	}
	return ""
}

var ParameterTypeEntityMeta = fireback.TableMetaData{
	EntityName:    "ParameterType",
	ExportKey:     "parameter-types",
	TableNameInDb: "parameter-type_entities",
	EntityObject:  &ParameterTypeEntity{},
	ExportStream:  ParameterTypeActionExportT,
	ImportQuery:   ParameterTypeActionImport,
}

func ParameterTypeActionExport(
	query fireback.QueryDSL,
) (chan []byte, *fireback.IError) {
	return fireback.YamlExporterChannel[ParameterTypeEntity](query, ParameterTypeActions.Query, ParameterTypePreloadRelations)
}
func ParameterTypeActionExportT(
	query fireback.QueryDSL,
) (chan []interface{}, *fireback.IError) {
	return fireback.YamlExporterChannelT[ParameterTypeEntity](query, ParameterTypeActions.Query, ParameterTypePreloadRelations)
}
func ParameterTypeActionImport(
	dto interface{}, query fireback.QueryDSL,
) *fireback.IError {
	var json = jsoniter.ConfigCompatibleWithStandardLibrary
	var content ParameterTypeEntity
	cx, err2 := json.Marshal(dto)
	if err2 != nil {
		return fireback.Create401Error(&fireback.FirebackMessages.InvalidContent, []string{})
	}
	json.Unmarshal(cx, &content)
	_, err := ParameterTypeActions.Create(&content, query)
	return err
}

var ParameterTypeCommonCliFlags = []cli.Flag{
	&cli.StringFlag{
		Name:  "x-accept",
		Usage: "Return type of the the content, such as json or yaml",
	},
	&cli.StringFlag{
		Name:     "wid",
		Required: false,
		Usage:    "Provide workspace id, if you want to change the data workspace",
	},
	&cli.StringFlag{
		Name:     "uid",
		Required: false,
		Usage:    "Unique Id - external unique hash to query entity",
	},
	&cli.StringFlag{
		Name:     "pid",
		Required: false,
		Usage:    " Parent record id of the same type",
	},
	&cli.StringFlag{
		Name:     "name",
		Required: true,
		Usage:    `Type of the parameter which can be selected for a parameter (string)`,
	},
	&cli.StringFlag{
		Name:     "description",
		Required: false,
		Usage:    `Describe the parameter type so selection is easier for content management. (string)`,
	},
	&cli.StringFlag{
		Name:     "binding-key",
		Required: true,
		Usage:    `A unique key that would bind this type to programming langauge base on limits in the code base. (string)`,
	},
}
var ParameterTypeCommonInteractiveCliFlags = []fireback.CliInteractiveFlag{
	{
		Name:        "name",
		StructField: "Name",
		Required:    true,
		Recommended: false,
		Usage:       `Type of the parameter which can be selected for a parameter`,
		Type:        "string",
	},
	{
		Name:        "description",
		StructField: "Description",
		Required:    false,
		Recommended: false,
		Usage:       `Describe the parameter type so selection is easier for content management.`,
		Type:        "string",
	},
	{
		Name:        "bindingKey",
		StructField: "BindingKey",
		Required:    true,
		Recommended: false,
		Usage:       `A unique key that would bind this type to programming langauge base on limits in the code base.`,
		Type:        "string",
	},
}
var ParameterTypeCommonCliFlagsOptional = []cli.Flag{
	&cli.StringFlag{
		Name:     "x-src",
		Required: false,
		Usage:    `Import the body of the request from a file (e.g. json/yaml) on the disk`,
	},
	&cli.StringFlag{
		Name:  "x-accept",
		Usage: "Return type of the the content, such as json or yaml",
	},
	&cli.StringFlag{
		Name:     "wid",
		Required: false,
		Usage:    "Provide workspace id, if you want to change the data workspace",
	},
	&cli.StringFlag{
		Name:     "uid",
		Required: false,
		Usage:    "Unique Id - external unique hash to query entity",
	},
	&cli.StringFlag{
		Name:     "pid",
		Required: false,
		Usage:    " Parent record id of the same type",
	},
	&cli.StringFlag{
		Name:     "name",
		Required: true,
		Usage:    `Type of the parameter which can be selected for a parameter (string)`,
	},
	&cli.StringFlag{
		Name:     "description",
		Required: false,
		Usage:    `Describe the parameter type so selection is easier for content management. (string)`,
	},
	&cli.StringFlag{
		Name:     "binding-key",
		Required: true,
		Usage:    `A unique key that would bind this type to programming langauge base on limits in the code base. (string)`,
	},
}
var ParameterTypeCreateCmd cli.Command = PARAMETER_TYPE_ACTION_POST_ONE.ToCli()
var ParameterTypeCreateInteractiveCmd cli.Command = cli.Command{
	Name:  "ic",
	Usage: "Creates a new entity, using requied fields in an interactive name",
	Flags: []cli.Flag{
		&cli.BoolFlag{
			Name:  "all",
			Usage: "Interactively asks for all inputs, not only required ones",
		},
	},
	Action: func(c *cli.Context) {
		query := fireback.CommonCliQueryDSLBuilderAuthorize(c, &fireback.SecurityModel{
			ActionRequires: []fireback.PermissionInfo{PERM_ROOT_PARAMETER_TYPE_CREATE},
		})
		entity := &ParameterTypeEntity{}
		fireback.PopulateInteractively(entity, c, ParameterTypeCommonInteractiveCliFlags)
		if entity, err := ParameterTypeActions.Create(entity, query); err != nil {
			fmt.Println(err.Error())
		} else {
			f, _ := yaml.Marshal(entity)
			fmt.Println(fireback.FormatYamlKeys(string(f)))
		}
	},
}
var ParameterTypeUpdateCmd cli.Command = cli.Command{
	Name:    "update",
	Aliases: []string{"u"},
	Flags:   ParameterTypeCommonCliFlagsOptional,
	Usage:   "Updates entity by passing the parameters",
	Action: func(c *cli.Context) error {
		query := fireback.CommonCliQueryDSLBuilderAuthorize(c, &fireback.SecurityModel{
			ActionRequires: []fireback.PermissionInfo{PERM_ROOT_PARAMETER_TYPE_UPDATE},
		})
		entity := CastParameterTypeFromCli(c)
		if entity, err := ParameterTypeActions.Update(query, entity); err != nil {
			fmt.Println(err.Error())
		} else {
			f, _ := json.MarshalIndent(entity, "", "  ")
			fmt.Println(string(f))
		}
		return nil
	},
}

func (x *ParameterTypeEntity) FromCli(c *cli.Context) *ParameterTypeEntity {
	return CastParameterTypeFromCli(c)
}
func CastParameterTypeFromCli(c *cli.Context) *ParameterTypeEntity {
	template := &ParameterTypeEntity{}
	fireback.HandleXsrc(c, template)
	if c.IsSet("uid") {
		template.UniqueId = c.String("uid")
	}
	if c.IsSet("pid") {
		template.ParentId = fireback.NewStringAutoNull(c.String("pid"))
	}
	if c.IsSet("name") {
		template.Name = c.String("name")
	}
	if c.IsSet("description") {
		template.Description = c.String("description")
	}
	if c.IsSet("binding-key") {
		template.BindingKey = c.String("binding-key")
	}
	return template
}
func ParameterTypeSyncSeederFromFs(fsRef *embed.FS, fileNames []string, q fireback.QueryDSL) {
	fireback.SeederFromFSImport(
		q,
		ParameterTypeActions.Create,
		reflect.ValueOf(&ParameterTypeEntity{}).Elem(),
		fsRef,
		fileNames,
		true,
	)
}
func ParameterTypeSyncSeeders() {
	fireback.SeederFromFSImport(
		fireback.QueryDSL{WorkspaceId: fireback.USER_SYSTEM},
		ParameterTypeActions.Create,
		reflect.ValueOf(&ParameterTypeEntity{}).Elem(),
		parameterTypeSeedersFs,
		[]string{},
		true,
	)
}
func ParameterTypeImportMocks() {
	fireback.SeederFromFSImport(
		fireback.QueryDSL{},
		ParameterTypeActions.Create,
		reflect.ValueOf(&ParameterTypeEntity{}).Elem(),
		&mocks.ViewsFs,
		[]string{},
		false,
	)
}
func ParameterTypeWriteQueryMock(ctx fireback.MockQueryContext) {
	for _, lang := range ctx.Languages {
		itemsPerPage := 9999
		if ctx.ItemsPerPage > 0 {
			itemsPerPage = ctx.ItemsPerPage
		}
		f := fireback.QueryDSL{ItemsPerPage: itemsPerPage, Language: lang, WithPreloads: ctx.WithPreloads, Deep: true}
		items, count, _ := ParameterTypeActions.Query(f)
		result := fireback.QueryEntitySuccessResult(f, items, count)
		fireback.WriteMockDataToFile(lang, "", "ParameterType", result)
	}
}
func ParameterTypesActionQueryString(keyword string, page int) ([]string, *fireback.QueryResultMeta, *fireback.IError) {
	searchFields := []string{
		`unique_id %"{keyword}"%`,
		`name %"{keyword}"%`,
	}
	m := func(item *ParameterTypeEntity) string {
		label := item.UniqueId
		// if item.Name != nil {
		// 	label += " >>> " + *item.Name
		// }
		return label
	}
	query := fireback.QueryStringCastCli(searchFields, keyword, page)
	items, meta, err := ParameterTypeActions.Query(query)
	stringItems := []string{}
	for _, item := range items {
		label := m(item)
		stringItems = append(stringItems, label)
	}
	return stringItems, meta, err
}

var ParameterTypeDevCommands = []cli.Command{
	ParameterTypeWipeCmd,
	{
		Name:  "mock",
		Usage: "Generates mock records based on the entity definition",
		Flags: []cli.Flag{
			&cli.IntFlag{
				Name:  "count",
				Usage: "how many activation key do you need to be generated and stored in database",
				Value: 10,
			},
			&cli.BoolFlag{
				Name:  "batch",
				Usage: "Multiple insert into database mode. Might miss children and relations at the moment",
			},
		},
		Action: func(c *cli.Context) error {
			query := fireback.CommonCliQueryDSLBuilderAuthorize(c, &fireback.SecurityModel{
				ActionRequires: []fireback.PermissionInfo{PERM_ROOT_PARAMETER_TYPE_CREATE},
			})
			if c.Bool("batch") {
				ParameterTypeActionSeederMultiple(query, c.Int("count"))
			} else {
				ParameterTypeActionSeeder(query, c.Int("count"))
			}
			return nil
		},
	},
	{
		Name:    "init",
		Aliases: []string{"i"},
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:  "format",
				Usage: "Format of the export or import file. Can be 'yaml', 'yml', 'json'",
				Value: "yaml",
			},
		},
		Usage: "Creates a basic seeder file for you, based on the definition module we have. You can populate this file as an example",
		Action: func(c *cli.Context) error {
			seed := ParameterTypeActions.SeederInit()
			fireback.CommonInitSeeder(strings.TrimSpace(c.String("format")), seed)
			return nil
		},
	},
	cli.Command{
		Name:  "mlist",
		Usage: "Prints the list of embedded mocks into the app",
		Action: func(c *cli.Context) error {
			if entity, err := fireback.GetSeederFilenames(&mocks.ViewsFs, ""); err != nil {
				fmt.Println(err.Error())
			} else {
				f, _ := json.MarshalIndent(entity, "", "  ")
				fmt.Println(string(f))
			}
			return nil
		},
	},
	cli.Command{
		Name:  "msync",
		Usage: "Tries to sync mocks into the system",
		Action: func(c *cli.Context) error {
			fireback.CommonCliImportEmbedCmd(c,
				ParameterTypeActions.Create,
				reflect.ValueOf(&ParameterTypeEntity{}).Elem(),
				&mocks.ViewsFs,
			)
			return nil
		},
	},
}
var ParameterTypeImportExportCommands = []cli.Command{
	{
		Name:    "validate",
		Aliases: []string{"v"},
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:  "file",
				Usage: "Validates an import file, such as yaml, json, csv, and gives some insights how the after import it would look like",
				Value: "parameter-type-seeder-parameter-type.yml",
				// Uncomment before publish, they need to specify
				// Required: true,
			},
			&cli.StringFlag{
				Name:  "format",
				Usage: "Format of the export or import file. Can be 'yaml', 'yml', 'json'",
				Value: "yaml",
			},
		},
		Usage: "Reads a yaml file containing an array of parameter-types, you can run this to validate if your import file is correct, and how it would look like after import",
		Action: func(c *cli.Context) error {
			data := &[]ParameterTypeEntity{}
			fireback.ReadYamlFile(c.String("file"), data)
			fmt.Println(data)
			return nil
		},
	},
	cli.Command{
		Name:  "slist",
		Usage: "Prints the list of files attached to this module for syncing or bootstrapping project",
		Action: func(c *cli.Context) error {
			if entity, err := fireback.GetSeederFilenames(parameterTypeSeedersFs, ""); err != nil {
				fmt.Println(err.Error())
			} else {
				f, _ := json.MarshalIndent(entity, "", "  ")
				fmt.Println(string(f))
			}
			return nil
		},
	},
	cli.Command{
		Name:  "ssync",
		Usage: "Tries to sync the embedded content into the database, the list could be seen by 'slist' command",
		Action: func(c *cli.Context) error {
			fireback.CommonCliImportEmbedCmd(c,
				ParameterTypeActions.Create,
				reflect.ValueOf(&ParameterTypeEntity{}).Elem(),
				parameterTypeSeedersFs,
			)
			return nil
		},
	},
	cli.Command{
		Name:    "export",
		Aliases: []string{"e"},
		Flags: append(fireback.CommonQueryFlags,
			&cli.StringFlag{
				Name:     "file",
				Usage:    "The address of file you want the csv/yaml/json be exported to",
				Required: true,
			}),
		Usage: "Exports a query results into the csv/yaml/json format",
		Action: func(c *cli.Context) error {
			return fireback.CommonCliExportCmd2(c,
				ParameterTypeEntityStream,
				reflect.ValueOf(&ParameterTypeEntity{}).Elem(),
				c.String("file"),
				&metas.MetaFs,
				"ParameterTypeFieldMap.yml",
				ParameterTypePreloadRelations,
			)
		},
	},
	cli.Command{
		Name: "import",
		Flags: append(
			append(
				fireback.CommonQueryFlags,
				&cli.StringFlag{
					Name:     "file",
					Usage:    "The address of file you want the csv be imported from",
					Required: true,
				}),
			ParameterTypeCommonCliFlagsOptional...,
		),
		Usage: "imports csv/yaml/json file and place it and its children into database",
		Action: func(c *cli.Context) error {
			fireback.CommonCliImportCmdAuthorized(c,
				ParameterTypeActions.Create,
				reflect.ValueOf(&ParameterTypeEntity{}).Elem(),
				c.String("file"),
				&fireback.SecurityModel{
					ActionRequires: []fireback.PermissionInfo{PERM_ROOT_PARAMETER_TYPE_CREATE},
				},
				func() ParameterTypeEntity {
					v := CastParameterTypeFromCli(c)
					return *v
				},
			)
			return nil
		},
	},
}
var ParameterTypeCliCommands []cli.Command = []cli.Command{
	PARAMETER_TYPE_ACTION_QUERY.ToCli(),
	PARAMETER_TYPE_ACTION_TABLE.ToCli(),
	PARAMETER_TYPE_ACTION_PATCH.ToCli(),
	ParameterTypeCreateCmd,
	ParameterTypeAskCmd,
	ParameterTypeCreateInteractiveCmd,
	fireback.GetCommonRemoveQuery(
		reflect.ValueOf(&ParameterTypeEntity{}).Elem(),
		ParameterTypeActions.Remove,
	),
}

func ParameterTypeCliFn() cli.Command {
	commands := append(ParameterTypeImportExportCommands, ParameterTypeCliCommands...)
	if !fireback.GetConfig().Production {
		commands = append(commands, ParameterTypeDevCommands...)
	}
	return cli.Command{
		Name:        "parametertype",
		ShortName:   "pt",
		Description: "ParameterTypes module actions",
		Usage:       `A minimal representation of a type of a parameter.`,
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:  "language",
				Value: "en",
			},
		},
		Subcommands: commands,
	}
}

var PARAMETER_TYPE_ACTION_TABLE = fireback.Module3Action{
	Name:          "table",
	ActionAliases: []string{"t"},
	Flags:         fireback.CommonQueryFlags,
	Description:   "Table formatted queries all of the entities in database based on the standard query format",
	Action:        ParameterTypeActions.Query,
	CliAction: func(c *cli.Context, security *fireback.SecurityModel) error {
		fireback.CommonCliTableCmd2(c,
			ParameterTypeActions.Query,
			security,
			reflect.ValueOf(&ParameterTypeEntity{}).Elem(),
		)
		return nil
	},
}
var PARAMETER_TYPE_ACTION_QUERY = fireback.Module3Action{
	Method: "GET",
	Url:    "/parameter-types",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_PARAMETER_TYPE_QUERY},
	},
	Handlers: []gin.HandlerFunc{
		func(c *gin.Context) {
			qs := &ParameterTypeEntityQs{}
			fireback.HttpQueryEntity(c, ParameterTypeActions.Query, qs)
		},
	},
	Format:         "QUERY",
	Action:         ParameterTypeActions.Query,
	ResponseEntity: &[]ParameterTypeEntity{},
	Out: &fireback.Module3ActionBody{
		Entity: "ParameterTypeEntity",
	},
	CliAction: func(c *cli.Context, security *fireback.SecurityModel) error {
		qs := &ParameterTypeEntityQs{}
		fireback.CommonCliQueryCmd3(
			c,
			ParameterTypeActions.Query,
			security,
			qs,
		)
		return nil
	},
	CliName:       "query",
	Name:          "query",
	ActionAliases: []string{"q"},
	Flags:         append(fireback.CommonQueryFlags, ParameterTypeQsFlags...),
	Description:   "Queries all of the entities in database based on the standard query format (s+)",
}
var PARAMETER_TYPE_ACTION_EXPORT = fireback.Module3Action{
	Method: "GET",
	Url:    "/parameter-types/export",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_PARAMETER_TYPE_QUERY},
	},
	Handlers: []gin.HandlerFunc{
		func(c *gin.Context) {
			fireback.HttpStreamFileChannel(c, ParameterTypeActionExport)
		},
	},
	Format:         "QUERY",
	Action:         ParameterTypeActionExport,
	ResponseEntity: &[]ParameterTypeEntity{},
	Out: &fireback.Module3ActionBody{
		Entity: "ParameterTypeEntity",
	},
}
var PARAMETER_TYPE_ACTION_GET_ONE = fireback.Module3Action{
	Method: "GET",
	Url:    "/parameter-type/:uniqueId",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_PARAMETER_TYPE_QUERY},
	},
	Handlers: []gin.HandlerFunc{
		func(c *gin.Context) {
			fireback.HttpGetEntity(c, ParameterTypeActions.GetOne)
		},
	},
	Format:         "GET_ONE",
	Action:         ParameterTypeActions.GetOne,
	ResponseEntity: &ParameterTypeEntity{},
	Out: &fireback.Module3ActionBody{
		Entity: "ParameterTypeEntity",
	},
}
var PARAMETER_TYPE_ACTION_POST_ONE = fireback.Module3Action{
	Name:          "create",
	ActionAliases: []string{"c"},
	Description:   "Create new parameterType",
	Flags:         ParameterTypeCommonCliFlags,
	Method:        "POST",
	Url:           "/parameter-type",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_PARAMETER_TYPE_CREATE},
	},
	Handlers: []gin.HandlerFunc{
		func(c *gin.Context) {
			fireback.HttpPostEntity(c, ParameterTypeActions.Create)
		},
	},
	CliAction: func(c *cli.Context, security *fireback.SecurityModel) error {
		result, err := fireback.CliPostEntity(c, ParameterTypeActions.Create, security)
		fireback.HandleActionInCli(c, result, err, map[string]map[string]string{})
		if err != nil {
			return err
		}
		return nil
	},
	Action:         ParameterTypeActions.Create,
	Format:         "POST_ONE",
	RequestEntity:  &ParameterTypeEntity{},
	ResponseEntity: &ParameterTypeEntity{},
	Out: &fireback.Module3ActionBody{
		Entity: "ParameterTypeEntity",
	},
	In: &fireback.Module3ActionBody{
		Entity: "ParameterTypeEntity",
	},
}
var PARAMETER_TYPE_ACTION_PATCH = fireback.Module3Action{
	Name:          "update",
	ActionAliases: []string{"u"},
	Flags:         ParameterTypeCommonCliFlagsOptional,
	Method:        "PATCH",
	Url:           "/parameter-type",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_PARAMETER_TYPE_UPDATE},
	},
	Handlers: []gin.HandlerFunc{
		func(c *gin.Context) {
			fireback.HttpUpdateEntity(c, ParameterTypeActions.Update)
		},
	},
	Action:         ParameterTypeActions.Update,
	RequestEntity:  &ParameterTypeEntity{},
	ResponseEntity: &ParameterTypeEntity{},
	Format:         "PATCH_ONE",
	Out: &fireback.Module3ActionBody{
		Entity: "ParameterTypeEntity",
	},
	In: &fireback.Module3ActionBody{
		Entity: "ParameterTypeEntity",
	},
	Description: "Update the ParameterType entity by unique id",
	CliName:     "update",
	CliAction: func(c *cli.Context, security *fireback.SecurityModel) error {
		result, err := fireback.CliPatchEntity(c, ParameterTypeActions.Update, security)
		fireback.HandleActionInCli(c, result, err, map[string]map[string]string{})
		if err != nil {
			return err
		}
		return nil
	},
}
var PARAMETER_TYPE_ACTION_PATCH_BULK = fireback.Module3Action{
	Method: "PATCH",
	Url:    "/parameter-types",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_PARAMETER_TYPE_UPDATE},
	},
	Handlers: []gin.HandlerFunc{
		func(c *gin.Context) {
			fireback.HttpUpdateEntities(c, ParameterTypeActionBulkUpdate)
		},
	},
	Action:         ParameterTypeActionBulkUpdate,
	Format:         "PATCH_BULK",
	RequestEntity:  &fireback.BulkRecordRequest[ParameterTypeEntity]{},
	ResponseEntity: &fireback.BulkRecordRequest[ParameterTypeEntity]{},
	Out: &fireback.Module3ActionBody{
		Entity: "ParameterTypeEntity",
	},
	In: &fireback.Module3ActionBody{
		Entity: "ParameterTypeEntity",
	},
}
var PARAMETER_TYPE_ACTION_DELETE = fireback.Module3Action{
	Method: "DELETE",
	Url:    "/parameter-type",
	Format: "DELETE_DSL",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_PARAMETER_TYPE_DELETE},
	},
	Handlers: []gin.HandlerFunc{
		func(c *gin.Context) {
			fireback.HttpRemoveEntity(c, ParameterTypeActions.Remove)
		},
	},
	Action:         ParameterTypeActions.Remove,
	RequestEntity:  &fireback.DeleteRequest{},
	ResponseEntity: &fireback.DeleteResponse{},
	TargetEntity:   &ParameterTypeEntity{},
}

/**
 *	Override this function on ParameterTypeEntityHttp.go,
 *	In order to add your own http
 **/
var AppendParameterTypeRouter = func(r *[]fireback.Module3Action) {}

func GetParameterTypeModule3Actions() []fireback.Module3Action {
	routes := []fireback.Module3Action{
		PARAMETER_TYPE_ACTION_QUERY,
		PARAMETER_TYPE_ACTION_EXPORT,
		PARAMETER_TYPE_ACTION_GET_ONE,
		PARAMETER_TYPE_ACTION_POST_ONE,
		PARAMETER_TYPE_ACTION_PATCH,
		PARAMETER_TYPE_ACTION_PATCH_BULK,
		PARAMETER_TYPE_ACTION_DELETE,
	}
	// Append user defined functions
	AppendParameterTypeRouter(&routes)
	return routes
}

var PERM_ROOT_PARAMETER_TYPE = fireback.PermissionInfo{
	CompleteKey: "root.modules.product.parameter-type.*",
	Name:        "Entire parameter type actions (*)",
	Description: "",
}
var PERM_ROOT_PARAMETER_TYPE_DELETE = fireback.PermissionInfo{
	CompleteKey: "root.modules.product.parameter-type.delete",
	Name:        "Delete parameter type",
	Description: "",
}
var PERM_ROOT_PARAMETER_TYPE_CREATE = fireback.PermissionInfo{
	CompleteKey: "root.modules.product.parameter-type.create",
	Name:        "Create parameter type",
	Description: "",
}
var PERM_ROOT_PARAMETER_TYPE_UPDATE = fireback.PermissionInfo{
	CompleteKey: "root.modules.product.parameter-type.update",
	Name:        "Update parameter type",
	Description: "",
}
var PERM_ROOT_PARAMETER_TYPE_QUERY = fireback.PermissionInfo{
	CompleteKey: "root.modules.product.parameter-type.query",
	Name:        "Query parameter type",
	Description: "",
}
var ALL_PARAMETER_TYPE_PERMISSIONS = []fireback.PermissionInfo{
	PERM_ROOT_PARAMETER_TYPE_DELETE,
	PERM_ROOT_PARAMETER_TYPE_CREATE,
	PERM_ROOT_PARAMETER_TYPE_UPDATE,
	PERM_ROOT_PARAMETER_TYPE_QUERY,
	PERM_ROOT_PARAMETER_TYPE,
}

func NewParameterTypeCreatedEvent(
	payload *ParameterTypeEntity,
	query *fireback.QueryDSL,
) (*fireback.Event, error) {
	event := &fireback.Event{
		Name:    "ParameterTypeCreated",
		Payload: payload,
		Security: &fireback.SecurityModel{
			ActionRequires: []fireback.PermissionInfo{
				PERM_ROOT_PARAMETER_TYPE_QUERY,
			},
		},
		CacheKey: "*product.ParameterTypeEntity",
	}
	// Apply the source of the event based on querydsl
	fireback.ApplyQueryDslContextToEvent(event, *query)
	return event, nil
}
func NewParameterTypeUpdatedEvent(
	payload *ParameterTypeEntity,
	query *fireback.QueryDSL,
) (*fireback.Event, error) {
	event := &fireback.Event{
		Name:    "ParameterTypeUpdated",
		Payload: payload,
		Security: &fireback.SecurityModel{
			ActionRequires: []fireback.PermissionInfo{
				PERM_ROOT_PARAMETER_TYPE_QUERY,
			},
		},
		CacheKey: "*product.ParameterTypeEntity",
	}
	// Apply the source of the event based on querydsl
	fireback.ApplyQueryDslContextToEvent(event, *query)
	return event, nil
}

var ParameterTypeEntityBundle = fireback.EntityBundle{
	Permissions: ALL_PARAMETER_TYPE_PERMISSIONS,
	// Cli command has been exluded, since we use module to wrap all the entities
	// to be more easier to wrap up.
	// Create your own bundle if you need with Cli
	//CliCommands: []cli.Command{
	//	ParameterTypeCliFn(),
	//},
	Actions:      GetParameterTypeModule3Actions(),
	MockProvider: ParameterTypeImportMocks,
	AutoMigrationEntities: []interface{}{
		&ParameterTypeEntity{},
		&ParameterTypeEntityPolyglot{},
	},
	MigrationScripts: []fireback.MigrationScript{},
}
