package product

/*
*	Generated by fireback 1.2.4
*	Written by Ali Torabi.
*	Checkout the repository for licenses and contribution: https://github.com/torabian/fireback
 */
import (
	"embed"
	"encoding/json"
	"fmt"
	"github.com/gin-gonic/gin"
	jsoniter "github.com/json-iterator/go"
	metas "github.com/myorg/mynewmicroservice/modules/product/metas"
	mocks "github.com/myorg/mynewmicroservice/modules/product/mocks/Parameter"
	seeders "github.com/myorg/mynewmicroservice/modules/product/seeders/Parameter"
	"github.com/schollz/progressbar/v3"
	"github.com/torabian/fireback/modules/fireback"
	"github.com/urfave/cli"
	"gopkg.in/yaml.v2"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"log"
	reflect "reflect"
	"strings"
	"time"
)

var parameterSeedersFs = &seeders.ViewsFs

func ResetParameterSeeders(fs *embed.FS) {
	parameterSeedersFs = fs
}

type ParameterEntityQs struct {
	Name          fireback.QueriableField `cli:"name" table:"parameter" typeof:"string" column:"name" qs:"name"`
	Description   fireback.QueriableField `cli:"description" table:"parameter" typeof:"string" column:"description" qs:"description"`
	ParameterType fireback.QueriableField `cli:"parameter-type" table:"parameter" typeof:"one" column:"parameter_type" qs:"parameterType"`
}

func (x *ParameterEntityQs) GetQuery() string {
	return fireback.GenerateQueryStringStyle(reflect.ValueOf(x), "")
}

var ParameterQsFlags = []cli.Flag{
	&cli.StringFlag{
		Name:  "name",
		Usage: "Name of the parameter which is gonna be available in category search. e.g. Color, Length, Width",
	},
	&cli.StringFlag{
		Name:  "description",
		Usage: "Describe the parameter so selection is easier for content management.",
	},
	&cli.StringFlag{
		Name:  "parameter-type",
		Usage: "The type of the parameter in terms of data structure.",
	},
}

type ParameterEntity struct {
	// Defines the visibility of the record in the table.
	// Visibility is a detailed topic, you can check all of the visibility values in fireback/visibility.go
	// by default, visibility of record are 0, means they are protected by the workspace
	// which are being created, and visible to every member of the workspace
	Visibility fireback.String `json:"visibility,omitempty" yaml:"visibility,omitempty" xml:"visibility,omitempty"`
	// The unique-id of the workspace which content belongs to. Upon creation this will be designated
	// to the selected workspace by user, if they have write access. You can change this value
	// or prevent changes to it manually (on root features for example modifying other workspace)
	WorkspaceId fireback.String `json:"workspaceId,omitempty" xml:"workspaceId,omitempty" yaml:"workspaceId,omitempty"`
	// The unique-id of the parent table, which this record is being linked to.
	// used internally for making relations in fireback, generally does not need manual changes
	// or modification by the developer or user. For example, if you have a object inside an object
	// the unique-id of the parent will be written in the child.
	LinkerId fireback.String `json:"linkerId,omitempty" xml:"linkerId,omitempty" yaml:"linkerId,omitempty"`
	// Used for recursive or parent-child operations. Some tables, are having nested relations,
	// and this field makes the table self refrenceing. ParentId needs to exist in the table before
	// creating of modifying a record.
	ParentId fireback.String `json:"parentId,omitempty" xml:"parentId,omitempty" yaml:"parentId,omitempty"`
	// Makes a field deletable. Some records should not be deletable at all.
	// default it's true.
	IsDeletable *bool `json:"isDeletable,omitempty" xml:"isDeletable,omitempty" yaml:"isDeletable,omitempty" gorm:"default:true"`
	// Makes a field updatable. Some records should not be updatable at all.
	// default it's true.
	IsUpdatable *bool `json:"isUpdatable,omitempty" xml:"isUpdatable,omitempty" yaml:"isUpdatable,omitempty" gorm:"default:true"`
	// The unique-id of the user which is creating the record, or the record belongs to.
	// Administration might want to change this to any user, by default Fireback fills
	// it to the current authenticated user.
	UserId fireback.String `json:"userId,omitempty" xml:"userId,omitempty" yaml:"userId,omitempty"`
	// General mechanism to rank the elements. From code perspective, it's just a number,
	// but you can sort it based on any logic for records to make a ranking, sorting.
	// they should not be unique across a table.
	Rank fireback.Int64 `json:"rank,omitempty" yaml:"rank,omitempty" xml:"rank,omitempty" gorm:"type:int;name:rank"`
	// Primary numeric key in the database. This value is not meant to be exported to public
	// or be used to access data at all. Rather a mechanism of indexing columns internally
	// or cursor pagination in future releases of fireback, or better search performance.
	ID uint `gorm:"primaryKey;autoIncrement" json:"-" yaml:"-" xml:"-"`
	// Unique id of the record across the table. This value will be accessed from public APIs,
	// and many other places intead of numeric ID property.
	// Upon generation, a UUID automatically is being assigned, and if user has specified the
	// Unique id in the post body, it will be used. This mechanism allows to manage unsaved
	// content on front-end much easier than requiring parent to exists first.
	UniqueId string `json:"uniqueId,omitempty" xml:"uniqueId,omitempty" gorm:"unique;not null;size:100;" yaml:"uniqueId,omitempty"`
	// The time that the record has been updated in datetime.
	// the field will be automatically populated by gorm orm.
	UpdatedAt *time.Time `json:"updatedAt,omitempty" xml:"updatedAt,omitempty" yaml:"updatedAt,omitempty"`
	// The time that the record has been created in datetime.
	// the field will be automatically populated by gorm orm.
	CreatedAt *time.Time `json:"createdAt,omitempty" xml:"createdAt,omitempty" yaml:"createdAt,omitempty"`
	// The time that the record has been deleted softly (means the data still exists in database, but no longer visible to any feature) in nano datatime
	// you need to make sure check this field if writing custom sql queries.
	// the field will be automatically populated by gorm orm.
	DeletedAt *time.Time `json:"deletedAt,omitempty" xml:"deletedAt,omitempty" yaml:"deletedAt,omitempty"`
	// Record creation date time formatting based on locale of the headers, or other
	// possible factors.
	CreatedFormatted string `json:"createdFormatted,omitempty" xml:"createdFormatted,omitempty" yaml:"createdFormatted,omitempty" sql:"-" gorm:"-"`
	// Record update date time formatting based on locale of the headers, or other
	// possible factors.
	UpdatedFormatted string `json:"updatedFormatted,omitempty" xml:"updatedFormatted,omitempty" yaml:"updatedFormatted,omitempty" sql:"-" gorm:"-"`
	// Name of the parameter which is gonna be available in category search. e.g. Color, Length, Width
	Name string `json:"name" xml:"name" yaml:"name"  validate:"required"        translate:"true"  `
	// Describe the parameter so selection is easier for content management.
	Description string `json:"description" xml:"description" yaml:"description"        translate:"true"  `
	// The type of the parameter in terms of data structure.
	ParameterType   *ParameterTypeEntity       `json:"parameterType" xml:"parameterType" yaml:"parameterType"    gorm:"foreignKey:ParameterTypeId;references:UniqueId"      `
	ParameterTypeId fireback.String            `json:"parameterTypeId" yaml:"parameterTypeId" xml:"parameterTypeId"   validate:"required" `
	Translations    []*ParameterEntityPolyglot `json:"translations,omitempty" xml:"translations,omitempty" yaml:"translations,omitempty" gorm:"foreignKey:LinkerId;references:UniqueId;constraint:OnDelete:CASCADE"`
	Children        []*ParameterEntity         `csv:"-" gorm:"-" sql:"-" json:"children,omitempty" xml:"children,omitempty"  yaml:"children,omitempty"`
	LinkedTo        *ParameterEntity           `csv:"-" yaml:"-" gorm:"-" json:"-" sql:"-" xml:"-"`
}

func ParameterEntityStream(q fireback.QueryDSL) (chan []*ParameterEntity, *fireback.QueryResultMeta, *fireback.IError) {
	cn := make(chan []*ParameterEntity)
	q.ItemsPerPage = 50
	q.StartIndex = 0
	_, qrm, err := ParameterActions.Query(q)
	if err != nil {
		return nil, nil, err
	}
	go func() {
		defer close(cn)
		for i := 0; i <= int(qrm.TotalAvailableItems)-1; i++ {
			items, _, _ := ParameterActions.Query(q)
			i += q.ItemsPerPage
			q.StartIndex = i
			cn <- items
		}
	}()
	return cn, qrm, nil
}

type ParameterEntityList struct {
	Items []*ParameterEntity
}

func NewParameterEntityList(items []*ParameterEntity) *ParameterEntityList {
	return &ParameterEntityList{
		Items: items,
	}
}
func (x *ParameterEntityList) Json() string {
	if x != nil {
		str, _ := json.MarshalIndent(x, "", "  ")
		return (string(str))
	}
	return ""
}
func (x *ParameterEntityList) ToTree() *fireback.TreeOperation[ParameterEntity] {
	return fireback.NewTreeOperation(
		x.Items,
		func(t *ParameterEntity) string {
			if !t.ParentId.Valid {
				return ""
			}
			return t.ParentId.String
		},
		func(t *ParameterEntity) string {
			return t.UniqueId
		},
	)
}

var ParameterPreloadRelations []string = []string{}

type parameterActionsSig struct {
	Update         func(query fireback.QueryDSL, dto *ParameterEntity) (*ParameterEntity, *fireback.IError)
	Create         func(dto *ParameterEntity, query fireback.QueryDSL) (*ParameterEntity, *fireback.IError)
	Upsert         func(dto *ParameterEntity, query fireback.QueryDSL) (*ParameterEntity, *fireback.IError)
	SeederInit     func() *ParameterEntity
	Remove         func(query fireback.QueryDSL) (int64, *fireback.IError)
	MultiInsert    func(dtos []*ParameterEntity, query fireback.QueryDSL) ([]*ParameterEntity, *fireback.IError)
	GetOne         func(query fireback.QueryDSL) (*ParameterEntity, *fireback.IError)
	GetByWorkspace func(query fireback.QueryDSL) (*ParameterEntity, *fireback.IError)
	Query          func(query fireback.QueryDSL) ([]*ParameterEntity, *fireback.QueryResultMeta, *fireback.IError)
}

var ParameterActions parameterActionsSig = parameterActionsSig{
	Update:         ParameterActionUpdateFn,
	Create:         ParameterActionCreateFn,
	Upsert:         ParameterActionUpsertFn,
	Remove:         ParameterActionRemoveFn,
	SeederInit:     ParameterActionSeederInitFn,
	MultiInsert:    ParameterMultiInsertFn,
	GetOne:         ParameterActionGetOneFn,
	GetByWorkspace: ParameterActionGetByWorkspaceFn,
	Query:          ParameterActionQueryFn,
}

func ParameterActionUpsertFn(dto *ParameterEntity, query fireback.QueryDSL) (*ParameterEntity, *fireback.IError) {
	return nil, nil
}

var PARAMETER_EVENT_CREATED = "parameter.created"
var PARAMETER_EVENT_UPDATED = "parameter.updated"
var PARAMETER_EVENT_DELETED = "parameter.deleted"
var PARAMETER_EVENTS = []string{
	PARAMETER_EVENT_CREATED,
	PARAMETER_EVENT_UPDATED,
	PARAMETER_EVENT_DELETED,
}

type ParameterFieldMap struct {
	Name          fireback.TranslatedString `yaml:"name"`
	Description   fireback.TranslatedString `yaml:"description"`
	ParameterType fireback.TranslatedString `yaml:"parameterType"`
}

var ParameterEntityMetaConfig map[string]int64 = map[string]int64{}
var ParameterEntityJsonSchema = fireback.ExtractEntityFields(reflect.ValueOf(&ParameterEntity{}))

type ParameterEntityPolyglot struct {
	LinkerId    string `gorm:"uniqueId;not null;size:100;" json:"linkerId,omitempty" yaml:"linkerId,omitempty" xml:"linkerId,omitempty"`
	LanguageId  string `gorm:"uniqueId;not null;size:100;" json:"languageId,omitempty" xml:"languageId,omitempty" yaml:"languageId,omitempty"`
	Name        string `yaml:"name,omitempty" xml:"name,omitempty" json:"name,omitempty"`
	Description string `yaml:"description,omitempty" xml:"description,omitempty" json:"description,omitempty"`
}

func entityParameterFormatter(dto *ParameterEntity, query fireback.QueryDSL) {
	if dto == nil {
		return
	}
}
func ParameterActionSeederMultiple(query fireback.QueryDSL, count int) {
	successInsert := 0
	failureInsert := 0
	batchSize := 100
	bar := progressbar.Default(int64(count))
	// Collect entities in batches
	var entitiesBatch []*ParameterEntity
	for i := 1; i <= count; i++ {
		entity := ParameterActions.SeederInit()
		entitiesBatch = append(entitiesBatch, entity)
		// When batch size is reached, perform the batch insert
		if len(entitiesBatch) == batchSize || i == count {
			// Insert batch
			_, err := ParameterActions.MultiInsert(entitiesBatch, query)
			if err == nil {
				successInsert += len(entitiesBatch)
			} else {
				fmt.Println(err)
				failureInsert += len(entitiesBatch)
			}
			// Clear the batch after insert
			entitiesBatch = nil
		}
		bar.Add(1)
	}
	fmt.Println("Success", successInsert, "Failure", failureInsert)
}
func ParameterActionSeeder(query fireback.QueryDSL, count int) {
	successInsert := 0
	failureInsert := 0
	bar := progressbar.Default(int64(count))
	for i := 1; i <= count; i++ {
		entity := ParameterActions.SeederInit()
		_, err := ParameterActions.Create(entity, query)
		if err == nil {
			successInsert++
		} else {
			fmt.Println(err)
			failureInsert++
		}
		bar.Add(1)
	}
	fmt.Println("Success", successInsert, "Failure", failureInsert)
}
func (x *ParameterEntity) GetNameTranslated(language string) string {
	if x.Translations != nil && len(x.Translations) > 0 {
		for _, item := range x.Translations {
			if item.LanguageId == language {
				return item.Name
			}
		}
	}
	return ""
}
func (x *ParameterEntity) GetDescriptionTranslated(language string) string {
	if x.Translations != nil && len(x.Translations) > 0 {
		for _, item := range x.Translations {
			if item.LanguageId == language {
				return item.Description
			}
		}
	}
	return ""
}
func (x *ParameterEntity) Seeder() string {
	obj := ParameterActions.SeederInit()
	v, _ := json.MarshalIndent(obj, "", "  ")
	return string(v)
}
func ParameterActionSeederInitFn() *ParameterEntity {
	entity := &ParameterEntity{}
	return entity
}
func ParameterAssociationCreate(dto *ParameterEntity, query fireback.QueryDSL) error {
	return nil
}

/**
* These kind of content are coming from another entity, which is indepndent module
* If we want to create them, we need to do it before. This is not association.
**/
func ParameterRelationContentCreate(dto *ParameterEntity, query fireback.QueryDSL) error {
	return nil
}
func ParameterRelationContentUpdate(dto *ParameterEntity, query fireback.QueryDSL) error {
	return nil
}
func ParameterPolyglotUpdateHandler(dto *ParameterEntity, query fireback.QueryDSL) {
	if dto == nil {
		return
	}
	fireback.PolyglotUpdateHandler(dto, &ParameterEntityPolyglot{}, query)
}

/**
 * This will be validating your entity fully. Important note is that, you add validate:* tag
 * in your entity, it will automatically work here. For slices inside entity, make sure you add
 * extra line of AppendSliceErrors, otherwise they won't be detected
 */
func ParameterValidator(dto *ParameterEntity, isPatch bool) *fireback.IError {
	err := fireback.CommonStructValidatorPointer(dto, isPatch)
	return err
}

// Creates a set of natural language queries, which can be used with
// AI tools to create content or help with some tasks
var ParameterAskCmd cli.Command = cli.Command{
	Name:  "nlp",
	Usage: "Set of natural language queries which helps creating content or data",
	Subcommands: []cli.Command{
		{
			Name:  "sample",
			Usage: "Asks for generating sample by giving an example data",
			Flags: []cli.Flag{
				&cli.StringFlag{
					Name:  "format",
					Usage: "Format of the export or import file. Can be 'yaml', 'yml', 'json'",
					Value: "yaml",
				},
				&cli.IntFlag{
					Name:  "count",
					Usage: "How many samples to ask",
					Value: 30,
				},
			},
			Action: func(c *cli.Context) error {
				v := &ParameterEntity{}
				format := c.String("format")
				request := "\033[1m" + `
I need you to create me an array of exact signature as the example given below,
with at least ` + fmt.Sprint(c.String("count")) + ` items, mock the content with few words, and guess the possible values
based on the common sense. I need the output to be a valid ` + format + ` file.
Make sure you wrap the entire array in 'items' field. Also before that, I provide some explanation of each field:
Name: (type: string) Description: Name of the parameter which is gonna be available in category search. e.g. Color, Length, Width
Description: (type: string) Description: Describe the parameter so selection is easier for content management.
ParameterType: (type: one) Description: The type of the parameter in terms of data structure.
And here is the actual object signature:
` + v.Seeder() + `
`
				fmt.Println(request)
				return nil
			},
		},
	},
}

func ParameterEntityPreSanitize(dto *ParameterEntity, query fireback.QueryDSL) {
}
func ParameterEntityBeforeCreateAppend(dto *ParameterEntity, query fireback.QueryDSL) {
	if dto.UniqueId == "" {
		dto.UniqueId = fireback.UUID()
	}
	dto.WorkspaceId = fireback.NewString(query.WorkspaceId)
	dto.UserId = fireback.NewString(query.UserId)
	ParameterRecursiveAddUniqueId(dto, query)
}
func ParameterRecursiveAddUniqueId(dto *ParameterEntity, query fireback.QueryDSL) {
}

/*
*
	Batch inserts, do not have all features that create
	operation does. Use it with unnormalized content,
	or read the source code carefully.
  This is not marked as an action, because it should not be available publicly
  at this moment.
*
*/
func ParameterMultiInsertFn(dtos []*ParameterEntity, query fireback.QueryDSL) ([]*ParameterEntity, *fireback.IError) {
	if len(dtos) > 0 {
		for index := range dtos {
			ParameterEntityPreSanitize(dtos[index], query)
			ParameterEntityBeforeCreateAppend(dtos[index], query)
		}
		var dbref *gorm.DB = nil
		if query.Tx == nil {
			dbref = fireback.GetDbRef()
		} else {
			dbref = query.Tx
		}
		query.Tx = dbref
		err := dbref.Create(&dtos).Error
		if err != nil {
			return nil, fireback.GormErrorToIError(err)
		}
	}
	return dtos, nil
}
func ParameterActionBatchCreateFn(dtos []*ParameterEntity, query fireback.QueryDSL) ([]*ParameterEntity, *fireback.IError) {
	if dtos != nil && len(dtos) > 0 {
		items := []*ParameterEntity{}
		for _, item := range dtos {
			s, err := ParameterActions.Create(item, query)
			if err != nil {
				return nil, err
			}
			items = append(items, s)
		}
		return items, nil
	}
	return dtos, nil
}
func ParameterDeleteEntireChildren(query fireback.QueryDSL, dto *ParameterEntity) *fireback.IError {
	// intentionally removed this. It's hard to implement it, and probably wrong without
	// proper on delete cascade
	return nil
}
func ParameterActionCreateFn(dto *ParameterEntity, query fireback.QueryDSL) (*ParameterEntity, *fireback.IError) {
	// 1. Validate always
	if iError := ParameterValidator(dto, false); iError != nil {
		return nil, iError
	}
	// 1.5 Sanitize the content coming of the front-end
	ParameterEntityPreSanitize(dto, query)
	// 2. Append the necessary information about user, workspace
	ParameterEntityBeforeCreateAppend(dto, query)
	// 3. Create other entities if we want select from them
	ParameterRelationContentCreate(dto, query)
	// 4. Create the entity
	var dbref *gorm.DB = nil
	if query.Tx == nil {
		dbref = fireback.GetDbRef()
	} else {
		dbref = query.Tx
	}
	query.Tx = dbref
	err := dbref.Create(&dto).Error
	if err != nil {
		err := fireback.GormErrorToIError(err)
		return nil, err
	}
	// 5. Create sub entities, objects or arrays, association to other entities
	ParameterAssociationCreate(dto, query)
	// 6. Fire the event into system
	actionEvent, eventErr := NewParameterCreatedEvent(dto, &query)
	if actionEvent != nil && eventErr == nil {
		fireback.GetEventBusInstance().FireEvent(query, *actionEvent)
	} else {
		log.Default().Panicln("Creating event has failed for %v", dto)
	}
	/*
		event.MustFire(PARAMETER_EVENT_CREATED, event.M{
			"entity":   dto,
			"entityKey": fireback.GetTypeString(&ParameterEntity{}),
			"target":   "workspace",
			"unqiueId": query.WorkspaceId,
		})
	*/
	return dto, nil
}
func ParameterActionGetOneFn(query fireback.QueryDSL) (*ParameterEntity, *fireback.IError) {
	refl := reflect.ValueOf(&ParameterEntity{})
	item, err := fireback.GetOneEntity[ParameterEntity](query, refl)
	entityParameterFormatter(item, query)
	return item, err
}
func ParameterActionGetByWorkspaceFn(query fireback.QueryDSL) (*ParameterEntity, *fireback.IError) {
	refl := reflect.ValueOf(&ParameterEntity{})
	item, err := fireback.GetOneByWorkspaceEntity[ParameterEntity](query, refl)
	entityParameterFormatter(item, query)
	return item, err
}
func ParameterActionQueryFn(query fireback.QueryDSL) ([]*ParameterEntity, *fireback.QueryResultMeta, *fireback.IError) {
	refl := reflect.ValueOf(&ParameterEntity{})
	items, meta, err := fireback.QueryEntitiesPointer[ParameterEntity](query, refl)
	for _, item := range items {
		entityParameterFormatter(item, query)
	}
	return items, meta, err
}

var parameterMemoryItems []*ParameterEntity = []*ParameterEntity{}

func ParameterEntityIntoMemory() {
	q := fireback.QueryDSL{
		ItemsPerPage: 500,
		StartIndex:   0,
	}
	_, qrm, _ := ParameterActions.Query(q)
	for i := 0; i <= int(qrm.TotalAvailableItems)-1; i++ {
		items, _, _ := ParameterActions.Query(q)
		parameterMemoryItems = append(parameterMemoryItems, items...)
		i += q.ItemsPerPage
		q.StartIndex = i
	}
}
func ParameterMemGet(id uint) *ParameterEntity {
	for _, item := range parameterMemoryItems {
		if item.ID == id {
			return item
		}
	}
	return nil
}
func ParameterMemJoin(items []uint) []*ParameterEntity {
	res := []*ParameterEntity{}
	for _, item := range items {
		v := ParameterMemGet(item)
		if v != nil {
			res = append(res, v)
		}
	}
	return res
}
func ParameterUpdateExec(dbref *gorm.DB, query fireback.QueryDSL, fields *ParameterEntity) (*ParameterEntity, *fireback.IError) {
	uniqueId := fields.UniqueId
	query.TriggerEventName = PARAMETER_EVENT_UPDATED
	ParameterEntityPreSanitize(fields, query)
	var item ParameterEntity
	var itemRefetched ParameterEntity
	// If the entity is distinct by workspace, then the Query.WorkspaceId
	// which is selected is being used as the condition for create or update
	// if not, the unique Id is being used
	cond2 := &ParameterEntity{UniqueId: uniqueId}
	q := dbref.
		Where(cond2).
		FirstOrCreate(&item)
	err := q.UpdateColumns(fields).Error
	if err != nil {
		return nil, fireback.GormErrorToIError(err)
	}
	query.Tx = dbref
	ParameterRelationContentUpdate(fields, query)
	ParameterPolyglotUpdateHandler(fields, query)
	if ero := ParameterDeleteEntireChildren(query, fields); ero != nil {
		return nil, ero
	}
	// @meta(update has many)
	err = dbref.
		Preload(clause.Associations).
		Where(&ParameterEntity{UniqueId: uniqueId}).
		First(&itemRefetched).Error
	if err != nil {
		return nil, fireback.GormErrorToIError(err)
	}
	actionEvent, eventErr := NewParameterUpdatedEvent(fields, &query)
	if actionEvent != nil && eventErr == nil {
		fireback.GetEventBusInstance().FireEvent(query, *actionEvent)
	} else {
		log.Default().Panicln("Updating event has failed for %v", fields)
	}
	/*
	   event.MustFire(query.TriggerEventName, event.M{
	     "entity":   &item,
	     "target":   "workspace",
	     "unqiueId": query.WorkspaceId,
	   })*/
	return &itemRefetched, nil
}
func ParameterActionUpdateFn(query fireback.QueryDSL, fields *ParameterEntity) (*ParameterEntity, *fireback.IError) {
	if fields == nil {
		return nil, fireback.Create401Error(&fireback.FirebackMessages.BodyIsMissing, []string{})
	}
	// 1. Validate always
	if iError := ParameterValidator(fields, true); iError != nil {
		return nil, iError
	}
	// Let's not add this. I am not sure of the consequences
	// ParameterRecursiveAddUniqueId(fields, query)
	var dbref *gorm.DB = nil
	if query.Tx == nil {
		dbref = fireback.GetDbRef()
		var item *ParameterEntity
		vf := dbref.Transaction(func(tx *gorm.DB) error {
			dbref = tx
			var err *fireback.IError
			item, err = ParameterUpdateExec(dbref, query, fields)
			if err == nil {
				return nil
			} else {
				return err
			}
		})
		return item, fireback.CastToIError(vf)
	} else {
		dbref = query.Tx
		return ParameterUpdateExec(dbref, query, fields)
	}
}

var ParameterWipeCmd cli.Command = cli.Command{
	Name:  "wipe",
	Usage: "Wipes entire parameters ",
	Action: func(c *cli.Context) error {
		query := fireback.CommonCliQueryDSLBuilderAuthorize(c, &fireback.SecurityModel{
			ActionRequires: []fireback.PermissionInfo{PERM_ROOT_PARAMETER_DELETE},
		})
		count, _ := ParameterActionWipeClean(query)
		fmt.Println("Removed", count, "of entities")
		return nil
	},
}

func ParameterActionRemoveFn(query fireback.QueryDSL) (int64, *fireback.IError) {
	refl := reflect.ValueOf(&ParameterEntity{})
	query.ActionRequires = []fireback.PermissionInfo{PERM_ROOT_PARAMETER_DELETE}
	return fireback.RemoveEntity[ParameterEntity](query, refl)
}
func ParameterActionWipeClean(query fireback.QueryDSL) (int64, error) {
	var err error
	var count int64 = 0
	{
		subCount, subErr := fireback.WipeCleanEntity[ParameterEntity]()
		if subErr != nil {
			fmt.Println("Error while wiping 'ParameterEntity'", subErr)
			return count, subErr
		} else {
			count += subCount
		}
	}
	return count, err
}
func ParameterActionBulkUpdate(
	query fireback.QueryDSL, dto *fireback.BulkRecordRequest[ParameterEntity]) (
	*fireback.BulkRecordRequest[ParameterEntity], *fireback.IError,
) {
	result := []*ParameterEntity{}
	err := fireback.GetDbRef().Transaction(func(tx *gorm.DB) error {
		query.Tx = tx
		for _, record := range dto.Records {
			item, err := ParameterActions.Update(query, record)
			if err != nil {
				return err
			} else {
				result = append(result, item)
			}
		}
		return nil
	})
	if err == nil {
		return dto, nil
	}
	return nil, err.(*fireback.IError)
}
func (x *ParameterEntity) Json() string {
	if x != nil {
		str, _ := json.MarshalIndent(x, "", "  ")
		return (string(str))
	}
	return ""
}

var ParameterEntityMeta = fireback.TableMetaData{
	EntityName:    "Parameter",
	ExportKey:     "parameters",
	TableNameInDb: "parameter_entities",
	EntityObject:  &ParameterEntity{},
	ExportStream:  ParameterActionExportT,
	ImportQuery:   ParameterActionImport,
}

func ParameterActionExport(
	query fireback.QueryDSL,
) (chan []byte, *fireback.IError) {
	return fireback.YamlExporterChannel[ParameterEntity](query, ParameterActions.Query, ParameterPreloadRelations)
}
func ParameterActionExportT(
	query fireback.QueryDSL,
) (chan []interface{}, *fireback.IError) {
	return fireback.YamlExporterChannelT[ParameterEntity](query, ParameterActions.Query, ParameterPreloadRelations)
}
func ParameterActionImport(
	dto interface{}, query fireback.QueryDSL,
) *fireback.IError {
	var json = jsoniter.ConfigCompatibleWithStandardLibrary
	var content ParameterEntity
	cx, err2 := json.Marshal(dto)
	if err2 != nil {
		return fireback.Create401Error(&fireback.FirebackMessages.InvalidContent, []string{})
	}
	json.Unmarshal(cx, &content)
	_, err := ParameterActions.Create(&content, query)
	return err
}

var ParameterCommonCliFlags = []cli.Flag{
	&cli.StringFlag{
		Name:  "x-accept",
		Usage: "Return type of the the content, such as json or yaml",
	},
	&cli.StringFlag{
		Name:     "wid",
		Required: false,
		Usage:    "Provide workspace id, if you want to change the data workspace",
	},
	&cli.StringFlag{
		Name:     "uid",
		Required: false,
		Usage:    "Unique Id - external unique hash to query entity",
	},
	&cli.StringFlag{
		Name:     "pid",
		Required: false,
		Usage:    " Parent record id of the same type",
	},
	&cli.StringFlag{
		Name:     "name",
		Required: true,
		Usage:    `Name of the parameter which is gonna be available in category search. e.g. Color, Length, Width (string)`,
	},
	&cli.StringFlag{
		Name:     "description",
		Required: false,
		Usage:    `Describe the parameter so selection is easier for content management. (string)`,
	},
	&cli.StringFlag{
		Name:     "parameter-type-id",
		Required: true,
		Usage:    `The type of the parameter in terms of data structure. (one)`,
	},
}
var ParameterCommonInteractiveCliFlags = []fireback.CliInteractiveFlag{
	{
		Name:        "name",
		StructField: "Name",
		Required:    true,
		Recommended: false,
		Usage:       `Name of the parameter which is gonna be available in category search. e.g. Color, Length, Width`,
		Type:        "string",
	},
	{
		Name:        "description",
		StructField: "Description",
		Required:    false,
		Recommended: false,
		Usage:       `Describe the parameter so selection is easier for content management.`,
		Type:        "string",
	},
}
var ParameterCommonCliFlagsOptional = []cli.Flag{
	&cli.StringFlag{
		Name:     "x-src",
		Required: false,
		Usage:    `Import the body of the request from a file (e.g. json/yaml) on the disk`,
	},
	&cli.StringFlag{
		Name:  "x-accept",
		Usage: "Return type of the the content, such as json or yaml",
	},
	&cli.StringFlag{
		Name:     "wid",
		Required: false,
		Usage:    "Provide workspace id, if you want to change the data workspace",
	},
	&cli.StringFlag{
		Name:     "uid",
		Required: false,
		Usage:    "Unique Id - external unique hash to query entity",
	},
	&cli.StringFlag{
		Name:     "pid",
		Required: false,
		Usage:    " Parent record id of the same type",
	},
	&cli.StringFlag{
		Name:     "name",
		Required: true,
		Usage:    `Name of the parameter which is gonna be available in category search. e.g. Color, Length, Width (string)`,
	},
	&cli.StringFlag{
		Name:     "description",
		Required: false,
		Usage:    `Describe the parameter so selection is easier for content management. (string)`,
	},
	&cli.StringFlag{
		Name:     "parameter-type-id",
		Required: true,
		Usage:    `The type of the parameter in terms of data structure. (one)`,
	},
}
var ParameterCreateCmd cli.Command = PARAMETER_ACTION_POST_ONE.ToCli()
var ParameterCreateInteractiveCmd cli.Command = cli.Command{
	Name:  "ic",
	Usage: "Creates a new entity, using requied fields in an interactive name",
	Flags: []cli.Flag{
		&cli.BoolFlag{
			Name:  "all",
			Usage: "Interactively asks for all inputs, not only required ones",
		},
	},
	Action: func(c *cli.Context) {
		query := fireback.CommonCliQueryDSLBuilderAuthorize(c, &fireback.SecurityModel{
			ActionRequires: []fireback.PermissionInfo{PERM_ROOT_PARAMETER_CREATE},
		})
		entity := &ParameterEntity{}
		fireback.PopulateInteractively(entity, c, ParameterCommonInteractiveCliFlags)
		if entity, err := ParameterActions.Create(entity, query); err != nil {
			fmt.Println(err.Error())
		} else {
			f, _ := yaml.Marshal(entity)
			fmt.Println(fireback.FormatYamlKeys(string(f)))
		}
	},
}
var ParameterUpdateCmd cli.Command = cli.Command{
	Name:    "update",
	Aliases: []string{"u"},
	Flags:   ParameterCommonCliFlagsOptional,
	Usage:   "Updates entity by passing the parameters",
	Action: func(c *cli.Context) error {
		query := fireback.CommonCliQueryDSLBuilderAuthorize(c, &fireback.SecurityModel{
			ActionRequires: []fireback.PermissionInfo{PERM_ROOT_PARAMETER_UPDATE},
		})
		entity := CastParameterFromCli(c)
		if entity, err := ParameterActions.Update(query, entity); err != nil {
			fmt.Println(err.Error())
		} else {
			f, _ := json.MarshalIndent(entity, "", "  ")
			fmt.Println(string(f))
		}
		return nil
	},
}

func (x *ParameterEntity) FromCli(c *cli.Context) *ParameterEntity {
	return CastParameterFromCli(c)
}
func CastParameterFromCli(c *cli.Context) *ParameterEntity {
	template := &ParameterEntity{}
	fireback.HandleXsrc(c, template)
	if c.IsSet("uid") {
		template.UniqueId = c.String("uid")
	}
	if c.IsSet("pid") {
		template.ParentId = fireback.NewStringAutoNull(c.String("pid"))
	}
	if c.IsSet("name") {
		template.Name = c.String("name")
	}
	if c.IsSet("description") {
		template.Description = c.String("description")
	}
	if c.IsSet("parameter-type-id") {
		template.ParameterTypeId = fireback.NewStringAutoNull(c.String("parameter-type-id"))
	}
	return template
}
func ParameterSyncSeederFromFs(fsRef *embed.FS, fileNames []string, q fireback.QueryDSL) {
	fireback.SeederFromFSImport(
		q,
		ParameterActions.Create,
		reflect.ValueOf(&ParameterEntity{}).Elem(),
		fsRef,
		fileNames,
		true,
	)
}
func ParameterSyncSeeders() {
	fireback.SeederFromFSImport(
		fireback.QueryDSL{WorkspaceId: fireback.USER_SYSTEM},
		ParameterActions.Create,
		reflect.ValueOf(&ParameterEntity{}).Elem(),
		parameterSeedersFs,
		[]string{},
		true,
	)
}
func ParameterImportMocks() {
	fireback.SeederFromFSImport(
		fireback.QueryDSL{},
		ParameterActions.Create,
		reflect.ValueOf(&ParameterEntity{}).Elem(),
		&mocks.ViewsFs,
		[]string{},
		false,
	)
}
func ParameterWriteQueryMock(ctx fireback.MockQueryContext) {
	for _, lang := range ctx.Languages {
		itemsPerPage := 9999
		if ctx.ItemsPerPage > 0 {
			itemsPerPage = ctx.ItemsPerPage
		}
		f := fireback.QueryDSL{ItemsPerPage: itemsPerPage, Language: lang, WithPreloads: ctx.WithPreloads, Deep: true}
		items, count, _ := ParameterActions.Query(f)
		result := fireback.QueryEntitySuccessResult(f, items, count)
		fireback.WriteMockDataToFile(lang, "", "Parameter", result)
	}
}
func ParametersActionQueryString(keyword string, page int) ([]string, *fireback.QueryResultMeta, *fireback.IError) {
	searchFields := []string{
		`unique_id %"{keyword}"%`,
		`name %"{keyword}"%`,
	}
	m := func(item *ParameterEntity) string {
		label := item.UniqueId
		// if item.Name != nil {
		// 	label += " >>> " + *item.Name
		// }
		return label
	}
	query := fireback.QueryStringCastCli(searchFields, keyword, page)
	items, meta, err := ParameterActions.Query(query)
	stringItems := []string{}
	for _, item := range items {
		label := m(item)
		stringItems = append(stringItems, label)
	}
	return stringItems, meta, err
}

var ParameterDevCommands = []cli.Command{
	ParameterWipeCmd,
	{
		Name:  "mock",
		Usage: "Generates mock records based on the entity definition",
		Flags: []cli.Flag{
			&cli.IntFlag{
				Name:  "count",
				Usage: "how many activation key do you need to be generated and stored in database",
				Value: 10,
			},
			&cli.BoolFlag{
				Name:  "batch",
				Usage: "Multiple insert into database mode. Might miss children and relations at the moment",
			},
		},
		Action: func(c *cli.Context) error {
			query := fireback.CommonCliQueryDSLBuilderAuthorize(c, &fireback.SecurityModel{
				ActionRequires: []fireback.PermissionInfo{PERM_ROOT_PARAMETER_CREATE},
			})
			if c.Bool("batch") {
				ParameterActionSeederMultiple(query, c.Int("count"))
			} else {
				ParameterActionSeeder(query, c.Int("count"))
			}
			return nil
		},
	},
	{
		Name:    "init",
		Aliases: []string{"i"},
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:  "format",
				Usage: "Format of the export or import file. Can be 'yaml', 'yml', 'json'",
				Value: "yaml",
			},
		},
		Usage: "Creates a basic seeder file for you, based on the definition module we have. You can populate this file as an example",
		Action: func(c *cli.Context) error {
			seed := ParameterActions.SeederInit()
			fireback.CommonInitSeeder(strings.TrimSpace(c.String("format")), seed)
			return nil
		},
	},
	cli.Command{
		Name:  "mlist",
		Usage: "Prints the list of embedded mocks into the app",
		Action: func(c *cli.Context) error {
			if entity, err := fireback.GetSeederFilenames(&mocks.ViewsFs, ""); err != nil {
				fmt.Println(err.Error())
			} else {
				f, _ := json.MarshalIndent(entity, "", "  ")
				fmt.Println(string(f))
			}
			return nil
		},
	},
	cli.Command{
		Name:  "msync",
		Usage: "Tries to sync mocks into the system",
		Action: func(c *cli.Context) error {
			fireback.CommonCliImportEmbedCmd(c,
				ParameterActions.Create,
				reflect.ValueOf(&ParameterEntity{}).Elem(),
				&mocks.ViewsFs,
			)
			return nil
		},
	},
}
var ParameterImportExportCommands = []cli.Command{
	{
		Name:    "validate",
		Aliases: []string{"v"},
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:  "file",
				Usage: "Validates an import file, such as yaml, json, csv, and gives some insights how the after import it would look like",
				Value: "parameter-seeder-parameter.yml",
				// Uncomment before publish, they need to specify
				// Required: true,
			},
			&cli.StringFlag{
				Name:  "format",
				Usage: "Format of the export or import file. Can be 'yaml', 'yml', 'json'",
				Value: "yaml",
			},
		},
		Usage: "Reads a yaml file containing an array of parameters, you can run this to validate if your import file is correct, and how it would look like after import",
		Action: func(c *cli.Context) error {
			data := &[]ParameterEntity{}
			fireback.ReadYamlFile(c.String("file"), data)
			fmt.Println(data)
			return nil
		},
	},
	cli.Command{
		Name:  "slist",
		Usage: "Prints the list of files attached to this module for syncing or bootstrapping project",
		Action: func(c *cli.Context) error {
			if entity, err := fireback.GetSeederFilenames(parameterSeedersFs, ""); err != nil {
				fmt.Println(err.Error())
			} else {
				f, _ := json.MarshalIndent(entity, "", "  ")
				fmt.Println(string(f))
			}
			return nil
		},
	},
	cli.Command{
		Name:  "ssync",
		Usage: "Tries to sync the embedded content into the database, the list could be seen by 'slist' command",
		Action: func(c *cli.Context) error {
			fireback.CommonCliImportEmbedCmd(c,
				ParameterActions.Create,
				reflect.ValueOf(&ParameterEntity{}).Elem(),
				parameterSeedersFs,
			)
			return nil
		},
	},
	cli.Command{
		Name:    "export",
		Aliases: []string{"e"},
		Flags: append(fireback.CommonQueryFlags,
			&cli.StringFlag{
				Name:     "file",
				Usage:    "The address of file you want the csv/yaml/json be exported to",
				Required: true,
			}),
		Usage: "Exports a query results into the csv/yaml/json format",
		Action: func(c *cli.Context) error {
			return fireback.CommonCliExportCmd2(c,
				ParameterEntityStream,
				reflect.ValueOf(&ParameterEntity{}).Elem(),
				c.String("file"),
				&metas.MetaFs,
				"ParameterFieldMap.yml",
				ParameterPreloadRelations,
			)
		},
	},
	cli.Command{
		Name: "import",
		Flags: append(
			append(
				fireback.CommonQueryFlags,
				&cli.StringFlag{
					Name:     "file",
					Usage:    "The address of file you want the csv be imported from",
					Required: true,
				}),
			ParameterCommonCliFlagsOptional...,
		),
		Usage: "imports csv/yaml/json file and place it and its children into database",
		Action: func(c *cli.Context) error {
			fireback.CommonCliImportCmdAuthorized(c,
				ParameterActions.Create,
				reflect.ValueOf(&ParameterEntity{}).Elem(),
				c.String("file"),
				&fireback.SecurityModel{
					ActionRequires: []fireback.PermissionInfo{PERM_ROOT_PARAMETER_CREATE},
				},
				func() ParameterEntity {
					v := CastParameterFromCli(c)
					return *v
				},
			)
			return nil
		},
	},
}
var ParameterCliCommands []cli.Command = []cli.Command{
	PARAMETER_ACTION_QUERY.ToCli(),
	PARAMETER_ACTION_TABLE.ToCli(),
	PARAMETER_ACTION_PATCH.ToCli(),
	ParameterCreateCmd,
	ParameterAskCmd,
	ParameterCreateInteractiveCmd,
	fireback.GetCommonRemoveQuery(
		reflect.ValueOf(&ParameterEntity{}).Elem(),
		ParameterActions.Remove,
	),
}

func ParameterCliFn() cli.Command {
	commands := append(ParameterImportExportCommands, ParameterCliCommands...)
	if !fireback.GetConfig().Production {
		commands = append(commands, ParameterDevCommands...)
	}
	return cli.Command{
		Name:        "parameter",
		ShortName:   "pa",
		Description: "Parameters module actions",
		Usage:       `A list of parameters that we assign to product category (or product instance) and they are unique references across the entire data.`,
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:  "language",
				Value: "en",
			},
		},
		Subcommands: commands,
	}
}

var PARAMETER_ACTION_TABLE = fireback.Module3Action{
	Name:          "table",
	ActionAliases: []string{"t"},
	Flags:         fireback.CommonQueryFlags,
	Description:   "Table formatted queries all of the entities in database based on the standard query format",
	Action:        ParameterActions.Query,
	CliAction: func(c *cli.Context, security *fireback.SecurityModel) error {
		fireback.CommonCliTableCmd2(c,
			ParameterActions.Query,
			security,
			reflect.ValueOf(&ParameterEntity{}).Elem(),
		)
		return nil
	},
}
var PARAMETER_ACTION_QUERY = fireback.Module3Action{
	Method: "GET",
	Url:    "/parameters",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_PARAMETER_QUERY},
	},
	Handlers: []gin.HandlerFunc{
		func(c *gin.Context) {
			qs := &ParameterEntityQs{}
			fireback.HttpQueryEntity(c, ParameterActions.Query, qs)
		},
	},
	Format:         "QUERY",
	Action:         ParameterActions.Query,
	ResponseEntity: &[]ParameterEntity{},
	Out: &fireback.Module3ActionBody{
		Entity: "ParameterEntity",
	},
	CliAction: func(c *cli.Context, security *fireback.SecurityModel) error {
		qs := &ParameterEntityQs{}
		fireback.CommonCliQueryCmd3(
			c,
			ParameterActions.Query,
			security,
			qs,
		)
		return nil
	},
	CliName:       "query",
	Name:          "query",
	ActionAliases: []string{"q"},
	Flags:         append(fireback.CommonQueryFlags, ParameterQsFlags...),
	Description:   "Queries all of the entities in database based on the standard query format (s+)",
}
var PARAMETER_ACTION_EXPORT = fireback.Module3Action{
	Method: "GET",
	Url:    "/parameters/export",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_PARAMETER_QUERY},
	},
	Handlers: []gin.HandlerFunc{
		func(c *gin.Context) {
			fireback.HttpStreamFileChannel(c, ParameterActionExport)
		},
	},
	Format:         "QUERY",
	Action:         ParameterActionExport,
	ResponseEntity: &[]ParameterEntity{},
	Out: &fireback.Module3ActionBody{
		Entity: "ParameterEntity",
	},
}
var PARAMETER_ACTION_GET_ONE = fireback.Module3Action{
	Method: "GET",
	Url:    "/parameter/:uniqueId",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_PARAMETER_QUERY},
	},
	Handlers: []gin.HandlerFunc{
		func(c *gin.Context) {
			fireback.HttpGetEntity(c, ParameterActions.GetOne)
		},
	},
	Format:         "GET_ONE",
	Action:         ParameterActions.GetOne,
	ResponseEntity: &ParameterEntity{},
	Out: &fireback.Module3ActionBody{
		Entity: "ParameterEntity",
	},
}
var PARAMETER_ACTION_POST_ONE = fireback.Module3Action{
	Name:          "create",
	ActionAliases: []string{"c"},
	Description:   "Create new parameter",
	Flags:         ParameterCommonCliFlags,
	Method:        "POST",
	Url:           "/parameter",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_PARAMETER_CREATE},
	},
	Handlers: []gin.HandlerFunc{
		func(c *gin.Context) {
			fireback.HttpPostEntity(c, ParameterActions.Create)
		},
	},
	CliAction: func(c *cli.Context, security *fireback.SecurityModel) error {
		result, err := fireback.CliPostEntity(c, ParameterActions.Create, security)
		fireback.HandleActionInCli(c, result, err, map[string]map[string]string{})
		if err != nil {
			return err
		}
		return nil
	},
	Action:         ParameterActions.Create,
	Format:         "POST_ONE",
	RequestEntity:  &ParameterEntity{},
	ResponseEntity: &ParameterEntity{},
	Out: &fireback.Module3ActionBody{
		Entity: "ParameterEntity",
	},
	In: &fireback.Module3ActionBody{
		Entity: "ParameterEntity",
	},
}
var PARAMETER_ACTION_PATCH = fireback.Module3Action{
	Name:          "update",
	ActionAliases: []string{"u"},
	Flags:         ParameterCommonCliFlagsOptional,
	Method:        "PATCH",
	Url:           "/parameter",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_PARAMETER_UPDATE},
	},
	Handlers: []gin.HandlerFunc{
		func(c *gin.Context) {
			fireback.HttpUpdateEntity(c, ParameterActions.Update)
		},
	},
	Action:         ParameterActions.Update,
	RequestEntity:  &ParameterEntity{},
	ResponseEntity: &ParameterEntity{},
	Format:         "PATCH_ONE",
	Out: &fireback.Module3ActionBody{
		Entity: "ParameterEntity",
	},
	In: &fireback.Module3ActionBody{
		Entity: "ParameterEntity",
	},
	Description: "Update the Parameter entity by unique id",
	CliName:     "update",
	CliAction: func(c *cli.Context, security *fireback.SecurityModel) error {
		result, err := fireback.CliPatchEntity(c, ParameterActions.Update, security)
		fireback.HandleActionInCli(c, result, err, map[string]map[string]string{})
		if err != nil {
			return err
		}
		return nil
	},
}
var PARAMETER_ACTION_PATCH_BULK = fireback.Module3Action{
	Method: "PATCH",
	Url:    "/parameters",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_PARAMETER_UPDATE},
	},
	Handlers: []gin.HandlerFunc{
		func(c *gin.Context) {
			fireback.HttpUpdateEntities(c, ParameterActionBulkUpdate)
		},
	},
	Action:         ParameterActionBulkUpdate,
	Format:         "PATCH_BULK",
	RequestEntity:  &fireback.BulkRecordRequest[ParameterEntity]{},
	ResponseEntity: &fireback.BulkRecordRequest[ParameterEntity]{},
	Out: &fireback.Module3ActionBody{
		Entity: "ParameterEntity",
	},
	In: &fireback.Module3ActionBody{
		Entity: "ParameterEntity",
	},
}
var PARAMETER_ACTION_DELETE = fireback.Module3Action{
	Method: "DELETE",
	Url:    "/parameter",
	Format: "DELETE_DSL",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_PARAMETER_DELETE},
	},
	Handlers: []gin.HandlerFunc{
		func(c *gin.Context) {
			fireback.HttpRemoveEntity(c, ParameterActions.Remove)
		},
	},
	Action:         ParameterActions.Remove,
	RequestEntity:  &fireback.DeleteRequest{},
	ResponseEntity: &fireback.DeleteResponse{},
	TargetEntity:   &ParameterEntity{},
}

/**
 *	Override this function on ParameterEntityHttp.go,
 *	In order to add your own http
 **/
var AppendParameterRouter = func(r *[]fireback.Module3Action) {}

func GetParameterModule3Actions() []fireback.Module3Action {
	routes := []fireback.Module3Action{
		PARAMETER_ACTION_QUERY,
		PARAMETER_ACTION_EXPORT,
		PARAMETER_ACTION_GET_ONE,
		PARAMETER_ACTION_POST_ONE,
		PARAMETER_ACTION_PATCH,
		PARAMETER_ACTION_PATCH_BULK,
		PARAMETER_ACTION_DELETE,
	}
	// Append user defined functions
	AppendParameterRouter(&routes)
	return routes
}

var PERM_ROOT_PARAMETER = fireback.PermissionInfo{
	CompleteKey: "root.modules.product.parameter.*",
	Name:        "Entire parameter actions (*)",
	Description: "",
}
var PERM_ROOT_PARAMETER_DELETE = fireback.PermissionInfo{
	CompleteKey: "root.modules.product.parameter.delete",
	Name:        "Delete parameter",
	Description: "",
}
var PERM_ROOT_PARAMETER_CREATE = fireback.PermissionInfo{
	CompleteKey: "root.modules.product.parameter.create",
	Name:        "Create parameter",
	Description: "",
}
var PERM_ROOT_PARAMETER_UPDATE = fireback.PermissionInfo{
	CompleteKey: "root.modules.product.parameter.update",
	Name:        "Update parameter",
	Description: "",
}
var PERM_ROOT_PARAMETER_QUERY = fireback.PermissionInfo{
	CompleteKey: "root.modules.product.parameter.query",
	Name:        "Query parameter",
	Description: "",
}
var ALL_PARAMETER_PERMISSIONS = []fireback.PermissionInfo{
	PERM_ROOT_PARAMETER_DELETE,
	PERM_ROOT_PARAMETER_CREATE,
	PERM_ROOT_PARAMETER_UPDATE,
	PERM_ROOT_PARAMETER_QUERY,
	PERM_ROOT_PARAMETER,
}

func NewParameterCreatedEvent(
	payload *ParameterEntity,
	query *fireback.QueryDSL,
) (*fireback.Event, error) {
	event := &fireback.Event{
		Name:    "ParameterCreated",
		Payload: payload,
		Security: &fireback.SecurityModel{
			ActionRequires: []fireback.PermissionInfo{
				PERM_ROOT_PARAMETER_QUERY,
			},
		},
		CacheKey: "*product.ParameterEntity",
	}
	// Apply the source of the event based on querydsl
	fireback.ApplyQueryDslContextToEvent(event, *query)
	return event, nil
}
func NewParameterUpdatedEvent(
	payload *ParameterEntity,
	query *fireback.QueryDSL,
) (*fireback.Event, error) {
	event := &fireback.Event{
		Name:    "ParameterUpdated",
		Payload: payload,
		Security: &fireback.SecurityModel{
			ActionRequires: []fireback.PermissionInfo{
				PERM_ROOT_PARAMETER_QUERY,
			},
		},
		CacheKey: "*product.ParameterEntity",
	}
	// Apply the source of the event based on querydsl
	fireback.ApplyQueryDslContextToEvent(event, *query)
	return event, nil
}

var ParameterEntityBundle = fireback.EntityBundle{
	Permissions: ALL_PARAMETER_PERMISSIONS,
	// Cli command has been exluded, since we use module to wrap all the entities
	// to be more easier to wrap up.
	// Create your own bundle if you need with Cli
	//CliCommands: []cli.Command{
	//	ParameterCliFn(),
	//},
	Actions:      GetParameterModule3Actions(),
	MockProvider: ParameterImportMocks,
	AutoMigrationEntities: []interface{}{
		&ParameterEntity{},
		&ParameterEntityPolyglot{},
	},
	MigrationScripts: []fireback.MigrationScript{},
}
