package product

/*
*	Generated by fireback 1.2.4
*	Written by Ali Torabi.
*	Checkout the repository for licenses and contribution: https://github.com/torabian/fireback
 */
func init() {
	// You can override default actions that fireback generates here,
	// or use this file to implement some extra business logic, related to the entity.
	// By default all the functions are assigned to Fireback generate code which ends in Fn
	// You can customize, or customize and still call Fireback implementation
	/*
		ParameterTypeActions.Create = func(dto *ParameterTypeEntity, query QueryDSL) (*ParameterTypeEntity, *IError) {
			// Do something before hand
			result, err := ParameterTypeActionCreateFn(dto, query)
			// Do something after fireback
			return result, err
		}
	*/
}
