package product

/*
*	Generated by fireback 1.2.4
*	Written by Ali Torabi.
*	Checkout the repository for licenses and contribution: https://github.com/torabian/fireback
 */
import (
	"github.com/torabian/fireback/modules/fireback"
	"github.com/urfave/cli"
)
import (
	"reflect"
)

// using shared actions here
func ProductCustomActions() []fireback.Module3Action {
	routes := []fireback.Module3Action{}
	return routes
}

var ProductCustomActionsCli = []cli.Command{}

// Only to include some headers
func ProductJsonInclude() {
	str4 := reflect.ValueOf(nil)
	_ = str4
}

// Use the actions bundle for ease and provide it to the ModuleProvider
// and it would gather all actions in the module level
var ProductCliActionsBundle = &fireback.CliActionsBundle{
	Name:  "product",
	Usage: `A module to manage product catalog itself.`,
	// Here we will include entities actions, as well as module level actions
	Subcommands: cli.Commands{
		ParameterTypeCliFn(),
		ParameterCliFn(),
		CategoryCliFn(),
		ProductCliFn(),
	},
}

func GetProductActionsBundle() *fireback.ModuleActionsBundle {
	return &fireback.ModuleActionsBundle{
		Actions:   ProductCustomActions(),
		CliAction: ProductCliActionsBundle,
	}
}
func GetProductActionsCli() []cli.Command {
	return ProductCustomActionsCli
}
