name: product
description: 
  A module to manage product catalog itself.
# This is a Module3.yml file format which is a complex definition of entities,
# actions, dtos, queries, and many more necessary things for a project.
# Make sure you have installed correct vscode extensions, to get intelisense and auto-save feature.
# You can read about extensions here:
# https://torabian.github.io/fireback/docs/vscode-extension-and-developing

# also learn how to create Module3.yml files:
# https://torabian.github.io/fireback/docs/module3-definition/

entities:
  - name: parameterType
    cliShort: pt
    description: 
      A minimal representation of a type of a parameter.
    fields:
      - name: name
        type: string
        translate: true
        validate: required
        description: 
          Type of the parameter which can be selected for a parameter
      - name: description
        type: string
        translate: true
        description: 
          Describe the parameter type so selection is easier for content management.

      # I doubt it, if unique id code be enough.
      - name: bindingKey
        type: string
        validate: required
        description: 
          A unique key that would bind this type to programming langauge base on limits
          in the code base.
  - name: parameter
    description: 
      A list of parameters that we assign to product category (or product instance)
      and they are unique references across the entire data.
    cliShort: pa
    fields:
      - name: name
        type: string
        translate: true
        validate: required
        description: 
          Name of the parameter which is gonna be available in category search.
          e.g. Color, Length, Width
      - name: description
        type: string
        translate: true
        description: 
          Describe the parameter so selection is easier for content management.
      - name: parameterType
        description: 
          The type of the parameter in terms of data structure.
        type: one
        validate: required
        target: ParameterTypeEntity

  - name: category
    description: 
      Represting categories across the products, which can have product or child categories,
      or both at the same time.
    cte: true
    fields:
      - name: name
        type: string
        translate: true
        validate: required
        description: 
          Name of the category

      - name: parameters
        type: array
        description: 
          The parameters this category has (itself),
          and this value will be used when creating a new product for the category.
        fields:
          - name: parameter
            type: one
            target: ParameterEntity
            description: The original parameter which will be required
            validate: required
          - name: isRequired
            type: bool?
            description: 
              If the parameter is required to create a product

      - name: attributes
        description: 
          Custom attributes for the product which will be created in the category.
        fields:
          - name: name
            description: Name of the attribute
            type: string
          - name: isRequired
            type: bool?
            description: 
              If the attribute is required to be entered for the product we are creating.

  - name: product
    description: 
      Product is anything tangible which is sellable on the platform
    fields:
      - name: name
        type: string
        translate: true
        description: 
          Name of the product
      - name: description
        type: text
        translate: true
        description: 
          The description of the product.
      - name: assets
        type: array
        fields:
          - name: asset
            type: xfile?
            description: The file (image/video) anything which is an asset to be used or shown
          - name: tag
            description: Custom tag string for the asset to group or recognize later on.
            type: string
      - name: parameters
        description: 
          The product parameters snapshot
        type: array
        fields:
          - name: parameter
            type: one
            target: ParameterEntity
            description: The original parameter which will be required
            validate: required
          - name: parameterSnapshot
            type: string
            description: Keep a value of the parameter snapshot for case deleted original value
            validate: required
          - name: value
            type: string
            description: 
              The field value in case of string
          - name: valueNumeric
            type: float64
            description: 
              The field value in case of numeric values