package product

import (
	"fmt"

	"github.com/torabian/fireback/modules/fireback"
)

/*
*	Generated by fireback 1.2.4
*	Written by Ali Torabi.
*	Checkout the repository for licenses and contribution: https://github.com/torabian/fireback
 */

func printMB(name string, b []byte) {
	mb := float64(len(b)) / (1024 * 1024)
	fmt.Printf("%s: %.2f MB\n", name, mb)
}

func init() {

	image, _ := GeneratePNGBlob(500, 500, 10, 0)
	image1, _ := GeneratePNGBlob(250, 250, 10, 0)
	image2, _ := GeneratePNGBlob(250, 250, 10, 0)
	image3, _ := GeneratePNGBlob(250, 250, 10, 0)
	image4, _ := GeneratePNGBlob(250, 250, 10, 0)

	printMB("image", image)
	printMB("image1", image1)
	printMB("image2", image2)
	printMB("image3", image3)
	printMB("image4", image4)

	// You can override default actions that fireback generates here,
	// or use this file to implement some extra business logic, related to the entity.
	// By default all the functions are assigned to Fireback generate code which ends in Fn
	// You can customize, or customize and still call Fireback implementation

	ProductActions.SeederInit = func() *ProductEntity {

		return &ProductEntity{
			Name:        "Sample product this is a great product of al time.",
			Description: "Product description here.Product description here.Product description here.Product description here.Product description here.Product description here.Product description here.Product description here.Product description here.Product description here.Product description here.Product description here.Product description here.Product description here.Product description here.Product description here.Product description here.Product description here.Product description here.Product description here.Product description here.Product description here.Product description here.Product description here.",
			Assets: []*ProductAssets{
				{
					Asset: fireback.XFile{Blob: image},
					Tag:   "general-image",
				},
				{
					Asset: fireback.XFile{Blob: image1},
					Tag:   "slide-1",
				},
				{
					Asset: fireback.XFile{Blob: image2},
					Tag:   "slide-2",
				},
				{
					Asset: fireback.XFile{Blob: image3},
					Tag:   "slide-3",
				},
				{
					Asset: fireback.XFile{Blob: image4},
					Tag:   "slide-4",
				},
			},
		}
	}

}
