name: Build and deploy to github pages.

on:
  pull_request:   # run on every PR
    branches: ["*"]
  push:           # still run on main push
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3


      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 24

      
      - name: Install dependencies
        run: npm ci

      - name: Build the website
        run: npm run build
      
      - name: Deploy pages 🚀
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./build
